#include "THISDUST.H"
#include "MENUFACE.H"


// decompiled code
// original method signature: 
// char * /*$ra*/ NextTimAddr(char *addr /*$a0*/, int w /*$a1*/, int h /*$a2*/, enum bdepth bpp /*$a3*/)
 // line 25, offset 0x800b9538
	/* begin block 1 */
		// Start line: 27
		// Start offset: 0x800B9538
		// Variables:
	// 		long addtl; // $v0
	/* end block 1 */
	// End offset: 0x800B9574
	// End Line: 34

	/* begin block 2 */
		// Start line: 50
	/* end block 2 */
	// End Line: 51

	/* begin block 3 */
		// Start line: 51
	/* end block 3 */
	// End Line: 52

	/* begin block 4 */
		// Start line: 52
	/* end block 4 */
	// End Line: 53

char * NextTimAddr(char *addr,int w,int h,bdepth bpp)

{
  char *unaff_s1;
  
  if ((int)unaff_s1 < 0) {
    unaff_s1 = &DAT_00000001;
  }
  return unaff_s1;
}



// decompiled code
// original method signature: 
// void /*$ra*/ menuface_initialize()
 // line 76, offset 0x800b9580
	/* begin block 1 */
		// Start line: 77
		// Start offset: 0x800B9580
		// Variables:
	// 		char *addr; // $s6
	// 		char *buttonAddr; // $s2
	// 		int i; // $s5
	// 		int j; // $s1

		/* begin block 1.1 */
			// Start line: 92
			// Start offset: 0x800B95AC
		/* end block 1.1 */
		// End offset: 0x800B9684
		// End Line: 134
	/* end block 1 */
	// End offset: 0x800B9684
	// End Line: 139

	/* begin block 2 */
		// Start line: 152
	/* end block 2 */
	// End Line: 153

	/* begin block 3 */
		// Start line: 161
	/* end block 3 */
	// End Line: 162

/* WARNING: Unknown calling convention yet parameter storage is locked */

void menuface_initialize(void)

{
  undefined4 uVar1;
  int unaff_s1;
  int iStack00000010;
  int iStack00000014;
  int iStack00000018;
  undefined4 uStack0000001c;
  
  uStack0000001c = 1;
  iStack00000010 = PAUSE_WIDTH;
  iStack00000014 = LINESKIP;
  iStack00000018 = ITEMSKIP;
  hack_attract = 0;
  FUN_800b7bf8(*(undefined4 *)(unaff_s1 + 0x20),1,PAUSE_XPOS,PAUSE_YPOS);
  iStack00000010 = FUN_800b7b80(0x21);
  FUN_800b7cf0(*(undefined4 *)(unaff_s1 + 0x20),0,0,4);
  uVar1 = FUN_800b7b80(0x27);
  FUN_800b7d80(*(undefined4 *)(unaff_s1 + 0x20),FUN_800b8b48,&LAB_80014180,uVar1);
  if ((draw[1].dr_env.code[10] & 4) == 0) {
    uVar1 = FUN_800b7b80(0x29);
    FUN_800b7d80(*(undefined4 *)(unaff_s1 + 0x20),FUN_800b8be0,0,uVar1);
    uVar1 = FUN_800b7b80(0x1f);
    FUN_800b7d80(*(undefined4 *)(unaff_s1 + 0x20),FUN_800b8ad8,FUN_800b8f6c,uVar1);
    uVar1 = FUN_800b7b80(0x26);
    FUN_800b7d80(*(undefined4 *)(unaff_s1 + 0x20),FUN_800b8ad8,FUN_800b94b8,uVar1);
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ menuface_terminate()
 // line 141, offset 0x800b96ac
	/* begin block 1 */
		// Start line: 142
		// Start offset: 0x800B96AC
		// Variables:
	// 		int i; // $s3
	// 		int j; // $s0
	/* end block 1 */
	// End offset: 0x800B973C
	// End Line: 158

	/* begin block 2 */
		// Start line: 329
	/* end block 2 */
	// End Line: 330

	/* begin block 3 */
		// Start line: 332
	/* end block 3 */
	// End Line: 333

/* WARNING: Unknown calling convention yet parameter storage is locked */

void menuface_terminate(void)

{
  return;
}



// autogenerated function stub: 
// void /*$ra*/ MENUFACE_ChangeStateRandomly(int index /*$a0*/)
void MENUFACE_ChangeStateRandomly(int index)
{ // line 163, offset 0x800b9758
	/* begin block 1 */
		// Start line: 164
		// Start offset: 0x800B9758
		// Variables:
			struct menuface_t *face; // $s1
			struct menuface_t *lastFace; // $s3

		/* begin block 1.1 */
			// Start line: 177
			// Start offset: 0x800B97B0
		/* end block 1.1 */
		// End offset: 0x800B9808
		// End Line: 182
	/* end block 1 */
	// End offset: 0x800B9860
	// End Line: 195

	/* begin block 2 */
		// Start line: 381
	/* end block 2 */
	// End Line: 382

	/* begin block 3 */
		// Start line: 384
	/* end block 3 */
	// End Line: 385

}


// decompiled code
// original method signature: 
// void /*$ra*/ MENUFACE_RefreshFaces()
 // line 198, offset 0x800b987c
	/* begin block 1 */
		// Start line: 199
		// Start offset: 0x800B987C
		// Variables:
	// 		int i; // $s3
	// 		struct menuface_t *face; // $s2
	/* end block 1 */
	// End offset: 0x800B9908
	// End Line: 218

	/* begin block 2 */
		// Start line: 474
	/* end block 2 */
	// End Line: 475

	/* begin block 3 */
		// Start line: 478
	/* end block 3 */
	// End Line: 479

/* WARNING: Unknown calling convention yet parameter storage is locked */

void MENUFACE_RefreshFaces(void)

{
  uint in_v0;
  uint unaff_s0;
  int unaff_s1;
  int unaff_s2;
  int unaff_s3;
  
  do {
    if (in_v0 == 0) {
      unaff_s2 = unaff_s2 + 7;
      unaff_s3 = unaff_s3 + 1;
      unaff_s1 = unaff_s1 + 0x10;
      if (7 < unaff_s3) {
                    /* WARNING: Subroutine does not return */
        FUN_8004fe84(PTR_ARRAY_800d5a20[1]);
      }
      unaff_s0 = 0;
    }
    if (((int)(uint)*(ushort *)(unaff_s1 + 0xe) >> (unaff_s0 & 0x1f) & 1U) != 0) {
      FUN_8002acac(PTR_ARRAY_800d5a20[1] + (unaff_s2 + unaff_s0) * 8);
    }
    unaff_s0 = unaff_s0 + 1;
    in_v0 = (uint)((int)unaff_s0 < 7);
  } while( true );
}





