#include "THISDUST.H"
#include "ALGOCTRL.H"


// decompiled code
// original method signature: 
// void /*$ra*/ InitAlgorithmicWings(struct _Instance *instance /*$s2*/)
 // line 24, offset 0x800a1c24
	/* begin block 1 */
		// Start line: 25
		// Start offset: 0x800A1C24
		// Variables:
	// 		struct _G2EulerAngles_Type Rot; // stack offset -24
	// 		unsigned char i; // $s1
	/* end block 1 */
	// End offset: 0x800A1DA4
	// End Line: 91

	/* begin block 2 */
		// Start line: 48
	/* end block 2 */
	// End Line: 49

	/* begin block 3 */
		// Start line: 59
	/* end block 3 */
	// End Line: 60

void InitAlgorithmicWings(_Instance *instance)

{
  undefined4 *puVar1;
  undefined *puVar2;
  int *unaff_s0;
  int unaff_s1;
  int unaff_s2;
  
code_r0x800a1c24:
  Raziel.currentHint = 8;
  Raziel._1312_4_ = 0;
  FUN_8009060c(*unaff_s0 + 0x194);
  FUN_8009060c(*unaff_s0 + 0x194,0,0xe,300);
  FUN_8009060c(*unaff_s0 + 0x194,0,8,300);
  FUN_8009060c(*unaff_s0 + 0x194,0xe,0xe,300);
  FUN_8009060c(*unaff_s0 + 0x194,0x32,0x4c,300);
  FUN_8009060c(*unaff_s0 + 0x194,0x3a,0x4c,300);
LAB_800a1cbc:
  FUN_800a5ffc();
  *(uint *)(*unaff_s0 + 0x18) = *(uint *)(*unaff_s0 + 0x18) | 0x40;
LAB_800a1b54:
  do {
    while( true ) {
      do {
        PurgeMessageQueue((__MessageQueue *)(unaff_s2 + 4));
        puVar1 = (undefined4 *)FUN_800707ac(unaff_s2 + 4);
        if (puVar1 == (undefined4 *)0x0) {
          return;
        }
        puVar2 = (undefined *)*puVar1;
        if (puVar2 == &DAT_00100004) goto LAB_800a1cbc;
        if (0x100004 < (int)puVar2) goto LAB_800a1bcc;
      } while (puVar2 == &DAT_80000008);
      if (-0x7ffffff8 < (int)puVar2) break;
      if (puVar2 != (undefined *)0x80000000) {
        if (puVar2 != (undefined *)0x80000001) goto LAB_800a1d3c;
        FUN_80070800(unaff_s2 + 0x8c,0x80000001,0);
      }
    }
  } while (puVar2 == &DAT_80000020);
  if (puVar2 == &DAT_00100001) goto LAB_800a1c1c;
  goto LAB_800a1d3c;
LAB_800a1bcc:
  if (puVar2 == (undefined *)0x4010008) goto LAB_800a1b54;
  if ((int)puVar2 < 0x4010009) {
    if ((puVar2 == (undefined *)0x1000001) || (puVar2 == (undefined *)0x4000001)) goto LAB_800a1b54;
  }
  else {
    if (puVar2 == (undefined *)0x4020000) goto LAB_800a1b54;
    if (puVar2 == (undefined *)0x8000000) {
      FUN_80071b48();
      FUN_800725cc();
      goto LAB_800a1b54;
    }
  }
LAB_800a1d3c:
  FUN_800b0280();
  goto LAB_800a1b54;
LAB_800a1c1c:
  if (unaff_s1 == 0) goto code_r0x800a1c24;
  goto LAB_800a1cbc;
}



// autogenerated function stub: 
// void /*$ra*/ DeInitAlgorithmicWings(struct _Instance *instance /*$s1*/)
void DeInitAlgorithmicWings(struct _Instance *instance)
{ // line 94, offset 0x800a1dbc
	/* begin block 1 */
		// Start line: 95
		// Start offset: 0x800A1DBC
		// Variables:
			unsigned char i; // $s0
	/* end block 1 */
	// End offset: 0x800A1E38
	// End Line: 114

	/* begin block 2 */
		// Start line: 219
	/* end block 2 */
	// End Line: 220

	/* begin block 3 */
		// Start line: 225
	/* end block 3 */
	// End Line: 226

}


// decompiled code
// original method signature: 
// void /*$ra*/ AlgorithmicWings(struct _Instance *instance /*$s0*/, struct evAnimationControllerDoneData *ControllerData /*$s1*/)
 // line 117, offset 0x800a1e4c
	/* begin block 1 */
		// Start line: 118
		// Start offset: 0x800A1E4C
		// Variables:
	// 		struct _G2EulerAngles_Type Rot; // stack offset -24
	/* end block 1 */
	// End offset: 0x800A1EA8
	// End Line: 143

	/* begin block 2 */
		// Start line: 273
	/* end block 2 */
	// End Line: 274

void AlgorithmicWings(_Instance *instance,evAnimationControllerDoneData *ControllerData)

{
  int in_v0;
  uint unaff_s1;
  int unaff_s2;
  undefined2 uStack00000018;
  undefined2 uStack0000001a;
  undefined2 uStack0000001c;
  
  if (in_v0 != 0) {
    if (*(int *)(unaff_s2 + 0x40) == 0) {
      uStack0000001c = 0;
      uStack0000001a = 0;
      uStack00000018 = 0;
                    /* WARNING: Subroutine does not return */
      FUN_800904f0(unaff_s2 + 0x194,unaff_s1 & 0xff,8);
    }
                    /* WARNING: Subroutine does not return */
    FUN_80095ff4(&stack0x00000018,*(int *)(unaff_s2 + 0x1a8) + (unaff_s1 & 0xff) * 0x20 + -0x20,0x15
                );
  }
  if (*(int *)(unaff_s2 + 0x40) == 0) {
    uStack0000001c = 0;
    uStack0000001a = 0;
    uStack00000018 = 0;
                    /* WARNING: Subroutine does not return */
    FUN_800904f0(unaff_s2 + 0x194,0x3b,8);
  }
                    /* WARNING: Subroutine does not return */
  FUN_80095ff4(&stack0x00000018,*(int *)(unaff_s2 + 0x1a8) + 0x740,0x15);
}



// decompiled code
// original method signature: 
// void /*$ra*/ AlgorithmicNeck(struct _Instance *Player /*$s1*/, struct _Instance *Target /*$s2*/)
 // line 150, offset 0x800a1ebc
	/* begin block 1 */
		// Start line: 151
		// Start offset: 0x800A1EBC
		// Variables:
	// 		struct _Position From; // stack offset -96
	// 		struct _Position To; // stack offset -88
	// 		struct _Rotation Rot1; // stack offset -80
	// 		int Diff; // $v1
	// 		struct MATRIX matrix; // stack offset -72

		/* begin block 1.1 */
			// Start line: 162
			// Start offset: 0x800A1EF0
			// Variables:
		// 		struct evCollideInstanceStatsData data; // stack offset -40
		/* end block 1.1 */
		// End offset: 0x800A1F58
		// End Line: 183

		/* begin block 1.2 */
			// Start line: 208
			// Start offset: 0x800A1FFC
			// Variables:
		// 		struct MATRIX *matrix; // $v1
		/* end block 1.2 */
		// End offset: 0x800A2034
		// End Line: 223
	/* end block 1 */
	// End offset: 0x800A2124
	// End Line: 256

	/* begin block 2 */
		// Start line: 345
	/* end block 2 */
	// End Line: 346

void AlgorithmicNeck(_Instance *Player,_Instance *Target)

{
  int in_v1;
  char unaff_s1;
  byte bVar1;
  int unaff_s2;
  int iStack00000010;
  undefined4 uStack00000014;
  undefined2 uStack00000018;
  undefined2 uStack0000001a;
  undefined2 uStack0000001c;
  
  iStack00000010 = in_v1 * 3;
  uStack00000014 = 2;
  FUN_80072464();
  bVar1 = unaff_s1 + 1;
  if (0x3d < bVar1) {
    AlgoControlFlag = AlgoControlFlag | 1;
    return;
  }
  if (*(int *)(unaff_s2 + 0x40) == 0) {
    uStack0000001c = 0;
    uStack0000001a = 0;
    uStack00000018 = 0;
                    /* WARNING: Subroutine does not return */
    FUN_800904f0(unaff_s2 + 0x194,(uint)bVar1,8);
  }
                    /* WARNING: Subroutine does not return */
  FUN_80095ff4(&stack0x00000018,*(int *)(unaff_s2 + 0x1a8) + (uint)bVar1 * 0x20 + -0x20,0x15);
}





