#include "THISDUST.H"
#include "ATTACK.H"


// decompiled code
// original method signature: 
// int /*$ra*/ StateHandlerDecodeHold(int *Message /*$s2*/, int *Data /*$s3*/)
 // line 16, offset 0x8009bb00
	/* begin block 1 */
		// Start line: 17
		// Start offset: 0x8009BB00
		// Variables:
	// 		int rc; // $s4
	// 		int WhoAmI; // $s0
	// 		struct _Instance *heldInstance; // $s1

		/* begin block 1.1 */
			// Start line: 53
			// Start offset: 0x8009BC2C
			// Variables:
		// 		int hitState; // $v1
		/* end block 1.1 */
		// End offset: 0x8009BD18
		// End Line: 90

		/* begin block 1.2 */
			// Start line: 117
			// Start offset: 0x8009BDB8
			// Variables:
		// 		struct _Instance *heldWeapon; // $v1
		/* end block 1.2 */
		// End offset: 0x8009BE1C
		// End Line: 137
	/* end block 1 */
	// End offset: 0x8009BE48
	// End Line: 147

	/* begin block 2 */
		// Start line: 32
	/* end block 2 */
	// End Line: 33

int StateHandlerDecodeHold(int *Message,int *Data)

{
  undefined4 *puVar1;
  uint uVar2;
  int iVar3;
  undefined *puVar4;
  int *unaff_s1;
  int unaff_s2;
  int unaff_s3;
  int unaff_s4;
  undefined4 unaff_s5;
  int unaff_s6;
  
code_r0x8009bb00:
  FUN_80072698();
LAB_8009b884:
  do {
    do {
      PurgeMessageQueue((__MessageQueue *)(unaff_s3 + 4));
      puVar1 = (undefined4 *)FUN_800707ac(unaff_s3 + 4);
      uVar2 = 0x1000000;
      if (puVar1 == (undefined4 *)0x0) {
        if ((unaff_s4 == 0) && (unaff_s2 == 0)) {
          iVar3 = FUN_80059340(*(undefined4 *)(*unaff_s1 + 0x38));
          uVar2 = *(uint *)(iVar3 + 0xcc) & 0x1000;
          if (uVar2 == 0) {
            uVar2 = FUN_80070800(unaff_s1 + 3,0x100000,0);
          }
        }
        return uVar2;
      }
      puVar4 = (undefined *)*puVar1;
    } while (puVar4 == (undefined *)0x1000001);
    if (0x1000001 < (int)puVar4) goto LAB_8009b93c;
  } while (puVar4 == &DAT_80000020);
  if ((int)puVar4 < -0x7fffffdf) {
    if (puVar4 == &DAT_80000004) goto LAB_8009b884;
    if (-0x7ffffffc < (int)puVar4) {
      if (puVar4 != &DAT_80000008) goto LAB_8009bb8c;
      goto LAB_8009b884;
    }
    if (puVar4 == (undefined *)0x80000000) goto LAB_8009b884;
  }
  else {
    if (puVar4 == &DAT_00100001) {
      if (unaff_s2 == 0) {
        Raziel.State.SectionList[1].Event.Queue[9].Data = 0x2000;
        Raziel.currentHint = 0;
        Raziel._1312_4_ = 0;
                    /* WARNING: Subroutine does not return */
        FUN_800a3070(*unaff_s1,0);
      }
      FUN_80071b48();
      goto LAB_8009b884;
    }
    if ((int)puVar4 < 0x100002) {
      if (puVar4 == (undefined *)0x100000) goto LAB_8009baac;
    }
    else {
      if (puVar4 == &DAT_00100004) {
        if (unaff_s2 == 0) {
          FUN_800a1d78(*unaff_s1);
          draw[0].dr_env.code[4]._0_2_ = 0xb;
          draw[0].dr_env.code[3]._0_2_ = 10;
          draw[0].dr_env.code[3]._2_2_ = 10;
          Raziel.Senses.Delta._0_4_ = unaff_s5;
        }
        goto LAB_8009b884;
      }
    }
  }
  goto LAB_8009bb8c;
LAB_8009b93c:
  if (puVar4 == (undefined *)0x4020000) goto LAB_8009b884;
  if ((int)puVar4 < 0x4020001) {
    if (puVar4 == (undefined *)0x4000007) goto LAB_8009b884;
    if ((int)puVar4 < 0x4000008) {
      if (puVar4 == (undefined *)0x4000001) goto LAB_8009b884;
    }
    else {
      if (puVar4 == (undefined *)0x4010008) {
        FUN_800725cc();
        goto LAB_8009b884;
      }
    }
  }
  else {
    if (puVar4 == (undefined *)0x10000000) goto LAB_8009b884;
    if ((int)puVar4 < 0x10000001) {
      if (puVar4 == (undefined *)0x8000000) {
        if (unaff_s6 == 0x10) {
          FUN_80071b8c();
          FUN_8009a684(0x800d56e4,*unaff_s1,4,0);
        }
        goto LAB_8009b884;
      }
    }
    else {
      if ((puVar4 == (undefined *)0x20000001) || (puVar4 == (undefined *)0x20000004))
      goto LAB_8009b884;
    }
  }
LAB_8009bb8c:
  FUN_800b0280();
  goto LAB_8009b884;
LAB_8009baac:
  FUN_8009a2c4(*unaff_s1,0xfffffff0,0,0);
  iVar3 = FUN_800a7384(*unaff_s1,0x18,0,0);
  if (iVar3 != 0) {
    FUN_80071eb8();
  }
  unaff_s4 = 1;
  goto code_r0x8009bb00;
}



// autogenerated function stub: 
// void /*$ra*/ StateHandlerAttack2(struct __CharacterState *In /*$s4*/, int CurrentSection /*$s5*/, int Data /*stack 8*/)
void StateHandlerAttack2(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 157, offset 0x8009be68
	/* begin block 1 */
		// Start line: 158
		// Start offset: 0x8009BE68
		// Variables:
			struct __Event *Ptr; // $s1
			int message; // stack offset -64
			int messageData; // stack offset -60
			int Frame; // stack offset -56
			int Anim; // stack offset -52
			int ignoreHit; // stack offset -48
			struct _Instance *ignoreInst; // stack offset -44

		/* begin block 1.1 */
			// Start line: 233
			// Start offset: 0x8009C214
			// Variables:
				struct _Instance *inst; // $s0
				unsigned long startColor; // $s3
				unsigned long endColor; // $s2
		/* end block 1.1 */
		// End offset: 0x8009C364
		// End Line: 279

		/* begin block 1.2 */
			// Start line: 332
			// Start offset: 0x8009C4BC
			// Variables:
				struct _Instance *weaponInst; // $s0
		/* end block 1.2 */
		// End offset: 0x8009C51C
		// End Line: 349

		/* begin block 1.3 */
			// Start line: 406
			// Start offset: 0x8009C750
			// Variables:
				struct _Instance *inst; // $s0
				unsigned long startColor; // $s2
				unsigned long endColor; // $s1
		/* end block 1.3 */
		// End offset: 0x8009C834
		// End Line: 438

		/* begin block 1.4 */
			// Start line: 486
			// Start offset: 0x8009C99C
			// Variables:
				struct _Instance *Inst; // $a0
		/* end block 1.4 */
		// End offset: 0x8009CA0C
		// End Line: 500

		/* begin block 1.5 */
			// Start line: 518
			// Start offset: 0x8009CA9C
		/* end block 1.5 */
		// End offset: 0x8009CA9C
		// End Line: 519

		/* begin block 1.6 */
			// Start line: 544
			// Start offset: 0x8009CB84
		/* end block 1.6 */
		// End offset: 0x8009CBCC
		// End Line: 551

		/* begin block 1.7 */
			// Start line: 574
			// Start offset: 0x8009CC60
			// Variables:
				struct evMonsterHitData *data; // $s0
		/* end block 1.7 */
		// End offset: 0x8009CD30
		// End Line: 588

		/* begin block 1.8 */
			// Start line: 608
			// Start offset: 0x8009CDE4
			// Variables:
				struct evMonsterHitData *hitData; // $s0
		/* end block 1.8 */
		// End offset: 0x8009CDFC
		// End Line: 614

		/* begin block 1.9 */
			// Start line: 634
			// Start offset: 0x8009CE74
			// Variables:
				struct _G2AnimSection_Type *animSection; // $v1
		/* end block 1.9 */
		// End offset: 0x8009CED8
		// End Line: 641
	/* end block 1 */
	// End offset: 0x8009CF08
	// End Line: 648

	/* begin block 2 */
		// Start line: 321
	/* end block 2 */
	// End Line: 322

}


// decompiled code
// original method signature: 
// void /*$ra*/ StateHandlerCannedReaction(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Data /*$s4*/)
 // line 651, offset 0x8009cf38
	/* begin block 1 */
		// Start line: 652
		// Start offset: 0x8009CF38
		// Variables:
	// 		struct __Event *Ptr; // $v0

		/* begin block 1.1 */
			// Start line: 694
			// Start offset: 0x8009D0F8
			// Variables:
		// 		struct _Instance *Inst; // $v0
		/* end block 1.1 */
		// End offset: 0x8009D114
		// End Line: 697

		/* begin block 1.2 */
			// Start line: 707
			// Start offset: 0x8009D11C
			// Variables:
		// 		struct _Instance *Inst; // $s0
		/* end block 1.2 */
		// End offset: 0x8009D18C
		// End Line: 724
	/* end block 1 */
	// End offset: 0x8009D1A8
	// End Line: 767

	/* begin block 2 */
		// Start line: 1341
	/* end block 2 */
	// End Line: 1342

void StateHandlerCannedReaction(__CharacterState *In,int CurrentSection,int Data)

{
  int unaff_s0;
  
                    /* WARNING: Subroutine does not return */
  FUN_80034368(*(undefined4 *)(unaff_s0 + 4),0x100001f);
}



// autogenerated function stub: 
// void /*$ra*/ StateHandlerStumble(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s3*/, int Data /*$s7*/)
void StateHandlerStumble(struct __CharacterState *In, int CurrentSection, int Data)
{ // line 770, offset 0x8009d1c8
	/* begin block 1 */
		// Start line: 771
		// Start offset: 0x8009D1C8
		// Variables:
			struct __Event *Ptr; // $s0

		/* begin block 1.1 */
			// Start line: 821
			// Start offset: 0x8009D500
			// Variables:
				struct evActionPlayHostAnimationData *data; // $v0
		/* end block 1.1 */
		// End offset: 0x8009D500
		// End Line: 823

		/* begin block 1.2 */
			// Start line: 831
			// Start offset: 0x8009D554
			// Variables:
				struct evMonsterHitData *data; // $v0
		/* end block 1.2 */
		// End offset: 0x8009D554
		// End Line: 832
	/* end block 1 */
	// End offset: 0x8009D5C0
	// End Line: 871

	/* begin block 2 */
		// Start line: 1609
	/* end block 2 */
	// End Line: 1610

}


// decompiled code
// original method signature: 
// void /*$ra*/ StateHandlerHitReaction(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Data /*$s4*/)
 // line 892, offset 0x8009d5ec
	/* begin block 1 */
		// Start line: 893
		// Start offset: 0x8009D5EC
		// Variables:
	// 		struct __Event *Ptr; // $v0

		/* begin block 1.1 */
			// Start line: 902
			// Start offset: 0x8009D6D0
			// Variables:
		// 		struct evMonsterHitData *data; // $s0

			/* begin block 1.1.1 */
				// Start line: 906
				// Start offset: 0x8009D6DC
				// Variables:
			// 		struct _Instance *weapon; // $v0
			/* end block 1.1.1 */
			// End offset: 0x8009D768
			// End Line: 927
		/* end block 1.1 */
		// End offset: 0x8009D7B0
		// End Line: 934
	/* end block 1 */
	// End offset: 0x8009D848
	// End Line: 969

	/* begin block 2 */
		// Start line: 1784
	/* end block 2 */
	// End Line: 1785

void StateHandlerHitReaction(__CharacterState *In,int CurrentSection,int Data)

{
  undefined4 *puVar1;
  int iVar2;
  undefined *puVar3;
  int *unaff_s1;
  int unaff_s2;
  int unaff_s3;
  int unaff_s4;
  int unaff_s5;
  
code_r0x8009d5ec:
  In->SectionList[0].Data2 = 0;
  In->SectionList[0].Data1 = In->SectionList[0].Data1 + -0x200;
LAB_8009d334:
  while( true ) {
    PurgeMessageQueue((__MessageQueue *)(unaff_s4 + 4));
    puVar1 = (undefined4 *)FUN_800707ac(unaff_s4 + 4);
    if (puVar1 == (undefined4 *)0x0) {
      return;
    }
    puVar3 = (undefined *)*puVar1;
    if (puVar3 != &DAT_00100001) break;
    if (unaff_s3 == 0) {
      Raziel.currentHint = 8;
      FUN_8009a2c4(*unaff_s1,0xfffffff0,0,0);
      Raziel._1312_4_ = 0;
                    /* WARNING: Subroutine does not return */
      FUN_800a3070(*unaff_s1,0);
    }
    FUN_8008fdd0(*unaff_s1 + 0x194,0x800);
    FUN_80071b48();
  }
  if ((int)puVar3 < 0x100002) {
    if (puVar3 == (undefined *)0x0) {
      *(undefined4 *)((int)unaff_s1 + unaff_s2 + 0x120) = 1;
      goto LAB_8009d334;
    }
    if ((int)puVar3 < 1) {
      if (puVar3 == &DAT_80000008) goto LAB_8009d334;
      if (-0x7ffffff8 < (int)puVar3) {
        if (puVar3 != &DAT_80000020) goto LAB_8009d6bc;
        goto LAB_8009d334;
      }
      if (puVar3 == (undefined *)0x80000000) goto LAB_8009d334;
    }
    else {
      if (puVar3 == &DAT_00040005) goto LAB_8009d334;
      if ((int)puVar3 < 0x40006) {
        if (puVar3 == &DAT_00040003) {
          if (unaff_s3 == 0) {
            puVar1 = (undefined4 *)puVar1[1];
            FUN_80071dcc(*puVar1,puVar1[1],puVar1[2],puVar1[3]);
          }
          goto LAB_8009d334;
        }
      }
      else {
        if (puVar3 == (undefined *)0x100000) {
          if (((*(uint *)Raziel.padCommands.Queue[5].Data & LONG_800cf574) != 0) &&
             ((*(uint *)Raziel.padCommands.Queue[5].Data & LONG_800cf570) != 0)) {
            Raziel.State.SectionList[2].Defer.Queue[10].ID = unaff_s5;
                    /* WARNING: Subroutine does not return */
            FUN_80071404(0,0,0xc);
          }
                    /* WARNING: Subroutine does not return */
          FUN_80071404(0,0,0xc);
        }
      }
    }
  }
  else {
    if (puVar3 == (undefined *)0x1000000) {
      if ((draw[0].dr_env.code[1] & 0x800) != 0) {
        FUN_800a4848(*(undefined4 *)(puVar1[1] + 0xc));
      }
      goto LAB_8009d334;
    }
    if (0x1000000 < (int)puVar3) {
      if (puVar3 == (undefined *)0x2000000) goto LAB_8009d334;
      if ((int)puVar3 < 0x2000001) {
        if (puVar3 != (undefined *)0x1000001) goto LAB_8009d6bc;
        goto LAB_8009d334;
      }
      if (puVar3 == (undefined *)0x4000001) goto LAB_8009d334;
      if (puVar3 != (undefined *)0x10000000) goto LAB_8009d6bc;
      In = (__CharacterState *)((int)unaff_s1 + unaff_s2);
      if (In->SectionList[0].Data2 == 1) goto code_r0x8009d5ec;
      goto LAB_8009d334;
    }
    if (puVar3 == &DAT_00100009) goto LAB_8009d334;
    if ((int)puVar3 < 0x10000a) {
      if (puVar3 == &DAT_00100004) {
        FUN_8008fdd0(*unaff_s1 + 0x194,0x1000);
        goto LAB_8009d334;
      }
    }
    else {
      if (puVar3 == &DAT_00100015) {
        iVar2 = FUN_800595a8();
        puVar3 = (undefined *)0x100000;
        if (iVar2 != 0) {
          puVar3 = &DAT_00100015;
        }
        FUN_80070800(unaff_s2 + -0x7ff2af34,puVar3,0);
        goto LAB_8009d334;
      }
    }
  }
LAB_8009d6bc:
  FUN_800b0280();
  goto LAB_8009d334;
}



// decompiled code
// original method signature: 
// void /*$ra*/ StateHandlerThrow2(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s2*/, int Data /*$s7*/)
 // line 1049, offset 0x8009d868
	/* begin block 1 */
		// Start line: 1050
		// Start offset: 0x8009D868
		// Variables:
	// 		struct __Event *Ptr; // $a1
	// 		int Anim; // $s4

		/* begin block 1.1 */
			// Start line: 1193
			// Start offset: 0x8009DE6C
			// Variables:
		// 		struct evMonsterHitData *data; // $v1
		/* end block 1.1 */
		// End offset: 0x8009DE80
		// End Line: 1196

		/* begin block 1.2 */
			// Start line: 1271
			// Start offset: 0x8009E07C
			// Variables:
		// 		struct _Instance *weaponInst; // $s0

			/* begin block 1.2.1 */
				// Start line: 1275
				// Start offset: 0x8009E090
				// Variables:
			// 		int spin_type; // $a3

				/* begin block 1.2.1.1 */
					// Start line: 1289
					// Start offset: 0x8009E0E8
					// Variables:
				// 		struct _Position To; // stack offset -64
				// 		struct _Rotation Rot; // stack offset -56
				// 		struct MATRIX *matrix; // $v0
				/* end block 1.2.1.1 */
				// End offset: 0x8009E0E8
				// End Line: 1294
			/* end block 1.2.1 */
			// End offset: 0x8009E1B4
			// End Line: 1310
		/* end block 1.2 */
		// End offset: 0x8009E1E0
		// End Line: 1314

		/* begin block 1.3 */
			// Start line: 1361
			// Start offset: 0x8009E320
			// Variables:
		// 		struct _Position To; // stack offset -64
		// 		struct _Rotation Rot; // stack offset -48
		// 		struct MATRIX *matrix; // $v0
		/* end block 1.3 */
		// End offset: 0x8009E364
		// End Line: 1371
	/* end block 1 */
	// End offset: 0x8009E364
	// End Line: 1394

	/* begin block 2 */
		// Start line: 2098
	/* end block 2 */
	// End Line: 2099

void StateHandlerThrow2(__CharacterState *In,int CurrentSection,int Data)

{
  undefined4 *unaff_s1;
  
  FUN_8009a338(In,0xfffffff0);
                    /* WARNING: Subroutine does not return */
  FUN_800a3070(*unaff_s1,10);
}



// decompiled code
// original method signature: 
// void /*$ra*/ PointAt(struct _Instance *instance /*$s0*/, struct _Position *Target /*$s1*/, struct _Rotation *Rot1 /*$s2*/)
 // line 1395, offset 0x8009e390
	/* begin block 1 */
		// Start line: 1396
		// Start offset: 0x8009E390
		// Variables:
	// 		struct _Position From; // stack offset -48
	// 		struct SVECTOR v1; // stack offset -40
	// 		struct VECTOR v3; // stack offset -32
	// 		struct MATRIX *tempMat; // $a0
	/* end block 1 */
	// End offset: 0x8009E47C
	// End Line: 1428

	/* begin block 2 */
		// Start line: 2822
	/* end block 2 */
	// End Line: 2823

	/* begin block 3 */
		// Start line: 2830
	/* end block 3 */
	// End Line: 2831

void PointAt(_Instance *instance,_Position *Target,_Rotation *Rot1)

{
  undefined4 uVar1;
  int iVar2;
  undefined *puVar3;
  undefined4 uVar4;
  uint uVar5;
  int *unaff_s1;
  int unaff_s2;
  int unaff_s3;
  uint unaff_s4;
  int unaff_s5;
  undefined4 uStack0000001c;
  
code_r0x8009e390:
  if (unaff_s2 == 1) {
    if (*(int *)&Target->z == 1) {
      if ((Raziel.State.SectionList[1].Defer.Queue[10].ID != 0x1000) &&
         (Raziel.State.SectionList[1].Defer.Queue[10].ID != 8)) {
        FUN_800a58a4((int)*(short *)(*unaff_s1 + 0xec),
                     (int)*(short *)(Raziel.Senses.EngagedMask + 0x24),
                     (int)*(short *)(Raziel.Senses.EngagedMask + 0x26));
      }
      Raziel.State.SectionList[2].Event.Queue[7].ID = 2;
      Raziel.State.SectionList[2].Defer.Queue[10].ID = (int)FUN_800a87bc;
    }
    else {
      FUN_800a58a4((int)*(short *)(*unaff_s1 + 0xec),0,
                   -(int)*(short *)(Raziel.Senses.EngagedMask + 0x26));
      FUN_8009060c(*unaff_s1 + 0x194,0xe,0xe,600);
      Raziel.State.SectionList[2].Event.Queue[7].ID = 0;
    }
  }
LAB_8009d9dc:
  while( true ) {
    PurgeMessageQueue((__MessageQueue *)(unaff_s5 + 4));
    Target = (_Position *)FUN_800707ac();
    if (Target == (_Position *)0x0) {
      if ((unaff_s2 == 1) && ((Raziel.State.SectionList[1].Defer.Queue[8].ID & 0x80U) != 0)) {
                    /* WARNING: Subroutine does not return */
        FUN_8003432c(*(undefined4 *)(Raziel.State.SectionList[1].Defer.Queue[7].Data + 0x38),0xc);
      }
      return;
    }
    puVar3 = *(undefined **)Target;
    if (puVar3 != (undefined *)0x1000000) break;
    if (unaff_s2 == 0) {
      if ((Raziel.State.SectionList[1].Event.Queue[9].Data & 0x40000U) == 0) {
        if (((Raziel.currentHint & 0x4000U) == 0) &&
           (Raziel.State.SectionList[1].Defer.Queue[13].ID == 0)) {
          FUN_80072554();
          FUN_800a58a4((int)*(short *)(*unaff_s1 + 0xec),0,
                       -*(int *)(Raziel.Senses.EngagedMask + 0x28));
          FUN_8001b848(&standardMenu);
        }
      }
      else {
        if ((draw[0].dr_env.code[1] & 0x800) != 0) {
          FUN_800a4848(*(undefined4 *)(*(int *)&Target->z + 0xc));
        }
      }
    }
  }
  if ((int)puVar3 < 0x1000001) {
    if (puVar3 == (undefined *)0x100000) {
      if ((Raziel.State.SectionList[1].Event.Queue[9].Data & 0x40000U) == 0) {
                    /* WARNING: Subroutine does not return */
        FUN_80071404(0,0,(uint)*(byte *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 9));
      }
LAB_8009e380:
      FUN_800725cc();
      goto LAB_8009d9dc;
    }
    if ((int)puVar3 < 0x100001) {
      if (puVar3 == &DAT_80000008) {
        if (Raziel.State.SectionList[2].Event.Queue[8].Data != 0) {
          FUN_80070800();
          FUN_800a58a4((int)*(short *)(*unaff_s1 + 0xec),0,
                       -(int)*(short *)(Raziel.Senses.EngagedMask + 0x26));
        }
        goto LAB_8009d9dc;
      }
      if ((int)puVar3 < -0x7ffffff7) {
        if (puVar3 == (undefined *)0x80000000) goto LAB_8009d9dc;
      }
      else {
        if (puVar3 == &DAT_80000020) goto LAB_8009d9dc;
      }
    }
    else {
      if (puVar3 == &DAT_00100004) {
        FUN_8009060c(*unaff_s1 + 0x194,0xe,0xe,300);
        if ((Raziel.State.SectionList[2].Defer.Queue[12].Data & 2U) != 0) {
          FUN_800a58a4((int)*(short *)(*unaff_s1 + 0xec),0,
                       -*(int *)(Raziel.Senses.EngagedMask + 0x28));
        }
        if ((unaff_s2 == 0) && (Raziel.steeringMode != 0)) {
                    /* WARNING: Subroutine does not return */
          FUN_800401fc();
        }
        if (Raziel.State.SectionList[1].Defer.Queue[10].ID == 8) {
          uVar1 = FUN_800a5f34();
          FUN_800341c8(uVar1);
        }
        if (Raziel.State.SectionList[1].Defer.Queue[10].ID == 0x1000) {
          uVar1 = 0x800105;
          iVar2 = Raziel.State.SectionList[2].Event.Queue[0].ID;
          goto LAB_8009e0dc;
        }
        goto LAB_8009d9dc;
      }
      if ((int)puVar3 < 0x100005) {
        if (puVar3 == &DAT_00100001) {
          if (unaff_s2 == 0) {
            Raziel.currentHint = (int)&DAT_00041001;
            if ((Raziel.State.SectionList[1].Event.Queue[9].Data & 0x40000U) != 0) {
                    /* WARNING: Subroutine does not return */
              FUN_800a3070(*unaff_s1,0xb);
            }
                    /* WARNING: Subroutine does not return */
            FUN_800a3070(*unaff_s1,0);
          }
          if (unaff_s2 == 2) {
LAB_8009de10:
            FUN_80071b48();
          }
          else {
            if (((Raziel.State.SectionList[1].Event.Queue[9].Data & 0x40000U) == 0) ||
               (unaff_s2 != 0)) {
              FUN_80071b8c();
            }
            else {
              if (unaff_s4 != 0x3f) goto LAB_8009de10;
            }
          }
          *(undefined4 *)(unaff_s3 + 0x120) = 1;
          goto LAB_8009d9dc;
        }
      }
      else {
        if (puVar3 == &DAT_00100009) goto code_r0x8009e390;
      }
    }
  }
  else {
    if (puVar3 == (undefined *)0x8000000) {
      Raziel.State.SectionList[2].Event.Queue[7].ID =
           Raziel.State.SectionList[2].Event.Queue[7].ID & 0xfffffffb;
      if (unaff_s4 == (uint)*(byte *)Raziel.State.SectionList[2].Event.Queue[6].Data) {
        if (((Raziel.State.SectionList[1].Event.Queue[9].Data & 0x40000U) == 0) || (unaff_s2 != 0))
        {
          FUN_80071b8c();
        }
      }
      else {
        if ((unaff_s4 == (uint)*(byte *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 6)) &&
           (uVar1 = 0x100000, unaff_s2 == 1)) {
          iVar2 = *unaff_s1;
LAB_8009e0dc:
                    /* WARNING: Subroutine does not return */
          FUN_80034368(iVar2,uVar1,0);
        }
      }
      goto LAB_8009d9dc;
    }
    if ((int)puVar3 < 0x8000001) {
      if (puVar3 == (undefined *)0x4000001) {
        if (unaff_s2 == 0) {
          FUN_8009a5cc(*unaff_s1,0x800d5034);
        }
        FUN_80071b48();
        goto LAB_8009e380;
      }
      if (0x4000001 < (int)puVar3) {
        if (puVar3 != (undefined *)0x4020000) goto LAB_8009e43c;
        goto LAB_8009d9dc;
      }
      if (puVar3 == (undefined *)0x1000001) goto LAB_8009d9dc;
    }
    else {
      if (puVar3 == (undefined *)0x20000002) goto LAB_8009d9dc;
      if ((int)puVar3 < 0x20000003) {
        if (puVar3 == (undefined *)0x8000004) {
          iVar2 = FUN_800a5f6c();
          if (iVar2 != 0) {
            uVar5 = (uint)(*(short *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x1e) != 0);
            if ((Raziel.State.SectionList[2].Event.Queue[7].ID & 2U) == 0) {
              if ((Raziel.State.SectionList[1].Defer.Queue[8].ID & 0x80U) != 0) {
                uStack0000001c = 0;
                uVar1 = FUN_800711c0(*(undefined4 *)
                                      (Raziel.State.SectionList[1].Defer.Queue[7].Data + 0x38),0,1,
                                     uVar5);
                    /* WARNING: Subroutine does not return */
                FUN_80034368(iVar2,0x800010,uVar1);
              }
              uVar1 = 0;
              uVar4 = 0;
            }
            else {
              uVar1 = 0x800d54a0;
              uVar4 = 4;
            }
            uStack0000001c = 0;
            uVar1 = FUN_800711c0(uVar1,0,uVar4,uVar5);
                    /* WARNING: Subroutine does not return */
            FUN_80034368(iVar2,0x800010,uVar1);
          }
          goto LAB_8009d9dc;
        }
      }
      else {
        if (puVar3 == (undefined *)0x20000020) {
          if (*(int *)(unaff_s3 + 0x120) != 0) {
            if (unaff_s4 == (uint)*(byte *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 3)) {
              if (((Raziel.State.SectionList[1].Event.Queue[9].Data & 0x40000U) == 0) ||
                 (unaff_s2 != 0)) {
                FUN_80071b48();
              }
              if (unaff_s2 == 1) {
                Raziel.ZDirection._0_2_ =
                     (ushort)*(byte *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 8) * 100;
                *(undefined4 *)(*unaff_s1 + 500) = 0x800d5594;
              }
              *(undefined4 *)(unaff_s3 + 0x120) = 0;
              if (((uint)Raziel.Senses.LastAutoFace & 0x200) != 0) {
                FUN_800a7de8(0x200);
              }
            }
            else {
              FUN_80070800(unaff_s5 + 0x8c,0x20000020,0);
            }
          }
          goto LAB_8009d9dc;
        }
      }
    }
  }
LAB_8009e43c:
  FUN_800b0280();
  goto LAB_8009d9dc;
}



// decompiled code
// original method signature: 
// void /*$ra*/ ThrowSetFocusPoint(struct _Instance *instance /*$s4*/, struct _Rotation *rot /*$s2*/)
 // line 1433, offset 0x8009e4b0
	/* begin block 1 */
		// Start line: 1434
		// Start offset: 0x8009E4B0
		// Variables:
	// 		struct MATRIX *pTempMat; // $s0
	// 		struct _Instance *weaponInstance; // $s1
	// 		struct SVECTOR v1; // stack offset -48
	// 		struct VECTOR v4; // stack offset -40
	/* end block 1 */
	// End offset: 0x8009E5D0
	// End Line: 1480

	/* begin block 2 */
		// Start line: 2933
	/* end block 2 */
	// End Line: 2934

void ThrowSetFocusPoint(_Instance *instance,_Rotation *rot)

{
  FUN_8009e4e4(instance,rot,&stack0x00000038);
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ LimitRotation(struct _Rotation *rot /*$a1*/)
 // line 1481, offset 0x8009e5f0
	/* begin block 1 */
		// Start line: 3047
	/* end block 1 */
	// End Line: 3048

void LimitRotation(_Rotation *rot)

{
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ StateHandlerGrab(struct __CharacterState *In /*$s1*/, int CurrentSection /*$s3*/, int Data /*$s7*/)
 // line 1541, offset 0x8009e764
	/* begin block 1 */
		// Start line: 1542
		// Start offset: 0x8009E764
		// Variables:
	// 		struct __Event *Ptr; // $s2
	// 		int Anim; // $s4

		/* begin block 1.1 */
			// Start line: 1575
			// Start offset: 0x8009E9B0
			// Variables:
		// 		struct _Instance *Inst; // $a1
		/* end block 1.1 */
		// End offset: 0x8009EA00
		// End Line: 1586

		/* begin block 1.2 */
			// Start line: 1612
			// Start offset: 0x8009EA70
			// Variables:
		// 		struct _Instance *Inst; // $s0
		/* end block 1.2 */
		// End offset: 0x8009EA8C
		// End Line: 1631

		/* begin block 1.3 */
			// Start line: 1718
			// Start offset: 0x8009EC64
			// Variables:
		// 		struct _Instance *Inst; // $s0
		/* end block 1.3 */
		// End offset: 0x8009ED24
		// End Line: 1751

		/* begin block 1.4 */
			// Start line: 1758
			// Start offset: 0x8009ED3C
			// Variables:
		// 		struct _Instance *Inst; // $s0
		/* end block 1.4 */
		// End offset: 0x8009ED9C
		// End Line: 1771

		/* begin block 1.5 */
			// Start line: 1778
			// Start offset: 0x8009EDFC
			// Variables:
		// 		struct _Instance *Inst; // $s0
		/* end block 1.5 */
		// End offset: 0x8009EE5C
		// End Line: 1793
	/* end block 1 */
	// End offset: 0x8009EED0
	// End Line: 1825

	/* begin block 2 */
		// Start line: 3171
	/* end block 2 */
	// End Line: 3172

void StateHandlerGrab(__CharacterState *In,int CurrentSection,int Data)

{
  bool bVar1;
  undefined2 in_v0;
  short sVar2;
  short sVar3;
  int iVar4;
  int iVar5;
  undefined2 uVar6;
  int in_v1;
  
  *(undefined2 *)CurrentSection = in_v0;
  if (0x1000 < in_v1) {
    iVar4 = in_v1 + -0x1000;
    do {
      sVar2 = (short)iVar4;
      *(short *)(CurrentSection + 4) = sVar2;
      iVar4 = iVar4 + -0x1000;
    } while (0x1000 < sVar2);
  }
  sVar2 = *(short *)(CurrentSection + 4);
  sVar3 = *(short *)(CurrentSection + 4) + 0x1000;
  if (sVar2 < 1) {
    *(short *)(CurrentSection + 4) = sVar3;
    bVar1 = sVar3 < *(short *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x16);
    uVar6 = *(undefined2 *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x16);
  }
  else {
    if (sVar2 < 0x800) {
      uVar6 = *(undefined2 *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x14);
      bVar1 = *(short *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x14) < sVar2;
    }
    else {
      uVar6 = *(undefined2 *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x16);
      bVar1 = sVar2 < *(short *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x16);
    }
  }
  if (bVar1) {
    *(undefined2 *)(CurrentSection + 4) = uVar6;
  }
  iVar4 = (int)*(short *)CurrentSection;
  iVar5 = iVar4;
  while (0x1000 < iVar5) {
    iVar4 = iVar4 + -0x1000;
    *(short *)CurrentSection = (short)iVar4;
    iVar5 = iVar4 * 0x10000 >> 0x10;
  }
  sVar2 = *(short *)CurrentSection;
  sVar3 = *(short *)CurrentSection;
  if (sVar2 < 1) {
    *(short *)CurrentSection = sVar3 + 0x1000;
    bVar1 = (short)(sVar3 + 0x1000) <
            *(short *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x12);
    uVar6 = *(undefined2 *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x12);
  }
  else {
    if (sVar2 < 0x800) {
      uVar6 = *(undefined2 *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x10);
      bVar1 = *(short *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x10) < sVar2;
    }
    else {
      uVar6 = *(undefined2 *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x12);
      bVar1 = sVar2 < *(short *)(Raziel.State.SectionList[2].Event.Queue[6].Data + 0x12);
    }
  }
  if (bVar1) {
    *(undefined2 *)CurrentSection = uVar6;
  }
  return;
}





