#include "THISDUST.H"
#include "INSTNCG2.H"


// autogenerated function stub: 
// void /*$ra*/ G2Instance_BuildTransformsForList(struct _Instance *listHead /*$s1*/)
void G2Instance_BuildTransformsForList(struct _Instance *listHead)
{ // line 71, offset 0x80094d90
	/* begin block 1 */
		// Start line: 72
		// Start offset: 0x80094D90
		// Variables:
			struct _Instance *instance; // $s0
	/* end block 1 */
	// End offset: 0x80094EF8
	// End Line: 151

	/* begin block 2 */
		// Start line: 142
	/* end block 2 */
	// End Line: 143

}


// decompiled code
// original method signature: 
// void /*$ra*/ G2Instance_BuildTransforms(struct _Instance *instance /*$a0*/)
 // line 155, offset 0x80094f0c
	/* begin block 1 */
		// Start line: 333
	/* end block 1 */
	// End Line: 334

void G2Instance_BuildTransforms(_Instance *instance)

{
  int iVar1;
  _Instance *instance_00;
  int unaff_s1;
  
code_r0x80094f0c:
  if (instance_00->matrix == (MATRIX *)0x0) goto LAB_80094f6c;
  if (((instance_00->object->animList != (_G2AnimKeylist_Type **)0x0) &&
      ((instance_00->object->oflags2 & 0x40000000U) == 0)) && (((instance_00->anim).flags & 1) != 0)
     ) goto LAB_80094f6c;
  do {
    FUN_8009588c(instance_00);
    while( true ) {
      do {
        instance_00 = instance_00->next;
        if (instance_00 == (_Instance *)0x0) {
          if (unaff_s1 != 0) {
            do {
              if ((*(code **)(unaff_s1 + 0x248) != (code *)0x0) &&
                 (iVar1 = (**(code **)(unaff_s1 + 0x248))(unaff_s1), iVar1 != 0)) {
                FUN_80092e74(unaff_s1 + 0x194);
                FUN_80095040(unaff_s1);
              }
              unaff_s1 = *(int *)(unaff_s1 + 8);
            } while (unaff_s1 != 0);
          }
          return;
        }
      } while (instance_00->LinkParent != (_Instance *)0x0);
      if ((instance_00->flags2 & 1U) != 0) break;
      if ((((instance_00->flags & 0x100000U) != 0) &&
          (*(int *)&instance_00->oldPos == *(int *)&instance_00->position)) &&
         (((instance_00->oldPos).z == (instance_00->position).z &&
          ((*(int *)&instance_00->oldRotation == *(int *)&instance_00->rotation &&
           ((instance_00->oldRotation).z == (instance_00->rotation).z)))))) goto code_r0x80094f0c;
LAB_80094f6c:
      _G2Instance_RebuildAnimatedTransforms(instance_00);
    }
  } while( true );
}



// decompiled code
// original method signature: 
// void /*$ra*/ G2Instance_RebuildTransforms(struct _Instance *instance /*$a0*/)
 // line 169, offset 0x80094f68
	/* begin block 1 */
		// Start line: 361
	/* end block 1 */
	// End Line: 362

void G2Instance_RebuildTransforms(_Instance *instance)

{
  int iVar1;
  _Instance *instance_00;
  int unaff_s1;
  
  do {
    _G2Instance_RebuildAnimatedTransforms(instance_00);
    while( true ) {
      do {
        instance_00 = instance_00->next;
        if (instance_00 == (_Instance *)0x0) {
          if (unaff_s1 != 0) {
            do {
              if ((*(code **)(unaff_s1 + 0x248) != (code *)0x0) &&
                 (iVar1 = (**(code **)(unaff_s1 + 0x248))(unaff_s1), iVar1 != 0)) {
                FUN_80092e74(unaff_s1 + 0x194);
                FUN_80095040(unaff_s1);
              }
              unaff_s1 = *(int *)(unaff_s1 + 8);
            } while (unaff_s1 != 0);
          }
          return;
        }
      } while (instance_00->LinkParent != (_Instance *)0x0);
      if (((instance_00->flags2 & 1U) == 0) &&
         ((((((instance_00->flags & 0x100000U) == 0 ||
             (*(int *)&instance_00->oldPos != *(int *)&instance_00->position)) ||
            ((instance_00->oldPos).z != (instance_00->position).z)) ||
           ((*(int *)&instance_00->oldRotation != *(int *)&instance_00->rotation ||
            ((instance_00->oldRotation).z != (instance_00->rotation).z)))) ||
          ((instance_00->matrix == (MATRIX *)0x0 ||
           (((instance_00->object->animList != (_G2AnimKeylist_Type **)0x0 &&
             ((instance_00->object->oflags2 & 0x40000000U) == 0)) &&
            (((instance_00->anim).flags & 1) != 0)))))))) break;
      FUN_8009588c(instance_00);
    }
  } while( true );
}



// decompiled code
// original method signature: 
// struct _G2AnimKeylist_Type * /*$ra*/ G2Instance_GetKeylist(struct _Instance *instance /*$a0*/, int id /*$a1*/)
 // line 184, offset 0x80094fc4
	/* begin block 1 */
		// Start line: 391
	/* end block 1 */
	// End Line: 392

	/* begin block 2 */
		// Start line: 392
	/* end block 2 */
	// End Line: 393

_G2AnimKeylist_Type * G2Instance_GetKeylist(_Instance *instance,int id)

{
  _G2AnimKeylist_Type *in_v0;
  int unaff_s0;
  
  while (unaff_s0 != 0) {
    in_v0 = *(_G2AnimKeylist_Type **)(unaff_s0 + 0x248);
    if ((in_v0 != (_G2AnimKeylist_Type *)0x0) &&
       (in_v0 = (_G2AnimKeylist_Type *)(*(code *)in_v0)(unaff_s0),
       in_v0 != (_G2AnimKeylist_Type *)0x0)) {
      FUN_80092e74(unaff_s0 + 0x194);
      in_v0 = (_G2AnimKeylist_Type *)FUN_80095040(unaff_s0);
    }
    unaff_s0 = *(int *)(unaff_s0 + 8);
  }
  return in_v0;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _G2Instance_RebuildAnimatedTransforms(struct _Instance *instance /*$s3*/)
 // line 196, offset 0x80094fe4
	/* begin block 1 */
		// Start line: 197
		// Start offset: 0x80094FE4
		// Variables:
	// 		struct _Model *model; // $s7
	// 		struct _G2Matrix_Type *rootMatrix; // $s4
	// 		struct _Rotation pre_facade_rot; // stack offset -120
	// 		struct _G2Matrix_Type *segMatrix; // $a2
	// 		struct _G2Matrix_Type seg1RotMatrix; // stack offset -112
	// 		struct _G2Matrix_Type seg2RotMatrix; // stack offset -80
	// 		struct _G2SVector3_Type rotVector; // stack offset -48
	// 		long otx; // $s6
	// 		long oty; // $s5
	// 		long otz; // $s2
	// 		long segIndex; // $s1

		/* begin block 1.1 */
			// Start line: 220
			// Start offset: 0x80095048
		/* end block 1.1 */
		// End offset: 0x80095094
		// End Line: 229

		/* begin block 1.2 */
			// Start line: 283
			// Start offset: 0x80095244
			// Variables:
		// 		struct VECTOR *ins_scale; // $v1
		/* end block 1.2 */
		// End offset: 0x80095278
		// End Line: 291
	/* end block 1 */
	// End offset: 0x800953EC
	// End Line: 346

	/* begin block 2 */
		// Start line: 415
	/* end block 2 */
	// End Line: 416

void _G2Instance_RebuildAnimatedTransforms(_Instance *instance)

{
  if ((instance->object->animList == (_G2AnimKeylist_Type **)0x0) ||
     ((instance->object->oflags2 & 0x40000000U) != 0)) {
    FUN_80095a0c();
  }
  else {
    FUN_80095544();
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ G2Instance_ClearMatrices(struct _Instance *instance /*$s0*/)
 // line 348, offset 0x80095418
	/* begin block 1 */
		// Start line: 756
	/* end block 1 */
	// End Line: 757

void G2Instance_ClearMatrices(_Instance *instance)

{
  int in_v0;
  int iVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  int *unaff_s0;
  int *piVar4;
  int unaff_s1;
  int unaff_s2;
  int unaff_s3;
  _Instance *instance_00;
  int unaff_s4;
  int unaff_s5;
  int unaff_s6;
  int unaff_s7;
  undefined4 in_stack_00000010;
  undefined4 in_stack_00000014;
  
  while ((piVar4 = unaff_s0 + 8, unaff_s1 < in_v0 &&
         (iVar1 = FUN_8009072c(unaff_s3 + 0x194,unaff_s1,0x20), iVar1 == 0))) {
    unaff_s1 = unaff_s1 + 1;
    unaff_s0[6] = unaff_s0[6] + unaff_s6;
    *piVar4 = *piVar4 + unaff_s2;
    unaff_s0[7] = unaff_s0[7] + unaff_s5;
    in_v0 = *(int *)(unaff_s7 + 0x18);
    unaff_s0 = piVar4;
  }
  iVar1 = *(int *)(unaff_s3 + 0x40);
  uVar2 = *(undefined4 *)(iVar1 + 0x18);
  uVar3 = *(undefined4 *)(iVar1 + 0x1c);
  *(undefined4 *)(unaff_s4 + 0x14) = *(undefined4 *)(iVar1 + 0x14);
  *(undefined4 *)(unaff_s4 + 0x18) = uVar2;
  *(undefined4 *)(unaff_s4 + 0x1c) = uVar3;
  *(undefined2 *)(unaff_s3 + 0x5c) = *(undefined2 *)(unaff_s4 + 0x14);
  *(undefined2 *)(unaff_s3 + 0x5e) = *(undefined2 *)(unaff_s4 + 0x18);
  *(undefined2 *)(unaff_s3 + 0x60) = *(undefined2 *)(unaff_s4 + 0x1c);
  if ((**(uint **)(unaff_s3 + 0x1c) & 4) != 0) {
    *(undefined4 *)(unaff_s3 + 0x74) = in_stack_00000010;
    *(undefined4 *)(unaff_s3 + 0x78) = in_stack_00000014;
  }
  instance_00 = *(_Instance **)(unaff_s3 + 0x130);
  while (instance_00 != (_Instance *)0x0) {
    _G2Instance_RebuildAnimatedTransforms(instance_00);
    instance_00 = instance_00->LinkSibling;
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _G2Instance_BuildAnimatedTransforms(struct _Instance *instance /*$s0*/)
 // line 359, offset 0x8009546c
	/* begin block 1 */
		// Start line: 360
		// Start offset: 0x8009546C
		// Variables:
	// 		struct MATRIX *rootMatrix; // $v0
	// 		struct _Model *model; // $v0
	/* end block 1 */
	// End offset: 0x80095518
	// End Line: 388

	/* begin block 2 */
		// Start line: 774
	/* end block 2 */
	// End Line: 775

	/* begin block 3 */
		// Start line: 780
	/* end block 3 */
	// End Line: 781

void _G2Instance_BuildAnimatedTransforms(_Instance *instance)

{
  uint in_v0;
  int unaff_s3;
  _Instance *instance_00;
  undefined4 in_stack_00000010;
  undefined4 in_stack_00000014;
  
  if ((in_v0 & 4) != 0) {
    *(undefined4 *)(unaff_s3 + 0x74) = in_stack_00000010;
    *(undefined4 *)(unaff_s3 + 0x78) = in_stack_00000014;
  }
  instance_00 = *(_Instance **)(unaff_s3 + 0x130);
  while (instance_00 != (_Instance *)0x0) {
    _G2Instance_RebuildAnimatedTransforms(instance_00);
    instance_00 = instance_00->LinkSibling;
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _G2Instance_RebuildNonAnimatedTransforms(struct _Instance *instance /*$s0*/)
 // line 392, offset 0x80095528
	/* begin block 1 */
		// Start line: 393
		// Start offset: 0x80095528
		// Variables:
	// 		struct VECTOR *scale; // $s5
	// 		struct MATRIX *introTransform; // $s7
	// 		struct MATRIX *segMatrix; // $s1
	// 		struct _Model *model; // $fp
	// 		struct _Segment *segment; // $s3
	// 		short scale_flag; // stack offset -48
	// 		long i; // $s4
	/* end block 1 */
	// End offset: 0x80095784
	// End Line: 511

	/* begin block 2 */
		// Start line: 847
	/* end block 2 */
	// End Line: 848

void _G2Instance_RebuildNonAnimatedTransforms(_Instance *instance)

{
  int unaff_s0;
  
  while (unaff_s0 != 0) {
    FUN_800954f0(unaff_s0);
    unaff_s0 = *(int *)(unaff_s0 + 0x134);
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _G2Instance_BuildDeactivatedTransforms(struct _Instance *instance /*$s0*/)
 // line 515, offset 0x800957b4
	/* begin block 1 */
		// Start line: 516
		// Start offset: 0x800957B4
		// Variables:
	// 		struct MATRIX *segMatrix; // $a0
	// 		struct MATRIX *startOldMatrix; // $a1
	// 		int numMatrices; // $s1
	// 		struct _Model *model; // $a0
	/* end block 1 */
	// End offset: 0x80095920
	// End Line: 578

	/* begin block 2 */
		// Start line: 1276
	/* end block 2 */
	// End Line: 1277

void _G2Instance_BuildDeactivatedTransforms(_Instance *instance)

{
  short *psVar1;
  int iVar2;
  int in_v0;
  undefined4 uVar3;
  undefined4 uVar4;
  undefined4 uVar5;
  int unaff_s0;
  _Instance *instance_00;
  undefined4 *unaff_s1;
  undefined4 *puVar6;
  undefined2 *unaff_s2;
  uint *unaff_s3;
  uint *puVar7;
  int unaff_s4;
  int unaff_s6;
  int unaff_s8;
  undefined2 in_stack_00000018;
  
  while (in_v0 == 0) {
    FUN_80039ae8(unaff_s1);
    while( true ) {
      if (unaff_s6 != 0) {
        FUN_80078fec(unaff_s1);
      }
      *(int *)(unaff_s2 + 1) = (int)*(short *)(unaff_s0 + 0x5c);
      *(int *)(unaff_s2 + 3) = (int)*(short *)(unaff_s0 + 0x5e);
      *(int *)(unaff_s2 + 5) = (int)*(short *)(unaff_s0 + 0x60);
      puVar7 = unaff_s3;
      do {
        puVar6 = unaff_s1;
        unaff_s1 = puVar6 + 8;
        unaff_s3 = puVar7 + 6;
        unaff_s4 = unaff_s4 + 1;
        *unaff_s2 = in_stack_00000018;
        unaff_s2 = unaff_s2 + 0x10;
        if (*(int *)(unaff_s8 + 0x18) <= unaff_s4) {
          instance_00 = *(_Instance **)(unaff_s0 + 0x130);
          while (instance_00 != (_Instance *)0x0) {
            _G2Instance_RebuildAnimatedTransforms(instance_00);
            instance_00 = instance_00->LinkSibling;
          }
          return;
        }
        psVar1 = (short *)((int)puVar7 + 0x1e);
        puVar7 = unaff_s3;
      } while (*psVar1 == -1);
      if ((*unaff_s3 & 3) != 0) {
                    /* WARNING: Subroutine does not return */
        rm_1(unaff_s0 + 0x74);
      }
      if (((*(uint *)(unaff_s0 + 0x14) & 1) == 0) || (*(int *)(unaff_s0 + 0x20) == 0)) break;
      iVar2 = *(int *)(*(int *)(unaff_s0 + 0x20) + 0x38);
      uVar5 = *(undefined4 *)(iVar2 + 0x34);
      uVar3 = *(undefined4 *)(iVar2 + 0x38);
      uVar4 = *(undefined4 *)(iVar2 + 0x3c);
      *unaff_s1 = *(undefined4 *)(iVar2 + 0x30);
      puVar6[9] = uVar5;
      puVar6[10] = uVar3;
      puVar6[0xb] = uVar4;
      uVar5 = *(undefined4 *)(iVar2 + 0x44);
      uVar3 = *(undefined4 *)(iVar2 + 0x48);
      uVar4 = *(undefined4 *)(iVar2 + 0x4c);
      puVar6[0xc] = *(undefined4 *)(iVar2 + 0x40);
      puVar6[0xd] = uVar5;
      puVar6[0xe] = uVar3;
      puVar6[0xf] = uVar4;
    }
    instance = (_Instance *)(unaff_s0 + 0x74);
    if (*(short *)(unaff_s0 + 0x78) != 0) break;
    in_v0 = *(int *)(unaff_s0 + 0x74);
  }
                    /* WARNING: Subroutine does not return */
  rm_1(instance,unaff_s1);
}



// decompiled code
// original method signature: 
// void /*$ra*/ _G2Instance_BuildNonAnimatedTransforms(struct _Instance *instance /*$s0*/)
 // line 583, offset 0x80095934
	/* begin block 1 */
		// Start line: 584
		// Start offset: 0x80095934
		// Variables:
	// 		struct MATRIX *segMatrix; // $v1
	// 		struct _Model *model; // $v0
	/* end block 1 */
	// End offset: 0x800959E0
	// End Line: 611

	/* begin block 2 */
		// Start line: 1415
	/* end block 2 */
	// End Line: 1416

void _G2Instance_BuildNonAnimatedTransforms(_Instance *instance)

{
  int iVar1;
  uint in_v1;
  int in_a1;
  int iVar2;
  int unaff_s0;
  _Instance *instance_00;
  int iVar3;
  
  if ((*(uint *)(in_a1 + 0x2c) & in_v1) == 0) {
    iVar3 = instance->flags2 + 1;
  }
  else {
    iVar3 = instance->flags2;
  }
  iVar1 = FUN_80030e8c(iVar3);
  if (iVar1 == 0) {
    *(undefined4 *)(unaff_s0 + 0x40) = 0;
  }
  else {
    *(int *)(unaff_s0 + 0x44) = *(int *)(unaff_s0 + 0x40);
    if ((*(int *)(*(int *)(unaff_s0 + 0x1c) + 0x10) == 0) ||
       (iVar2 = *(int *)(unaff_s0 + 0x40) + -0x20,
       (*(uint *)(*(int *)(unaff_s0 + 0x1c) + 0x2c) & 0x40000000) != 0)) {
      iVar2 = *(int *)(unaff_s0 + 0x44);
      *(int *)(unaff_s0 + 0x40) = iVar1;
    }
    else {
      *(int *)(unaff_s0 + 0x40) = iVar1 + 0x20;
    }
    if (*(int *)(unaff_s0 + 0x44) != 0) {
      FUN_8007919c(iVar1,iVar2,iVar3 << 5);
    }
    instance_00 = *(_Instance **)(unaff_s0 + 0x130);
    while (instance_00 != (_Instance *)0x0) {
      _G2Instance_RebuildAnimatedTransforms(instance_00);
      instance_00 = instance_00->LinkSibling;
    }
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ _G2Instance_BuildFacadeTransforms(struct _Instance *instance /*$s0*/, struct _Segment *segment /*$s1*/, struct MATRIX *segMatrix /*$s5*/, struct MATRIX *matrixPool /*$s6*/, long scale_flag /*stack 16*/)
 // line 619, offset 0x800959f0
	/* begin block 1 */
		// Start line: 620
		// Start offset: 0x800959F0
		// Variables:
	// 		struct _Position *cameraPos; // $s7
	// 		struct SVECTOR *segmentPos; // $s3
	// 		struct SVECTOR *segmentRot; // $s4
	// 		struct VECTOR *scale; // $fp

		/* begin block 1.1 */
			// Start line: 644
			// Start offset: 0x80095B1C
			// Variables:
		// 		struct SVECTOR *zvec; // $s1
		// 		struct SVECTOR *camWorldPos; // $s2
		// 		struct SVECTOR *camLocPos; // $s6
		// 		long sqrt; // $s0
		/* end block 1.1 */
		// End offset: 0x80095C38
		// End Line: 676

		/* begin block 1.2 */
			// Start line: 683
			// Start offset: 0x80095C98
			// Variables:
		// 		struct VECTOR *xy; // $s0
		/* end block 1.2 */
		// End offset: 0x80095D5C
		// End Line: 702
	/* end block 1 */
	// End offset: 0x80095D5C
	// End Line: 703

	/* begin block 2 */
		// Start line: 1488
	/* end block 2 */
	// End Line: 1489

void _G2Instance_BuildFacadeTransforms
               (_Instance *instance,_Segment *segment,MATRIX *segMatrix,MATRIX *matrixPool,
               long scale_flag)

{
  _Instance *instance_00;
  
  while (instance_00 != (_Instance *)0x0) {
    _G2Instance_RebuildAnimatedTransforms(instance_00);
    instance_00 = instance_00->LinkSibling;
  }
  return;
}





