#include "THISDUST.H"
#include "POOLMMG2.H"


// decompiled code
// original method signature: 
// void /*$ra*/ G2PoolMem_InitPool(void *voidPool /*$s1*/, int blockCount /*$s0*/, int blockSize /*$s2*/)
 // line 9, offset 0x80095d9c
	/* begin block 1 */
		// Start line: 10
		// Start offset: 0x80095D9C
	/* end block 1 */
	// End offset: 0x80095D9C
	// End Line: 10

	/* begin block 2 */
		// Start line: 18
	/* end block 2 */
	// End Line: 19

void G2PoolMem_InitPool(void *voidPool,int blockCount,int blockSize)

{
  short in_v0;
  int in_v1;
  int unaff_s0;
  int unaff_s3;
  
  *(int *)(unaff_s0 + 4) = blockCount - (int)in_v0;
                    /* WARNING: Subroutine does not return */
  *(int *)(unaff_s0 + 8) = (in_v1 >> 0x10) - (int)*(short *)(unaff_s3 + 4);
  FUN_80039564();
}



// decompiled code
// original method signature: 
// void /*$ra*/ G2PoolMem_ResetPool(void *voidPool /*$a0*/)
 // line 32, offset 0x80095e08
	/* begin block 1 */
		// Start line: 35
		// Start offset: 0x80095E08
		// Variables:
	// 		struct _G2PoolMemPool_Type *pool; // $a0
	// 		int blockIndex; // $a1
	/* end block 1 */
	// End offset: 0x80095E3C
	// End Line: 48

	/* begin block 2 */
		// Start line: 81
	/* end block 2 */
	// End Line: 82

	/* begin block 3 */
		// Start line: 83
	/* end block 3 */
	// End Line: 84

	/* begin block 4 */
		// Start line: 94
	/* end block 4 */
	// End Line: 95

void G2PoolMem_ResetPool(void *voidPool)

{
  short *unaff_s4;
  
  FUN_80078fec();
  FUN_80078bf4((int)*unaff_s4);
                    /* WARNING: Subroutine does not return */
  FUN_80078e5c((int)unaff_s4[2]);
}



// decompiled code
// original method signature: 
// void * /*$ra*/ G2PoolMem_Allocate(void *voidPool /*$a1*/)
 // line 64, offset 0x80095e44
	/* begin block 1 */
		// Start line: 65
		// Start offset: 0x80095E44
		// Variables:
	// 		int blockIndex; // $a0
	/* end block 1 */
	// End offset: 0x80095E98
	// End Line: 86

	/* begin block 2 */
		// Start line: 128
	/* end block 2 */
	// End Line: 129

void * G2PoolMem_Allocate(void *voidPool)

{
  void *in_v0;
  
  return in_v0;
}



// autogenerated function stub: 
// void /*$ra*/ G2PoolMem_Free(void *voidPool /*$a0*/, void *block /*$a1*/)
void G2PoolMem_Free(void *voidPool, void *block)
{ // line 87, offset 0x80095ea0
	/* begin block 1 */
		// Start line: 90
		// Start offset: 0x80095EA0
		// Variables:
			int blockIndex; // $a1
	/* end block 1 */
	// End offset: 0x80095EA0
	// End Line: 96

	/* begin block 2 */
		// Start line: 192
	/* end block 2 */
	// End Line: 193

	/* begin block 3 */
		// Start line: 194
	/* end block 3 */
	// End Line: 195

	/* begin block 4 */
		// Start line: 200
	/* end block 4 */
	// End Line: 201

}




