#include "THISDUST.H"
#include "VWRAITH.H"


// autogenerated function stub: 
// void /*$ra*/ VWRAITH_MoveVertical(struct _Instance *instance /*$a0*/, long targetZ /*$a1*/, int velocity /*$a2*/)
void VWRAITH_MoveVertical(struct _Instance *instance, long targetZ, int velocity)
{ // line 89, offset 0x8008e8f4
	/* begin block 1 */
		// Start line: 178
	/* end block 1 */
	// End Line: 179

	/* begin block 2 */
		// Start line: 179
	/* end block 2 */
	// End Line: 180

}


// autogenerated function stub: 
// void /*$ra*/ VWRAITH_Init(struct _Instance *instance /*$s1*/)
void VWRAITH_Init(struct _Instance *instance)
{ // line 108, offset 0x8008e94c
	/* begin block 1 */
		// Start line: 109
		// Start offset: 0x8008E94C
		// Variables:
			struct _MonsterVars *mv; // $s0
			long color; // stack offset -24
	/* end block 1 */
	// End offset: 0x8008E97C
	// End Line: 111

	/* begin block 2 */
		// Start line: 216
	/* end block 2 */
	// End Line: 217

}


// decompiled code
// original method signature: 
// int /*$ra*/ VWRAITH_ShouldISwoop(struct _Instance *instance /*$a0*/)
 // line 131, offset 0x8008ea00
	/* begin block 1 */
		// Start line: 132
		// Start offset: 0x8008EA00
		// Variables:
	// 		struct _MonsterAttributes *ma; // $a3
	// 		struct _MonsterVars *mv; // $v1

		/* begin block 1.1 */
			// Start line: 138
			// Start offset: 0x8008EA34
			// Variables:
		// 		struct _Instance *ei; // $a1
		/* end block 1.1 */
		// End offset: 0x8008EA74
		// End Line: 143
	/* end block 1 */
	// End offset: 0x8008EA74
	// End Line: 146

	/* begin block 2 */
		// Start line: 281
	/* end block 2 */
	// End Line: 282

int VWRAITH_ShouldISwoop(_Instance *instance)

{
  uint uVar1;
  uint *unaff_s0;
  undefined4 uStack00000010;
  undefined4 uStack00000014;
  undefined4 uStack00000018;
  
  uStack00000010 = 1;
  uStack00000014 = 0x4b0;
  uStack00000018 = 0x9c;
  uVar1 = FUN_8004b040();
  unaff_s0[0x37] = uVar1;
  FUN_8008cba8();
  *(undefined2 *)(unaff_s0 + 0x4d) = 0x3000;
  uVar1 = unaff_s0[1];
  unaff_s0[1] = uVar1 & 0xfffffffe;
  *unaff_s0 = *unaff_s0 | 0x10002800;
  return uVar1 & 0xfffffffe;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VWRAITH_PursueEntry(struct _Instance *instance /*$s1*/)
 // line 151, offset 0x8008ea84
	/* begin block 1 */
		// Start line: 152
		// Start offset: 0x8008EA84
		// Variables:
	// 		struct _MonsterVars *mv; // $s0

		/* begin block 1.1 */
			// Start line: 166
			// Start offset: 0x8008EAE0
			// Variables:
		// 		struct _MonsterAttributes *ma; // $v0
		/* end block 1.1 */
		// End offset: 0x8008EB08
		// End Line: 171
	/* end block 1 */
	// End offset: 0x8008EB08
	// End Line: 172

	/* begin block 2 */
		// Start line: 324
	/* end block 2 */
	// End Line: 325

void VWRAITH_PursueEntry(_Instance *instance)

{
  uint uVar1;
  
  if (((((*(uint *)instance->extraData & 4) == 0) &&
       (uVar1 = *(uint *)(instance->extraData + 0x31), uVar1 != 0)) &&
      (*(short *)(*(int *)(uVar1 + 4) + 0x60) <= (instance->position).z)) &&
     (*(short *)(*(int *)((int)instance->data + 4) + 0xc) < *(short *)(uVar1 + 0x14))) {
    FUN_800800f8();
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VWRAITH_Pursue(struct _Instance *instance /*$s2*/)
 // line 174, offset 0x8008eb1c
	/* begin block 1 */
		// Start line: 175
		// Start offset: 0x8008EB1C
		// Variables:
	// 		struct _MonsterAttributes *ma; // $s1
	// 		struct _MonsterVars *mv; // $s0

		/* begin block 1.1 */
			// Start line: 195
			// Start offset: 0x8008EBBC
			// Variables:
		// 		struct _MonsterAttributes *ma; // $s1
		// 		struct _MonsterAttackAttributes *attack; // $s3
		/* end block 1.1 */
		// End offset: 0x8008ECAC
		// End Line: 218
	/* end block 1 */
	// End offset: 0x8008ECD0
	// End Line: 225

	/* begin block 2 */
		// Start line: 370
	/* end block 2 */
	// End Line: 371

void VWRAITH_Pursue(_Instance *instance)

{
  int iVar1;
  int unaff_s0;
  
  iVar1 = FUN_8008ea80();
  if (iVar1 != 0) {
    *(uint *)(unaff_s0 + 4) = *(uint *)(unaff_s0 + 4) | 2;
  }
  if ((*(uint *)(unaff_s0 + 4) & 2) == 0) {
    FUN_8008a5c8();
  }
  else {
    FUN_8007fc04();
    *(undefined4 *)(unaff_s0 + 0xf4) = 4;
    *(undefined2 *)(unaff_s0 + 0x110) = 0;
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VWRAITH_VerticalMove(struct _Instance *instance /*$s0*/)
 // line 230, offset 0x8008ecec
	/* begin block 1 */
		// Start line: 231
		// Start offset: 0x8008ECEC
		// Variables:
	// 		struct _MonsterVars *mv; // $v0

		/* begin block 1.1 */
			// Start line: 236
			// Start offset: 0x8008ED18
			// Variables:
		// 		struct _MonsterAttributes *ma; // $v0
		// 		long targetZ; // $s1
		/* end block 1.1 */
		// End offset: 0x8008ED5C
		// End Line: 242
	/* end block 1 */
	// End offset: 0x8008ED5C
	// End Line: 243

	/* begin block 2 */
		// Start line: 494
	/* end block 2 */
	// End Line: 495

void VWRAITH_VerticalMove(_Instance *instance)

{
  int unaff_s0;
  
  FUN_8007fc04();
  FUN_8008e974();
  if (*(short *)(unaff_s0 + 0x110) != 0) {
    FUN_80080f90();
  }
  FUN_80085a94();
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VWRAITH_CombatEntry(struct _Instance *instance /*$a0*/)
 // line 248, offset 0x8008ed70
	/* begin block 1 */
		// Start line: 531
	/* end block 1 */
	// End Line: 532

void VWRAITH_CombatEntry(_Instance *instance)

{
  int iVar1;
  
  iVar1 = *(int *)((int)instance->extraData + 0xc4);
  if (iVar1 != 0) {
    iVar1 = (int)*(short *)(*(int *)(iVar1 + 4) + 0x60);
    FUN_8008e974(instance,iVar1,(int)*(short *)(*(int *)((int)instance->data + 4) + 8));
    if ((instance->currentMainState == 6) && ((int)(instance->position).z != iVar1)) {
                    /* WARNING: Subroutine does not return */
      FUN_8007f88c(instance,0xd);
    }
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VWRAITH_Combat(struct _Instance *instance /*$s0*/)
 // line 253, offset 0x8008ed90
	/* begin block 1 */
		// Start line: 541
	/* end block 1 */
	// End Line: 542

void VWRAITH_Combat(_Instance *instance)

{
  int in_v1;
  int unaff_s0;
  int iVar1;
  
  if (in_v1 != 0) {
    iVar1 = (int)*(short *)(*(int *)(in_v1 + 4) + 0x60);
    FUN_8008e974(instance,iVar1,(int)*(short *)(*(int *)(*(int *)(unaff_s0 + 0x24) + 4) + 8));
    if ((*(int *)(unaff_s0 + 0x178) == 6) && ((int)*(short *)(unaff_s0 + 0x60) != iVar1)) {
                    /* WARNING: Subroutine does not return */
      FUN_8007f88c();
    }
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VWRAITH_EmbraceEntry(struct _Instance *instance /*$a0*/)
 // line 263, offset 0x8008edbc
	/* begin block 1 */
		// Start line: 561
	/* end block 1 */
	// End Line: 562

void VWRAITH_EmbraceEntry(_Instance *instance)

{
  int in_v0;
  int in_v1;
  int unaff_s0;
  int unaff_s1;
  
  if ((in_v1 == in_v0) && ((int)*(short *)(unaff_s0 + 0x60) != unaff_s1)) {
                    /* WARNING: Subroutine does not return */
    FUN_8007f88c();
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VWRAITH_Embrace(struct _Instance *instance /*$s0*/)
 // line 268, offset 0x8008eddc
	/* begin block 1 */
		// Start line: 571
	/* end block 1 */
	// End Line: 572

void VWRAITH_Embrace(_Instance *instance)

{
  return;
}





