#include "THISDUST.H"
#include "PLANAPI.H"


// autogenerated function stub: 
// void /*$ra*/ PLANAPI_ConvertPlanIntoEnmyPlanDataFormat(struct PlanningNode *goalNode /*$a0*/, struct EnemyPlanData *planData /*$s1*/, struct PlanningNode *planningPool /*$s2*/)
void PLANAPI_ConvertPlanIntoEnmyPlanDataFormat(struct PlanningNode *goalNode, struct EnemyPlanData *planData, struct PlanningNode *planningPool)
{ // line 131, offset 0x80097b8c
	/* begin block 1 */
		// Start line: 132
		// Start offset: 0x80097B8C
		// Variables:
			struct PlanningNode *currentNode; // $s0
			int i; // $a0
	/* end block 1 */
	// End offset: 0x80097C28
	// End Line: 151

	/* begin block 2 */
		// Start line: 262
	/* end block 2 */
	// End Line: 263

}


// decompiled code
// original method signature: 
// int /*$ra*/ PLANAPI_FindPathBetweenNodes(struct PlanningNode *startNode /*$v0*/, struct PlanningNode *goalNode /*$v1*/, struct EnemyPlanData *planData /*$s3*/, int validNodeTypes /*$a3*/)
 // line 157, offset 0x80097c40
	/* begin block 1 */
		// Start line: 158
		// Start offset: 0x80097C40
		// Variables:
	// 		struct PlanningNode *planningPool; // $s1
	// 		int successFlag; // $s2
	/* end block 1 */
	// End offset: 0x80097CA8
	// End Line: 172

	/* begin block 2 */
		// Start line: 317
	/* end block 2 */
	// End Line: 318

int PLANAPI_FindPathBetweenNodes
              (PlanningNode *startNode,PlanningNode *goalNode,EnemyPlanData *planData,
              int validNodeTypes)

{
  int unaff_s3;
  
  return unaff_s3;
}



// decompiled code
// original method signature: 
// void /*$ra*/ PLANAPI_DoTimingCalcsAndDrawing(long startTime /*$a0*/, struct PlanningNode *planningPool /*$s2*/)
 // line 177, offset 0x80097cc8
	/* begin block 1 */
		// Start line: 178
		// Start offset: 0x80097CC8
		// Variables:
	// 		int i; // $a1
	// 		long minTime; // $s1
	// 		long maxTime; // $s0

		/* begin block 1.1 */
			// Start line: 199
			// Start offset: 0x80097D70
		/* end block 1.1 */
		// End offset: 0x80097DCC
		// End Line: 221
	/* end block 1 */
	// End offset: 0x80097DCC
	// End Line: 222

	/* begin block 2 */
		// Start line: 361
	/* end block 2 */
	// End Line: 362

void PLANAPI_DoTimingCalcsAndDrawing(long startTime,PlanningNode *planningPool)

{
  undefined uVar1;
  undefined *in_v0;
  undefined4 in_a3;
  ushort in_t0;
  undefined4 *unaff_s0;
  int unaff_s1;
  int unaff_s2;
  
  do {
    *(undefined4 *)&planningPool->cost = in_a3;
    planningPool->nodeType = in_t0;
    uVar1 = *(undefined *)(unaff_s0 + 5);
    *in_v0 = 0;
    in_v0[8] = uVar1;
    do {
      planningPool = (PlanningNode *)((int)&planningPool[-1].streamUnitID + 2);
      startTime = startTime + -1;
      unaff_s0 = (undefined4 *)(unaff_s2 + (uint)*(ushort *)((int)unaff_s0 + 0x12) * 0x1c);
      if (startTime < 0) {
        return;
      }
      in_v0 = (undefined *)(unaff_s1 + startTime);
    } while (7 < startTime);
    in_a3 = *unaff_s0;
    in_t0 = *(ushort *)(unaff_s0 + 1);
  } while( true );
}



// decompiled code
// original method signature: 
// int /*$ra*/ PLANAPI_AddNodeOfTypeToPool(struct _Position *pos /*$s0*/, int type /*$s2*/)
 // line 269, offset 0x80097de4
	/* begin block 1 */
		// Start line: 270
		// Start offset: 0x80097DE4
		// Variables:
	// 		struct PlanningNode *planningPool; // $s1
	// 		int foundHit; // $v1
	// 		int nodePlacement; // stack offset -24
	// 		struct _PlanCollideInfo pci; // stack offset -40

		/* begin block 1.1 */
			// Start line: 284
			// Start offset: 0x80097E30
			// Variables:
		// 		short _x1; // $v0
		// 		short _y1; // $v1
		// 		short _z1; // $t0
		// 		struct _Position *_v0; // $s0
		/* end block 1.1 */
		// End offset: 0x80097E30
		// End Line: 284
	/* end block 1 */
	// End offset: 0x80097EAC
	// End Line: 294

	/* begin block 2 */
		// Start line: 552
	/* end block 2 */
	// End Line: 553

int PLANAPI_AddNodeOfTypeToPool(_Position *pos,int type)

{
  uint uVar1;
  int in_v1;
  int unaff_s0;
  int unaff_s1;
  
  while( true ) {
    if (in_v1 < unaff_s1) {
      unaff_s1 = in_v1;
    }
    if (unaff_s0 < in_v1) {
      unaff_s0 = in_v1;
    }
    type = type + 1;
    pos = (_Position *)&pos->z;
    if (9 < type) break;
    in_v1 = *(int *)pos;
  }
  _G2AnimSegValue_Type_ARRAY_800d4f7c[4].trans._0_4_ =
       _G2AnimSegValue_Type_ARRAY_800d4f7c[4].trans._0_4_ + 1;
  if (9 < _G2AnimSegValue_Type_ARRAY_800d4f7c[4].trans._0_4_) {
    _G2AnimSegValue_Type_ARRAY_800d4f7c[4].trans._0_4_ = 0;
  }
  uVar1 = draw[0].dr_env.code[1] & 0x10;
  if (uVar1 != 0) {
    FUN_80099420();
    FUN_80099420();
    FUN_80099420();
    FUN_80099420();
    FUN_8009946c();
    FUN_8009946c();
    FUN_8009946c();
    uVar1 = FUN_8009946c();
  }
  return uVar1;
}



// decompiled code
// original method signature: 
// void /*$ra*/ PLANAPI_DeleteNodesFromPoolByType(int nodeSource /*$s3*/)
 // line 306, offset 0x80097ec4
	/* begin block 1 */
		// Start line: 307
		// Start offset: 0x80097EC4
		// Variables:
	// 		struct PlanningNode *planningPool; // $s2
	// 		struct PlanningNode *nodeToDelete; // $s0
	// 		int i; // $s1
	/* end block 1 */
	// End offset: 0x80097F44
	// End Line: 324

	/* begin block 2 */
		// Start line: 612
	/* end block 2 */
	// End Line: 613

	/* begin block 3 */
		// Start line: 626
	/* end block 3 */
	// End Line: 627

void PLANAPI_DeleteNodesFromPoolByType(int nodeSource)

{
  long lVar1;
  int iVar2;
  uint in_a1;
  uint uVar3;
  int iStack00000010;
  int in_stack_00000018;
  undefined2 in_stack_00000020;
  undefined2 in_stack_00000022;
  undefined2 in_stack_00000024;
  ushort in_stack_00000028;
  
  lVar1 = gameTrackerX.drawPage;
  iStack00000010 = FUN_80098d2c();
  if ((loadStatus.decompressLen == 0x103e8) || (iStack00000010 == -1)) {
    in_stack_00000020 = *(undefined2 *)nodeSource;
    in_stack_00000022 = *(undefined2 *)(nodeSource + 2);
    in_stack_00000024 = *(undefined2 *)(nodeSource + 4);
    nodeSource = (int)&stack0x00000020;
    iStack00000010 = 0;
    iVar2 = FUN_80098e98(&stack0x00000018,&stack0x00000028,0x100,0xfffffd80);
    if (iVar2 == 0) {
      return;
    }
    uVar3 = ((uint)in_stack_00000028 & 3) << 3 | in_a1 & 7;
    iStack00000010 = in_stack_00000018;
  }
  else {
    uVar3 = in_a1 & 7 | 0x18;
  }
  FUN_80099c00(nodeSource,lVar1,uVar3,0);
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ PLANAPI_DeleteNodeFromPoolByUnit(long streamUnitID /*$s3*/)
 // line 327, offset 0x80097f60
	/* begin block 1 */
		// Start line: 328
		// Start offset: 0x80097F60
		// Variables:
	// 		struct PlanningNode *planningPool; // $s2
	// 		struct PlanningNode *nodeToDelete; // $s0
	// 		int i; // $s1
	/* end block 1 */
	// End offset: 0x80097FDC
	// End Line: 347

	/* begin block 2 */
		// Start line: 683
	/* end block 2 */
	// End Line: 684

	/* begin block 3 */
		// Start line: 688
	/* end block 3 */
	// End Line: 689

void PLANAPI_DeleteNodeFromPoolByUnit(long streamUnitID)

{
  return;
}



// decompiled code
// original method signature: 
// int /*$ra*/ PLANAPI_FindPathInGraphToTarget(struct _Position *startPos /*$a0*/, struct EnemyPlanData *planData /*$s1*/, int validNodeTypes /*$s2*/)
 // line 388, offset 0x80097ff8
	/* begin block 1 */
		// Start line: 389
		// Start offset: 0x80097FF8
		// Variables:
	// 		struct PlanningNode *planningPool; // $s0
	// 		struct PlanningNode *startNode; // $s0
	/* end block 1 */
	// End offset: 0x80097FF8
	// End Line: 389

	/* begin block 2 */
		// Start line: 827
	/* end block 2 */
	// End Line: 828

int PLANAPI_FindPathInGraphToTarget(_Position *startPos,EnemyPlanData *planData,int validNodeTypes)

{
  bool bVar1;
  int unaff_s0;
  int unaff_s1;
  uint unaff_s3;
  
  do {
    FUN_80099cf4();
    while( true ) {
      bVar1 = unaff_s1 < (int)(uint)*(byte *)(_G2AnimSegValue_Type_ARRAY_800d4f7c[4]._20_4_ + 1);
      if (!bVar1) {
        return (uint)bVar1;
      }
      if (((uint)*(ushort *)(unaff_s0 + 0x14) & 7) == unaff_s3) break;
      unaff_s1 = unaff_s1 + 1;
      unaff_s0 = unaff_s0 + 0x1c;
    }
  } while( true );
}



// decompiled code
// original method signature: 
// void /*$ra*/ PLANAPI_InitPlanning(void *planningPool /*$a0*/)
 // line 405, offset 0x8009805c
	/* begin block 1 */
		// Start line: 407
		// Start offset: 0x8009805C
		// Variables:
	// 		int i; // $a1
	// 		int j; // $a0
	/* end block 1 */
	// End offset: 0x800980D0
	// End Line: 439

	/* begin block 2 */
		// Start line: 862
	/* end block 2 */
	// End Line: 863

	/* begin block 3 */
		// Start line: 863
	/* end block 3 */
	// End Line: 864

	/* begin block 4 */
		// Start line: 885
	/* end block 4 */
	// End Line: 886

void PLANAPI_InitPlanning(void *planningPool)

{
  int in_v0;
  int unaff_s0;
  int iVar1;
  
  iVar1 = 0;
  if (*(char *)(in_v0 + 1) != '\0') {
    do {
      if (*(void **)(unaff_s0 + 0x18) == planningPool) {
        FUN_80099cf4(unaff_s0);
      }
      else {
        iVar1 = iVar1 + 1;
        unaff_s0 = unaff_s0 + 0x1c;
      }
    } while (iVar1 < (int)(uint)*(byte *)(_G2AnimSegValue_Type_ARRAY_800d4f7c[4]._20_4_ + 1));
  }
  return;
}



// decompiled code
// original method signature: 
// short /*$ra*/ PLANAPI_PairType(struct PlanningNode *node1 /*$a0*/, struct PlanningNode *node2 /*$a1*/)
 // line 446, offset 0x800980dc
	/* begin block 1 */
		// Start line: 448
		// Start offset: 0x800980DC
		// Variables:
	// 		short placement1; // $a2
	// 		short placement2; // $a1
	/* end block 1 */
	// End offset: 0x80098118
	// End Line: 457

	/* begin block 2 */
		// Start line: 964
	/* end block 2 */
	// End Line: 965

	/* begin block 3 */
		// Start line: 965
	/* end block 3 */
	// End Line: 966

	/* begin block 4 */
		// Start line: 969
	/* end block 4 */
	// End Line: 970

short PLANAPI_PairType(PlanningNode *node1,PlanningNode *node2)

{
  short in_v0;
  
  return in_v0;
}



// decompiled code
// original method signature: 
// int /*$ra*/ PLANAPI_PassThroughHit(struct PlanningNode *node1 /*$a0*/, struct PlanningNode *node2 /*$a1*/)
 // line 462, offset 0x80098124
	/* begin block 1 */
		// Start line: 464
		// Start offset: 0x80098124
		// Variables:
	// 		int src1; // $a0
	// 		int src2; // $v1
	// 		int res; // $v1
	/* end block 1 */
	// End offset: 0x80098188
	// End Line: 485

	/* begin block 2 */
		// Start line: 997
	/* end block 2 */
	// End Line: 998

	/* begin block 3 */
		// Start line: 998
	/* end block 3 */
	// End Line: 999

	/* begin block 4 */
		// Start line: 1002
	/* end block 4 */
	// End Line: 1003

int PLANAPI_PassThroughHit(PlanningNode *node1,PlanningNode *node2)

{
  int iVar1;
  
  iVar1 = FUN_80097d18();
  return iVar1;
}



// decompiled code
// original method signature: 
// int /*$ra*/ PLANAPI_CheckTargetToEnemyNode(struct PlanningNode **node1 /*$s2*/, struct PlanningNode **node2 /*$s3*/)
 // line 487, offset 0x80098190
	/* begin block 1 */
		// Start line: 488
		// Start offset: 0x80098190
		// Variables:
	// 		struct PlanningNode *planningPool; // $s0
	// 		struct PlanningNode *temp1; // $s1
	// 		struct PlanningNode *temp2; // $a1
	/* end block 1 */
	// End offset: 0x80098284
	// End Line: 511

	/* begin block 2 */
		// Start line: 1048
	/* end block 2 */
	// End Line: 1049

int PLANAPI_CheckTargetToEnemyNode(PlanningNode **node1,PlanningNode **node2)

{
  undefined4 *puVar1;
  int iVar2;
  int iVar3;
  int in_a3;
  
  while (node2 = (PlanningNode **)((int)node2 + 1), (int)node2 < 0x20) {
    iVar2 = 0;
    iVar3 = 0;
    do {
      iVar2 = iVar2 + 1;
      *(undefined2 *)(iVar3 + (int)node2 * 0x40 + *(int *)(in_a3 + 0x10)) = 0;
      iVar3 = iVar2 * 2;
    } while (iVar2 < 0x20);
  }
  iVar3 = 9;
  puVar1 = (undefined4 *)&_G2AnimSegValue_Type_ARRAY_800d4f7c[4].scale.z;
  do {
    *puVar1 = 0;
    iVar3 = iVar3 + -1;
    puVar1 = puVar1 + -1;
  } while (-1 < iVar3);
  _G2AnimSegValue_Type_ARRAY_800d4f7c[4].trans._0_4_ = 0;
  return (int)puVar1;
}



// decompiled code
// original method signature: 
// void /*$ra*/ PLANAPI_UpdatePlanningDatabase(struct GameTracker *gameTracker /*$a0*/, struct _Instance *player /*$s2*/)
 // line 517, offset 0x800982a0
	/* begin block 1 */
		// Start line: 518
		// Start offset: 0x800982A0
		// Variables:
	// 		struct PlanningNode *planningPool; // $s1
	// 		struct PlanningNode *node1; // stack offset -32
	// 		struct PlanningNode *node2; // stack offset -28
	// 		long startTime; // $s3
	// 		int pathExistsAbove; // $s0
	// 		int pathExistsBelow; // $v1

		/* begin block 1.1 */
			// Start line: 566
			// Start offset: 0x800984A8
		/* end block 1.1 */
		// End offset: 0x800984B4
		// End Line: 570
	/* end block 1 */
	// End offset: 0x80098720
	// End Line: 681

	/* begin block 2 */
		// Start line: 1116
	/* end block 2 */
	// End Line: 1117

void PLANAPI_UpdatePlanningDatabase(GameTracker *gameTracker,_Instance *player)

{
  int iVar1;
  int iVar2;
  int unaff_s0;
  int *unaff_s2;
  int *unaff_s3;
  
  iVar1 = FUN_800993d0();
  iVar2 = FUN_800993d0();
  if (((iVar1 != 0) && (iVar2 != 0)) &&
     (((*(uint *)(iVar1 + 8) & 1 << ((iVar2 - unaff_s0) * -0x49249249 >> 2 & 0x1fU)) == 0 ||
      ((*(uint *)(iVar2 + 8) & 1 << ((iVar1 - unaff_s0) * -0x49249249 >> 2 & 0x1fU)) == 0)))) {
    *unaff_s2 = iVar1;
    *unaff_s3 = iVar2;
  }
  return;
}



// decompiled code
// original method signature: 
// int /*$ra*/ PLANAPI_NumNodesInPool(void *planningPool /*$a0*/)
 // line 689, offset 0x8009874c
	/* begin block 1 */
		// Start line: 1491
	/* end block 1 */
	// End Line: 1492

	/* begin block 2 */
		// Start line: 1492
	/* end block 2 */
	// End Line: 1493

int PLANAPI_NumNodesInPool(void *planningPool)

{
  int iVar1;
  undefined4 uVar2;
  int iVar3;
  undefined4 in_a1;
  undefined4 uStack00000010;
  undefined4 in_stack_00000018;
  undefined4 in_stack_0000001c;
  
  iVar1 = FUN_800991e4(planningPool,in_a1,0,_G2AnimSegValue_Type_ARRAY_800d4f7c[4]._20_4_ + 0x16);
  uVar2 = FUN_80098210(in_stack_0000001c,in_stack_00000018);
  uStack00000010 = 0;
  iVar3 = FUN_80098c28(in_stack_00000018,_G2AnimSegValue_Type_ARRAY_800d4f7c[4]._20_4_ + 0x16,0,
                       uVar2);
  if ((iVar1 == 0) || (iVar3 == 0)) {
    FUN_800999dc(in_stack_0000001c,in_stack_00000018);
  }
  else {
    FUN_800998e0(in_stack_0000001c,in_stack_00000018);
  }
  *_G2AnimSegValue_Type_ARRAY_800d4f7c[4]._20_4_ = 1;
  iVar1 = FUN_80097da0();
  clearRect[0].y0._0_1_ = 0;
  return iVar1;
}



// decompiled code
// original method signature: 
// void /*$ra*/ PLANAPI_InitPlanMkrList(struct _StreamUnit *streamUnit /*$a0*/)
 // line 697, offset 0x80098760
	/* begin block 1 */
		// Start line: 698
		// Start offset: 0x80098760
		// Variables:
	// 		int i; // $s2
	// 		int terrainFoundFlag; // $v0
	// 		struct Level *level; // $v0
	// 		unsigned short numPlanMkrs; // $s3
	// 		struct _PlanMkr *planMkrList; // $v1

		/* begin block 1.1 */
			// Start line: 712
			// Start offset: 0x800987A0
			// Variables:
		// 		struct _PlanCollideInfo pci; // stack offset -40

			/* begin block 1.1.1 */
				// Start line: 713
				// Start offset: 0x800987A0
				// Variables:
			// 		short _x1; // $v0
			// 		short _y1; // $v1
			// 		short _z1; // $a0
			// 		struct _Position *_v0; // $s1
			/* end block 1.1.1 */
			// End offset: 0x800987A0
			// End Line: 713

			/* begin block 1.1.2 */
				// Start line: 738
				// Start offset: 0x8009883C
				// Variables:
			// 		short _x1; // $v0
			// 		short _y1; // $v1
			// 		short _z1; // $a0
			/* end block 1.1.2 */
			// End offset: 0x80098854
			// End Line: 738
		/* end block 1.1 */
		// End offset: 0x80098854
		// End Line: 741
	/* end block 1 */
	// End offset: 0x80098868
	// End Line: 742

	/* begin block 2 */
		// Start line: 1507
	/* end block 2 */
	// End Line: 1508

void PLANAPI_InitPlanMkrList(_StreamUnit *streamUnit)

{
  int in_v0;
  undefined4 uVar1;
  int iVar2;
  undefined4 uStack00000010;
  undefined4 in_stack_00000018;
  undefined4 in_stack_0000001c;
  
  uVar1 = FUN_80098210(in_stack_0000001c,in_stack_00000018);
  uStack00000010 = 0;
  iVar2 = FUN_80098c28(in_stack_00000018,_G2AnimSegValue_Type_ARRAY_800d4f7c[4]._20_4_ + 0x16,0,
                       uVar1);
  if ((in_v0 == 0) || (iVar2 == 0)) {
    FUN_800999dc(in_stack_0000001c,in_stack_00000018);
  }
  else {
    FUN_800998e0(in_stack_0000001c,in_stack_00000018);
  }
  *_G2AnimSegValue_Type_ARRAY_800d4f7c[4]._20_4_ = 1;
  FUN_80097da0();
  clearRect[0].y0._0_1_ = 0;
  return;
}



// decompiled code
// original method signature: 
// int /*$ra*/ PLANAPI_GetFlags(int type /*$a0*/)
 // line 755, offset 0x80098884
	/* begin block 1 */
		// Start line: 757
		// Start offset: 0x80098884
		// Variables:
	// 		int chk; // $v0
	/* end block 1 */
	// End offset: 0x800988E4
	// End Line: 779

	/* begin block 2 */
		// Start line: 1510
	/* end block 2 */
	// End Line: 1511

	/* begin block 3 */
		// Start line: 1641
	/* end block 3 */
	// End Line: 1642

	/* begin block 4 */
		// Start line: 1643
	/* end block 4 */
	// End Line: 1644

int PLANAPI_GetFlags(int type)

{
  ushort uVar1;
  bool bVar2;
  int iVar3;
  undefined2 *in_v1;
  undefined4 uVar4;
  undefined4 uVar5;
  int unaff_s2;
  uint unaff_s3;
  undefined4 uStack00000010;
  undefined4 uStack00000014;
  undefined2 uStack00000020;
  undefined2 uStack00000022;
  undefined2 uStack00000024;
  
  do {
    uStack00000020 = *in_v1;
    uStack00000022 = in_v1[1];
    uStack00000024 = in_v1[2];
    uVar1 = in_v1[3];
    if ((uVar1 & 0x5000) == 0) {
      if ((uVar1 & 0x8000) == 0) {
        if ((uVar1 & 0x2000) == 0) {
          uVar4 = 0x80;
          uVar5 = 0xfffffc00;
          uStack00000010 = 0;
          uStack00000014 = 0;
        }
        else {
          uVar4 = 0xffffff00;
          uVar5 = 0x280;
          uStack00000010 = 5;
          uStack00000014 = 5;
        }
      }
      else {
        uVar4 = 0xffffff00;
        uVar5 = 0x280;
        uStack00000010 = 1;
        uStack00000014 = 4;
      }
      iVar3 = FUN_80098e98(&stack0x00000018,0,uVar4,uVar5);
      if (iVar3 != 0) {
        *in_v1 = uStack00000020;
        in_v1[1] = uStack00000022;
        in_v1[2] = uStack00000024;
      }
    }
    unaff_s2 = unaff_s2 + 1;
    bVar2 = unaff_s2 < (int)(unaff_s3 & 0xffff);
    in_v1 = in_v1 + 4;
  } while (bVar2);
  return (uint)bVar2;
}



// decompiled code
// original method signature: 
// int /*$ra*/ PLANAPI_FindNodePositionInUnit(struct _StreamUnit *streamUnit /*$a0*/, struct _Position *pos /*$s3*/, int id /*$s2*/, int type /*$a3*/)
 // line 781, offset 0x800988ec
	/* begin block 1 */
		// Start line: 782
		// Start offset: 0x800988EC

		/* begin block 1.1 */
			// Start line: 785
			// Start offset: 0x80098910
			// Variables:
		// 		struct Level *level; // $v0
		// 		int numPlanMkrs; // $s0
		// 		struct _PlanMkr *planMkr; // $s1
		// 		int i; // $s0

			/* begin block 1.1.1 */
				// Start line: 795
				// Start offset: 0x80098944
				// Variables:
			// 		short _x1; // $v1
			// 		short _y1; // $a0
			// 		short _z1; // $a1
			/* end block 1.1.1 */
			// End offset: 0x80098944
			// End Line: 795
		/* end block 1.1 */
		// End offset: 0x80098970
		// End Line: 799
	/* end block 1 */
	// End offset: 0x80098974
	// End Line: 801

	/* begin block 2 */
		// Start line: 1692
	/* end block 2 */
	// End Line: 1693

int PLANAPI_FindNodePositionInUnit(_StreamUnit *streamUnit,_Position *pos,int id,int type)

{
  ushort uVar1;
  undefined2 uVar2;
  undefined2 uVar3;
  bool bVar4;
  int iVar5;
  undefined4 uVar6;
  undefined4 uVar7;
  undefined2 *unaff_s0;
  undefined2 *puVar8;
  int unaff_s1;
  int unaff_s2;
  uint unaff_s3;
  undefined4 uStack00000010;
  undefined4 uStack00000014;
  undefined2 in_stack_00000020;
  
  do {
    uVar6 = 0xffffff00;
    uVar7 = 0x280;
    uStack00000010 = 5;
    uStack00000014 = 5;
    while( true ) {
      while( true ) {
        iVar5 = FUN_80098e98(streamUnit,pos,uVar6,uVar7);
        puVar8 = unaff_s0;
        if (iVar5 != 0) {
          uVar2 = *(undefined2 *)(unaff_s1 + 2);
          uVar3 = *(undefined2 *)(unaff_s1 + 4);
          *unaff_s0 = in_stack_00000020;
          unaff_s0[1] = uVar2;
          unaff_s0[2] = uVar3;
          puVar8 = unaff_s0;
        }
        do {
          unaff_s2 = unaff_s2 + 1;
          bVar4 = unaff_s2 < (int)(unaff_s3 & 0xffff);
          unaff_s0 = puVar8 + 4;
          if (!bVar4) {
            return (uint)bVar4;
          }
          in_stack_00000020 = *unaff_s0;
          uVar2 = puVar8[6];
          *(undefined2 *)(unaff_s1 + 2) = puVar8[5];
          *(undefined2 *)(unaff_s1 + 4) = uVar2;
          uVar1 = puVar8[7];
          puVar8 = unaff_s0;
        } while ((uVar1 & 0x5000) != 0);
        streamUnit = (_StreamUnit *)&stack0x00000018;
        if ((uVar1 & 0x8000) == 0) break;
        pos = (_Position *)0x0;
        uVar6 = 0xffffff00;
        uVar7 = 0x280;
        uStack00000010 = 1;
        uStack00000014 = 4;
      }
      pos = (_Position *)0x0;
      if ((uVar1 & 0x2000) != 0) break;
      streamUnit = (_StreamUnit *)&stack0x00000018;
      uVar6 = 0x80;
      uVar7 = 0xfffffc00;
      uStack00000010 = 0;
      uStack00000014 = 0;
    }
  } while( true );
}



// decompiled code
// original method signature: 
// int /*$ra*/ PLANAPI_FindClosestNodePositionInUnit(struct _StreamUnit *streamUnit /*$a0*/, struct _Position *target /*$s3*/, struct _Position *pos /*$fp*/, int offset /*stack 12*/, int max /*stack 16*/, int type /*stack 20*/, int distanceCheck /*stack 24*/)
 // line 806, offset 0x80098990
	/* begin block 1 */
		// Start line: 807
		// Start offset: 0x80098990
		// Variables:
	// 		struct Level *level; // $v0
	// 		int numPlanMkrs; // $s0
	// 		struct _PlanMkr *planMkr; // $s1
	// 		struct _Position *ptr; // $s4
	// 		int dist; // $v1
	// 		int min_dist; // $s5
	// 		int chk; // $s7
	// 		int res; // $s6
	// 		int i; // $s2

		/* begin block 1.1 */
			// Start line: 846
			// Start offset: 0x80098AC8
			// Variables:
		// 		short _x1; // $v0
		// 		short _y1; // $v1
		// 		short _z1; // $a0
		/* end block 1.1 */
		// End offset: 0x80098AE0
		// End Line: 846
	/* end block 1 */
	// End offset: 0x80098AE0
	// End Line: 849

	/* begin block 2 */
		// Start line: 1749
	/* end block 2 */
	// End Line: 1750

int PLANAPI_FindClosestNodePositionInUnit
              (_StreamUnit *streamUnit,_Position *target,_Position *pos,int offset,int max,int type,
              int distanceCheck)

{
  if (streamUnit == (_StreamUnit *)&DAT_00000014) {
    return 0x2000;
  }
  if (streamUnit != (_StreamUnit *)0x1c) {
    return 0;
  }
  return 0x4000;
}





