#include "THISDUST.H"
#include "GAMELOOP.H"


// autogenerated function stub: 
// void /*$ra*/ GAMELOOP_AllocStaticMemory()
void GAMELOOP_AllocStaticMemory()
{ // line 143, offset 0x8002d7c8
	/* begin block 1 */
		// Start line: 286
	/* end block 1 */
	// End Line: 287

}


// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_InitGameTracker()
 // line 189, offset 0x8002d8b8
	/* begin block 1 */
		// Start line: 190
		// Start offset: 0x8002D8B8

		/* begin block 1.1 */
			// Start line: 190
			// Start offset: 0x8002D8B8
			// Variables:
		// 		int i; // $t4
		/* end block 1.1 */
		// End offset: 0x8002D990
		// End Line: 264
	/* end block 1 */
	// End offset: 0x8002D990
	// End Line: 270

	/* begin block 2 */
		// Start line: 412
	/* end block 2 */
	// End Line: 413

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GAMELOOP_InitGameTracker(void)

{
  _VertexPool *in_v0;
  int in_v1;
  undefined4 in_a0;
  undefined4 in_a1;
  undefined4 in_t2;
  int in_t3;
  int in_t4;
  
  gameTrackerX.GlobalObjects._0_2_ = 0;
  gameTrackerX.controlData[1][2]._0_2_ = SUB42(in_v0,0);
  loadStatus.changeDir = in_v1;
  draw[1]._24_4_ = in_t2;
  clearRect[1]._8_4_ = in_a0;
  clearRect[1]._12_4_ = in_a1;
  gameTrackerX.vertexPool = in_v0;
  gameTrackerX.controlData[1][1] = (long)in_v0;
  do {
    in_t4 = in_t4 + 1;
    *(undefined2 *)(in_t3 + loadStatus.endLoadTime + 0x14) = 0;
    in_t3 = in_t3 + 0x24;
  } while (in_t4 < 0x30);
  loadStatus.decompressLen._0_2_ = 1000;
  FUN_8003dd60();
  FUN_80060cd4();
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_SystemInit(struct GameTracker *gameTracker /*$a0*/)
 // line 285, offset 0x8002d9b8
	/* begin block 1 */
		// Start line: 804
	/* end block 1 */
	// End Line: 805

void GAMELOOP_SystemInit(GameTracker *gameTracker)

{
  int iVar1;
  int iVar2;
  
  iVar2 = (uint)(gameTrackerX.controlCommand[0][4] * (int)gameTrackerX.primPool) / 60000 + 0x2d0;
  iVar1 = iVar2 / 0x3c;
  gameTrackerX.instancePool._2_2_ =
       (short)iVar1 * 0x28 +
       ((short)(iVar1 / 6 + (iVar1 >> 0x1f) >> 2) - (short)(iVar1 >> 0x1f)) * -0x960 + (short)iVar2;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_ResetGameStates()
 // line 298, offset 0x8002d9f0
	/* begin block 1 */
		// Start line: 830
	/* end block 1 */
	// End Line: 831

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GAMELOOP_ResetGameStates(void)

{
  int in_v0;
  int iVar1;
  int in_a1;
  
  iVar1 = ((int)((ulonglong)((longlong)in_a1 * (longlong)in_v0) >> 0x20) + in_a1 >> 5) -
          (in_a1 >> 0x1f);
  gameTrackerX.instancePool._2_2_ =
       (short)iVar1 * 0x28 +
       ((short)(iVar1 / 6 + (iVar1 >> 0x1f) >> 2) - (short)(iVar1 >> 0x1f)) * -0x960 + (short)in_a1;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_ClearGameTracker()
 // line 304, offset 0x8002da10
	/* begin block 1 */
		// Start line: 842
	/* end block 1 */
	// End Line: 843

	/* begin block 2 */
		// Start line: 853
	/* end block 2 */
	// End Line: 854

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GAMELOOP_ClearGameTracker(void)

{
  int in_v1;
  int in_a0;
  short in_a1;
  
  gameTrackerX.instancePool._2_2_ =
       (short)in_a0 * 0x28 +
       ((short)(int)((longlong)in_a0 * (longlong)in_v1 >> 0x22) - (short)(in_a0 >> 0x1f)) * -0x960 +
       in_a1;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_CalcGameTime()
 // line 334, offset 0x8002da58
	/* begin block 1 */
		// Start line: 336
		// Start offset: 0x8002DA58
		// Variables:
	// 		long time; // $a1
	/* end block 1 */
	// End offset: 0x8002DA58
	// End Line: 340

	/* begin block 2 */
		// Start line: 905
	/* end block 2 */
	// End Line: 906

	/* begin block 3 */
		// Start line: 918
	/* end block 3 */
	// End Line: 919

	/* begin block 4 */
		// Start line: 919
	/* end block 4 */
	// End Line: 920

	/* begin block 5 */
		// Start line: 923
	/* end block 5 */
	// End Line: 924

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GAMELOOP_CalcGameTime(void)

{
  short in_v1;
  short in_a1;
  
  gameTrackerX.instancePool._2_2_ = in_v1 + in_a1;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_SetGameTime(long timeOfDay /*$a1*/)
 // line 345, offset 0x8002db04
	/* begin block 1 */
		// Start line: 346
		// Start offset: 0x8002DB04
		// Variables:
	// 		long tim; // $v1
	/* end block 1 */
	// End offset: 0x8002DB5C
	// End Line: 352

	/* begin block 2 */
		// Start line: 942
	/* end block 2 */
	// End Line: 943

void GAMELOOP_SetGameTime(long timeOfDay)

{
  int in_v1;
  
  if (in_v1 - 0x259U < 99) {
    return;
  }
  if ((1099 < in_v1 - 700U) && (99 < in_v1 - 0x708U)) {
    return;
  }
  return;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GAMELOOP_GetTimeOfDay()
 // line 362, offset 0x8002db98
	/* begin block 1 */
		// Start line: 364
		// Start offset: 0x8002DB98
		// Variables:
	// 		int timeOfDay; // $v1
	/* end block 1 */
	// End offset: 0x8002DBDC
	// End Line: 389

	/* begin block 2 */
		// Start line: 979
	/* end block 2 */
	// End Line: 980

	/* begin block 3 */
		// Start line: 980
	/* end block 3 */
	// End Line: 981

	/* begin block 4 */
		// Start line: 982
	/* end block 4 */
	// End Line: 983

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GAMELOOP_GetTimeOfDay(void)

{
  uint in_v0;
  int iVar1;
  uint in_v1;
  
  if ((in_v0 & in_v1) != 0) {
    FUN_800b773c();
  }
  iVar1 = FUN_8005fd78();
  return iVar1;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GAMELOOP_GetTimeOfDayIdx(int timeOfDay /*$a0*/)
 // line 391, offset 0x8002dbe4
	/* begin block 1 */
		// Start line: 1047
	/* end block 1 */
	// End Line: 1048

	/* begin block 2 */
		// Start line: 1049
	/* end block 2 */
	// End Line: 1050

int GAMELOOP_GetTimeOfDayIdx(int timeOfDay)

{
  short sVar1;
  int in_v0;
  int iVar2;
  int iVar3;
  int iVar4;
  int *piVar5;
  short *psVar6;
  short **ppsVar7;
  char *bigFileName;
  char *voiceFileName;
  char *unaff_s2;
  int unaff_s3;
  int unaff_s4;
  short sStack00000010;
  short sStack00000012;
  short sStack00000014;
  
  if (in_v0 != 0) {
    FUN_800585cc(0x800ce2b0);
  }
  voiceFileName = unaff_s2;
  FUN_800bd564(0x800ce2b0);
  bigFileName = unaff_s2;
  iVar2 = FUN_800593e8();
  if (iVar2 == 0) {
    unaff_s3 = 1;
    FUN_8006045c();
    voiceFileName = (char *)0x0;
    bigFileName = unaff_s2;
    iVar2 = FUN_8005a5fc();
  }
  if (*(short *)(iVar2 + 4) == 1) {
    FUN_8002c9bc();
    sVar1 = *(short *)(iVar2 + 4);
    while (sVar1 == 1) {
      FUN_8002db8c();
      sVar1 = *(short *)(iVar2 + 4);
    }
    if (unaff_s3 == 0) {
      FUN_8006045c();
      voiceFileName = (char *)0x0;
      iVar2 = FUN_8005a5fc();
      FUN_80058e20();
      bigFileName = unaff_s2;
    }
    STREAM_InitLoader(bigFileName,voiceFileName);
    FUN_8005a4c0();
    FUN_8005fb38();
    iVar3 = FUN_8002db8c();
    do {
      iVar4 = FUN_8002db8c();
      if (iVar4 == 0) break;
    } while (iVar3 + -1 <= iVar4);
  }
  else {
    FUN_8006045c();
    iVar2 = FUN_8005a5fc();
    FUN_80058e20();
    FUN_8005a4c0();
  }
  piVar5 = *(int **)(iVar2 + 8);
  iVar3 = piVar5[0x30];
  if (iVar3 != 0) {
    if (*(int *)(unaff_s4 + 0x2c) != 0) {
      *(ushort *)(iVar3 + 6) = *(ushort *)(iVar3 + 6) | 1;
      FUN_8001e174(*(undefined4 *)(unaff_s4 + 0x2c),*(int *)(*(int *)(iVar2 + 8) + 0xc0) + 8,0);
      FUN_80060744(*(undefined4 *)(*(int *)(iVar2 + 8) + 0xc0));
    }
    piVar5 = *(int **)(iVar2 + 8);
  }
  ppsVar7 = *(short ***)(*piVar5 + 0x48);
  psVar6 = *ppsVar7;
  sStack00000010 = -(*psVar6 + *(short *)(ppsVar7 + 3));
  sStack00000012 = -(psVar6[1] + *(short *)((int)ppsVar7 + 0xe));
  sStack00000014 = -(psVar6[2] + *(short *)(ppsVar7 + 4));
  FUN_8005b490(iVar2);
  return iVar2;
}



// decompiled code
// original method signature: 
// int /*$ra*/ GAMELOOP_WaitForLoad()
 // line 819, offset 0x8002dc28
	/* begin block 1 */
		// Start line: 1505
	/* end block 1 */
	// End Line: 1506

	/* begin block 2 */
		// Start line: 1913
	/* end block 2 */
	// End Line: 1914

/* WARNING: Unknown calling convention yet parameter storage is locked */

int GAMELOOP_WaitForLoad(void)

{
  short sVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  int *piVar5;
  short *psVar6;
  short **ppsVar7;
  char *bigFileName;
  char *voiceFileName;
  char *unaff_s2;
  int unaff_s3;
  int unaff_s4;
  short sStack00000010;
  short sStack00000012;
  short sStack00000014;
  
  voiceFileName = (char *)0x0;
  bigFileName = unaff_s2;
  iVar2 = FUN_8005a5fc();
  if (*(short *)(iVar2 + 4) == 1) {
    FUN_8002c9bc();
    sVar1 = *(short *)(iVar2 + 4);
    while (sVar1 == 1) {
      FUN_8002db8c();
      sVar1 = *(short *)(iVar2 + 4);
    }
    if (unaff_s3 == 0) {
      FUN_8006045c();
      voiceFileName = (char *)0x0;
      iVar2 = FUN_8005a5fc();
      FUN_80058e20();
      bigFileName = unaff_s2;
    }
    STREAM_InitLoader(bigFileName,voiceFileName);
    FUN_8005a4c0();
    FUN_8005fb38();
    iVar3 = FUN_8002db8c();
    do {
      iVar4 = FUN_8002db8c();
      if (iVar4 == 0) break;
    } while (iVar3 + -1 <= iVar4);
  }
  else {
    FUN_8006045c();
    iVar2 = FUN_8005a5fc();
    FUN_80058e20();
    FUN_8005a4c0();
  }
  piVar5 = *(int **)(iVar2 + 8);
  iVar3 = piVar5[0x30];
  if (iVar3 != 0) {
    if (*(int *)(unaff_s4 + 0x2c) != 0) {
      *(ushort *)(iVar3 + 6) = *(ushort *)(iVar3 + 6) | 1;
      FUN_8001e174(*(undefined4 *)(unaff_s4 + 0x2c),*(int *)(*(int *)(iVar2 + 8) + 0xc0) + 8,0);
      FUN_80060744(*(undefined4 *)(*(int *)(iVar2 + 8) + 0xc0));
    }
    piVar5 = *(int **)(iVar2 + 8);
  }
  ppsVar7 = *(short ***)(*piVar5 + 0x48);
  psVar6 = *ppsVar7;
  sStack00000010 = -(*psVar6 + *(short *)(ppsVar7 + 3));
  sStack00000012 = -(psVar6[1] + *(short *)((int)ppsVar7 + 0xe));
  sStack00000014 = -(psVar6[2] + *(short *)(ppsVar7 + 4));
  FUN_8005b490(iVar2);
  return iVar2;
}



// decompiled code
// original method signature: 
// struct _StreamUnit * /*$ra*/ LoadLevels(char *baseAreaName /*$s2*/, struct GameTracker *gameTracker /*$s4*/)
 // line 836, offset 0x8002dc60
	/* begin block 1 */
		// Start line: 837
		// Start offset: 0x8002DC60
		// Variables:
	// 		struct _SVector offset; // stack offset -32
	// 		struct _StreamUnit *streamUnit; // $s0
	// 		static char oldArea[16]; // offset 0xc
	// 		int cd; // $s3

		/* begin block 1.1 */
			// Start line: 862
			// Start offset: 0x8002DCEC
			// Variables:
		// 		int num; // $v0
		// 		int waitFor; // $s1
		/* end block 1.1 */
		// End offset: 0x8002DD88
		// End Line: 897

		/* begin block 1.2 */
			// Start line: 928
			// Start offset: 0x8002DE24
			// Variables:
		// 		short _x0; // $a2
		// 		short _y0; // $a3
		// 		short _z0; // $v0
		// 		short _x1; // $v1
		// 		short _y1; // $t1
		// 		short _z1; // $t0
		// 		struct _SVector *_v; // $a1
		// 		struct _Position *_v0; // $v0
		// 		struct _Position *_v1; // $t0
		/* end block 1.2 */
		// End offset: 0x8002DE24
		// End Line: 928
	/* end block 1 */
	// End offset: 0x8002DE24
	// End Line: 928

	/* begin block 2 */
		// Start line: 1947
	/* end block 2 */
	// End Line: 1948

	/* begin block 3 */
		// Start line: 1953
	/* end block 3 */
	// End Line: 1954

_StreamUnit * LoadLevels(char *baseAreaName,GameTracker *gameTracker)

{
  int in_v0;
  int iVar1;
  int iVar2;
  Level *pLVar3;
  _BSPNode *p_Var4;
  _MultiSignal *p_Var5;
  BSPTree *pBVar6;
  _StreamUnit *unaff_s0;
  int unaff_s1;
  char *unaff_s2;
  int unaff_s3;
  int unaff_s4;
  short sStack00000010;
  short sStack00000012;
  short sStack00000014;
  
  if (in_v0 == unaff_s1) {
    do {
      FUN_8002db8c();
    } while (unaff_s0->used == 1);
  }
  if (unaff_s3 == 0) {
    FUN_8006045c();
    gameTracker = (GameTracker *)0x0;
    unaff_s0 = (_StreamUnit *)FUN_8005a5fc();
    FUN_80058e20();
    baseAreaName = unaff_s2;
  }
  STREAM_InitLoader(baseAreaName,(char *)gameTracker);
  FUN_8005a4c0();
  FUN_8005fb38();
  iVar1 = FUN_8002db8c();
  do {
    iVar2 = FUN_8002db8c();
    if (iVar2 == 0) break;
  } while (iVar1 + -1 <= iVar2);
  pLVar3 = unaff_s0->level;
  p_Var5 = pLVar3->startUnitMainSignal;
  if (p_Var5 != (_MultiSignal *)0x0) {
    if (*(int *)(unaff_s4 + 0x2c) != 0) {
      p_Var5->flags = p_Var5->flags | 1;
      FUN_8001e174(*(undefined4 *)(unaff_s4 + 0x2c),unaff_s0->level->startUnitMainSignal->signalList
                   ,0);
      FUN_80060744(unaff_s0->level->startUnitMainSignal);
    }
    pLVar3 = unaff_s0->level;
  }
  pBVar6 = pLVar3->terrain->BSPTreeArray;
  p_Var4 = pBVar6->bspRoot;
  sStack00000010 = -((p_Var4->sphere).position.x + (pBVar6->globalOffset).x);
  sStack00000012 = -((p_Var4->sphere).position.y + (pBVar6->globalOffset).y);
  sStack00000014 = -((p_Var4->sphere).position.z + (pBVar6->globalOffset).z);
  FUN_8005b490(unaff_s0);
  return unaff_s0;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_InitStandardObjects()
 // line 937, offset 0x8002debc
	/* begin block 1 */
		// Start line: 938
		// Start offset: 0x8002DEBC
		// Variables:
	// 		static char (*sobjects[10]); // offset 0x0
	// 		int i; // $s1
	/* end block 1 */
	// End offset: 0x8002DEFC
	// End Line: 953

	/* begin block 2 */
		// Start line: 2169
	/* end block 2 */
	// End Line: 2170

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GAMELOOP_InitStandardObjects(void)

{
  Object *pOVar1;
  short *psVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int unaff_s3;
  
  FUN_80098148(fontTracker.font_buffer[188]._0_4_);
  FUN_8009667c(fontTracker.font_buffer[187]._2_4_);
  FUN_80041eec(fontTracker.font_buffer[194]._0_4_);
  FUN_8005af04();
  FUN_8002a590();
  FUN_8002de20();
  psVar2 = (short *)FUN_8002dbc4();
  do {
    iVar3 = FUN_8005fd78();
    pOVar1 = _Normal_ARRAY_800c89d0[0]._4_4_;
  } while (iVar3 != 0);
  *(undefined4 *)(unaff_s3 + 0x1cc) = _Normal_ARRAY_800c89d0[4]._4_4_;
  iVar3 = *(int *)(psVar2 + 4);
  fontTracker.font_buffer[192].x = *(short *)(unaff_s3 + 0x178);
  fontsObject = pOVar1;
  iVar5 = 0;
  if (0 < *(int *)(iVar3 + 0x78)) {
    iVar4 = 0;
    do {
      iVar3 = FUN_80074604(*(int *)(iVar3 + 0x7c) + iVar4,&DAT_800ce554);
      if (iVar3 == 0) {
        FUN_80032a68(*(int *)(*(int *)(psVar2 + 4) + 0x7c) + iVar4,(int)*psVar2);
        break;
      }
      iVar3 = *(int *)(psVar2 + 4);
      iVar5 = iVar5 + 1;
      iVar4 = iVar4 + 0x4c;
    } while (iVar5 < *(int *)(iVar3 + 0x78));
  }
  *(undefined4 *)(*(int *)(unaff_s3 + 0x2c) + 0x24) =
       *(undefined4 *)(*(int *)(*(int *)(unaff_s3 + 0x2c) + 0x1c) + 0x1c);
  FUN_80015d94(&standardMenu,*(undefined4 *)(unaff_s3 + 0x2c));
  iVar3 = *(int *)(unaff_s3 + 0x2c);
  standardMenu.type._0_2_ = *(undefined2 *)(iVar3 + 0x5c);
  standardMenu.type._2_2_ = *(undefined2 *)(iVar3 + 0x5e);
  standardMenu.lower._0_2_ = *(undefined2 *)(iVar3 + 0x60);
  FUN_800bd414((uint)*(ushort *)(*(int *)(psVar2 + 4) + 0x46),
               (uint)*(ushort *)(*(int *)(psVar2 + 4) + 0x44),0x140);
  FUN_800bd7e4(0,0,0);
  loadStatus.currentQueueFile.retData2._0_1_ = *(undefined *)(*(int *)(psVar2 + 4) + 0x3c);
  loadStatus.currentQueueFile.retData2._1_1_ = *(undefined *)(*(int *)(psVar2 + 4) + 0x3d);
  loadStatus.currentQueueFile.retData2._2_1_ = *(undefined *)(*(int *)(psVar2 + 4) + 0x3e);
  loadStatus.cdWaitTime._0_1_ = *(undefined *)(*(int *)(psVar2 + 4) + 0x3c);
  loadStatus.cdWaitTime._1_1_ = *(undefined *)(*(int *)(psVar2 + 4) + 0x3d);
  loadStatus.cdWaitTime._2_1_ = *(undefined *)(*(int *)(psVar2 + 4) + 0x3e);
  *(undefined2 *)(unaff_s3 + 0xd0) = 10;
  *(undefined2 *)(unaff_s3 + 0x170) = 0;
  *(undefined2 *)(unaff_s3 + 0xcc) = 0x1e;
  *(undefined2 *)(unaff_s3 + 0xce) = 0x1e;
  iVar3 = *(int *)(*(int *)(psVar2 + 4) + 0x74);
  if (iVar3 != 0) {
    *(ushort *)(iVar3 + 6) = *(ushort *)(iVar3 + 6) | 1;
    FUN_8001e174(*(undefined4 *)(unaff_s3 + 0x2c),*(int *)(*(int *)(psVar2 + 4) + 0x74) + 8,0);
    FUN_80060744(*(undefined4 *)(*(int *)(psVar2 + 4) + 0x74));
  }
  *(undefined4 *)(unaff_s3 + 0x134) = 0;
  iVar3 = *(int *)(*(int *)(psVar2 + 4) + 0xc0);
  if ((iVar3 != 0) && (*(int *)(unaff_s3 + 0x2c) != 0)) {
    *(ushort *)(iVar3 + 6) = *(ushort *)(iVar3 + 6) | 1;
    FUN_8001e174(*(undefined4 *)(unaff_s3 + 0x2c),*(int *)(*(int *)(psVar2 + 4) + 0xc0) + 8,0);
    FUN_80060744(*(undefined4 *)(*(int *)(psVar2 + 4) + 0xc0));
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_LevelLoadAndInit(char *baseAreaName /*$s0*/, struct GameTracker *gameTracker /*$s3*/)
 // line 956, offset 0x8002df10
	/* begin block 1 */
		// Start line: 957
		// Start offset: 0x8002DF10
		// Variables:
	// 		long i; // $s1
	// 		struct _StreamUnit *streamUnit; // $s2

		/* begin block 1.1 */
			// Start line: 1035
			// Start offset: 0x8002E03C
			// Variables:
		// 		short _x1; // $v0
		// 		short _y1; // $a0
		// 		short _z1; // $v1
		// 		struct _Position *_v0; // $v0
		// 		struct _Position *_v1; // $v1
		/* end block 1.1 */
		// End offset: 0x8002E03C
		// End Line: 1035
	/* end block 1 */
	// End offset: 0x8002E204
	// End Line: 1140

	/* begin block 2 */
		// Start line: 2211
	/* end block 2 */
	// End Line: 2212

void GAMELOOP_LevelLoadAndInit(char *baseAreaName,GameTracker *gameTracker)

{
  Object *pOVar1;
  int in_v0;
  int iVar2;
  int iVar3;
  int iVar4;
  short *unaff_s2;
  int unaff_s3;
  
  while (pOVar1 = _Normal_ARRAY_800c89d0[0]._4_4_, in_v0 != 0) {
    in_v0 = FUN_8005fd78();
  }
  *(undefined4 *)(unaff_s3 + 0x1cc) = _Normal_ARRAY_800c89d0[4]._4_4_;
  iVar2 = *(int *)(unaff_s2 + 4);
  fontTracker.font_buffer[192].x = *(short *)(unaff_s3 + 0x178);
  fontsObject = pOVar1;
  iVar4 = 0;
  if (0 < *(int *)(iVar2 + 0x78)) {
    iVar3 = 0;
    do {
      iVar2 = FUN_80074604(*(int *)(iVar2 + 0x7c) + iVar3,&DAT_800ce554);
      if (iVar2 == 0) {
        FUN_80032a68(*(int *)(*(int *)(unaff_s2 + 4) + 0x7c) + iVar3,(int)*unaff_s2);
        break;
      }
      iVar2 = *(int *)(unaff_s2 + 4);
      iVar4 = iVar4 + 1;
      iVar3 = iVar3 + 0x4c;
    } while (iVar4 < *(int *)(iVar2 + 0x78));
  }
  *(undefined4 *)(*(int *)(unaff_s3 + 0x2c) + 0x24) =
       *(undefined4 *)(*(int *)(*(int *)(unaff_s3 + 0x2c) + 0x1c) + 0x1c);
  FUN_80015d94(&standardMenu,*(undefined4 *)(unaff_s3 + 0x2c));
  iVar2 = *(int *)(unaff_s3 + 0x2c);
  standardMenu.type._0_2_ = *(undefined2 *)(iVar2 + 0x5c);
  standardMenu.type._2_2_ = *(undefined2 *)(iVar2 + 0x5e);
  standardMenu.lower._0_2_ = *(undefined2 *)(iVar2 + 0x60);
  FUN_800bd414((uint)*(ushort *)(*(int *)(unaff_s2 + 4) + 0x46),
               (uint)*(ushort *)(*(int *)(unaff_s2 + 4) + 0x44),0x140);
  FUN_800bd7e4(0,0,0);
  loadStatus.currentQueueFile.retData2._0_1_ = *(undefined *)(*(int *)(unaff_s2 + 4) + 0x3c);
  loadStatus.currentQueueFile.retData2._1_1_ = *(undefined *)(*(int *)(unaff_s2 + 4) + 0x3d);
  loadStatus.currentQueueFile.retData2._2_1_ = *(undefined *)(*(int *)(unaff_s2 + 4) + 0x3e);
  loadStatus.cdWaitTime._0_1_ = *(undefined *)(*(int *)(unaff_s2 + 4) + 0x3c);
  loadStatus.cdWaitTime._1_1_ = *(undefined *)(*(int *)(unaff_s2 + 4) + 0x3d);
  loadStatus.cdWaitTime._2_1_ = *(undefined *)(*(int *)(unaff_s2 + 4) + 0x3e);
  *(undefined2 *)(unaff_s3 + 0xd0) = 10;
  *(undefined2 *)(unaff_s3 + 0x170) = 0;
  *(undefined2 *)(unaff_s3 + 0xcc) = 0x1e;
  *(undefined2 *)(unaff_s3 + 0xce) = 0x1e;
  iVar2 = *(int *)(*(int *)(unaff_s2 + 4) + 0x74);
  if (iVar2 != 0) {
    *(ushort *)(iVar2 + 6) = *(ushort *)(iVar2 + 6) | 1;
    FUN_8001e174(*(undefined4 *)(unaff_s3 + 0x2c),*(int *)(*(int *)(unaff_s2 + 4) + 0x74) + 8,0);
    FUN_80060744(*(undefined4 *)(*(int *)(unaff_s2 + 4) + 0x74));
  }
  *(undefined4 *)(unaff_s3 + 0x134) = 0;
  iVar2 = *(int *)(*(int *)(unaff_s2 + 4) + 0xc0);
  if ((iVar2 != 0) && (*(int *)(unaff_s3 + 0x2c) != 0)) {
    *(ushort *)(iVar2 + 6) = *(ushort *)(iVar2 + 6) | 1;
    FUN_8001e174(*(undefined4 *)(unaff_s3 + 0x2c),*(int *)(*(int *)(unaff_s2 + 4) + 0xc0) + 8,0);
    FUN_80060744(*(undefined4 *)(*(int *)(unaff_s2 + 4) + 0xc0));
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_StreamLevelLoadAndInit(char *baseAreaName /*$a0*/, struct GameTracker *gameTracker /*$a1*/, int toSignalNum /*$a2*/, int fromSignalNum /*$a3*/)
 // line 1143, offset 0x8002e220
	/* begin block 1 */
		// Start line: 1144
		// Start offset: 0x8002E220
	/* end block 1 */
	// End offset: 0x8002E220
	// End Line: 1144

	/* begin block 2 */
		// Start line: 2613
	/* end block 2 */
	// End Line: 2614

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void GAMELOOP_StreamLevelLoadAndInit
               (char *baseAreaName,GameTracker *gameTracker,int toSignalNum,int fromSignalNum)

{
  int iVar1;
  undefined4 uStack00000010;
  undefined4 uStack00000014;
  undefined4 uStack00000018;
  int iStack00000020;
  undefined4 uStack0000002c;
  
  uStack00000010 = 0xd2;
  uStack00000014 = 0;
  uStack00000018 = 0xf0;
  iStack00000020 = 0xf0;
  FUN_8002a818(0x800d0e94,0,0xd2,0x200);
  iVar1 = (int)(short)draw[0].dr_env.code[3];
  if (iVar1 < 1) {
    if (iVar1 < -1) {
      if ((short)draw[0].dr_env.code[4] == 10) {
        uStack00000010 = 0;
        uStack00000018 = 0x200;
        uStack00000014 = 0xf0;
        uStack0000002c = 2;
        iStack00000020 =
             (int)(short)((((int)draw[0].dr_env.code[3]._2_2_ + iVar1 + 2) * 0xff) /
                         (int)draw[0].dr_env.code[3]._2_2_);
        FUN_8002a8c0(0,0,0x200,0);
      }
      else {
        if ((short)draw[0].dr_env.code[4] == 0xb) {
          uStack00000010 = 0;
          uStack00000018 = 0x200;
          uStack0000002c = 2;
          uStack00000014 = 0x1e;
          iVar1 = (int)(short)((((int)draw[0].dr_env.code[3]._2_2_ + iVar1) * 0xff) /
                              (int)draw[0].dr_env.code[3]._2_2_);
          iStack00000020 = iVar1;
          FUN_8002a8c0(0,0,0x200,0);
          uStack00000010 = 0;
          uStack00000014 = 0xf0;
          uStack00000018 = 0x200;
          uStack0000002c = 2;
          iStack00000020 = iVar1;
          FUN_8002a8c0(0,0xd2,0x200,0xd2);
          if ((short)draw[0].dr_env.code[3] == -2) {
            GlobalSave->flags = GlobalSave->flags | 1;
          }
        }
      }
      if (gameTrackerX.controlData[0][4] != 0) {
        draw[0].dr_env.code[3]._0_2_ = (short)draw[0].dr_env.code[3] + 1;
      }
    }
    else {
      if (iVar1 == -1) {
        if ((short)draw[0].dr_env.code[4] == 0xb) {
          GlobalSave->flags = GlobalSave->flags | 1;
        }
        else {
          uStack00000010 = 0;
          uStack00000014 = 0;
          uStack00000018 = 0xf0;
          iStack00000020 = 0xf0;
          FUN_8002a818(0x800d0e94,0,0);
        }
      }
      else {
        uRam800cfd6e = 0x1000;
        _maxVelAccl_63 = 0x1000;
        uRam800cfd6a = 0x1000;
      }
    }
  }
  else {
    if ((short)draw[0].dr_env.code[4] == 10) {
      uStack00000010 = 0;
      uStack00000018 = 0x200;
      uStack00000014 = 0xf0;
      uStack0000002c = 2;
      iStack00000020 = (int)(short)((iVar1 * 0xff) / (int)draw[0].dr_env.code[3]._2_2_);
      FUN_8002a8c0(0,0,0x200,0);
    }
    else {
      if ((short)draw[0].dr_env.code[4] == 0xb) {
        uStack00000010 = 0;
        uStack00000018 = 0x200;
        uStack0000002c = 2;
        uStack00000014 = 0x1e;
        iVar1 = (int)(short)((iVar1 * 0xff) / (int)draw[0].dr_env.code[3]._2_2_);
        iStack00000020 = iVar1;
        FUN_8002a8c0(0,0,0x200,0);
        uStack00000010 = 0;
        uStack00000014 = 0xf0;
        uStack00000018 = 0x200;
        uStack0000002c = 2;
        iStack00000020 = iVar1;
        FUN_8002a8c0(0,0xd2,0x200,0xd2);
        GlobalSave->flags = GlobalSave->flags & 0xfffe;
      }
    }
    if (gameTrackerX.controlData[0][4] != 0) {
      draw[0].dr_env.code[3]._0_2_ = (short)draw[0].dr_env.code[3] + -1;
    }
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_SetScreenWipe(int time /*$a0*/, int maxTime /*$a1*/, int type /*$a2*/)
 // line 1162, offset 0x8002e240
	/* begin block 1 */
		// Start line: 2651
	/* end block 1 */
	// End Line: 2652

	/* begin block 2 */
		// Start line: 2652
	/* end block 2 */
	// End Line: 2653

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void GAMELOOP_SetScreenWipe(int time,int maxTime,int type)

{
  int iVar1;
  undefined4 uStack00000010;
  undefined4 uStack00000014;
  undefined4 uStack00000018;
  int iStack00000020;
  undefined4 uStack0000002c;
  
  uStack00000014 = 0;
  uStack00000018 = 0xf0;
  iStack00000020 = 0xf0;
  FUN_8002a818();
  iVar1 = (int)(short)draw[0].dr_env.code[3];
  if (iVar1 < 1) {
    if (iVar1 < -1) {
      if ((short)draw[0].dr_env.code[4] == 10) {
        uStack00000010 = 0;
        uStack00000018 = 0x200;
        uStack00000014 = 0xf0;
        uStack0000002c = 2;
        iStack00000020 =
             (int)(short)((((int)draw[0].dr_env.code[3]._2_2_ + iVar1 + 2) * 0xff) /
                         (int)draw[0].dr_env.code[3]._2_2_);
        FUN_8002a8c0(0,0,0x200,0);
      }
      else {
        if ((short)draw[0].dr_env.code[4] == 0xb) {
          uStack00000010 = 0;
          uStack00000018 = 0x200;
          uStack0000002c = 2;
          uStack00000014 = 0x1e;
          iVar1 = (int)(short)((((int)draw[0].dr_env.code[3]._2_2_ + iVar1) * 0xff) /
                              (int)draw[0].dr_env.code[3]._2_2_);
          iStack00000020 = iVar1;
          FUN_8002a8c0(0,0,0x200,0);
          uStack00000010 = 0;
          uStack00000014 = 0xf0;
          uStack00000018 = 0x200;
          uStack0000002c = 2;
          iStack00000020 = iVar1;
          FUN_8002a8c0(0,0xd2,0x200,0xd2);
          if ((short)draw[0].dr_env.code[3] == -2) {
            GlobalSave->flags = GlobalSave->flags | 1;
          }
        }
      }
      if (gameTrackerX.controlData[0][4] != 0) {
        draw[0].dr_env.code[3]._0_2_ = (short)draw[0].dr_env.code[3] + 1;
      }
    }
    else {
      if (iVar1 == -1) {
        if ((short)draw[0].dr_env.code[4] == 0xb) {
          GlobalSave->flags = GlobalSave->flags | 1;
        }
        else {
          uStack00000010 = 0;
          uStack00000014 = 0;
          uStack00000018 = 0xf0;
          iStack00000020 = 0xf0;
          FUN_8002a818(0x800d0e94,0,0);
        }
      }
      else {
        uRam800cfd6e = 0x1000;
        _maxVelAccl_63 = 0x1000;
        uRam800cfd6a = 0x1000;
      }
    }
  }
  else {
    if ((short)draw[0].dr_env.code[4] == 10) {
      uStack00000010 = 0;
      uStack00000018 = 0x200;
      uStack00000014 = 0xf0;
      uStack0000002c = 2;
      iStack00000020 = (int)(short)((iVar1 * 0xff) / (int)draw[0].dr_env.code[3]._2_2_);
      FUN_8002a8c0(0,0,0x200,0);
    }
    else {
      if ((short)draw[0].dr_env.code[4] == 0xb) {
        uStack00000010 = 0;
        uStack00000018 = 0x200;
        uStack0000002c = 2;
        uStack00000014 = 0x1e;
        iVar1 = (int)(short)((iVar1 * 0xff) / (int)draw[0].dr_env.code[3]._2_2_);
        iStack00000020 = iVar1;
        FUN_8002a8c0(0,0,0x200,0);
        uStack00000010 = 0;
        uStack00000014 = 0xf0;
        uStack00000018 = 0x200;
        uStack0000002c = 2;
        iStack00000020 = iVar1;
        FUN_8002a8c0(0,0xd2,0x200,0xd2);
        GlobalSave->flags = GlobalSave->flags & 0xfffe;
      }
    }
    if (gameTrackerX.controlData[0][4] != 0) {
      draw[0].dr_env.code[3]._0_2_ = (short)draw[0].dr_env.code[3] + -1;
    }
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_HandleScreenWipes(unsigned long **drawot /*$s4*/)
 // line 1170, offset 0x8002e254
	/* begin block 1 */
		// Start line: 1171
		// Start offset: 0x8002E254
		// Variables:
	// 		long temp; // $s0
	// 		struct _PrimPool *primPool; // $s3
	/* end block 1 */
	// End offset: 0x8002E694
	// End Line: 1519

	/* begin block 2 */
		// Start line: 2667
	/* end block 2 */
	// End Line: 2668

	/* begin block 3 */
		// Start line: 2682
	/* end block 3 */
	// End Line: 2683

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void GAMELOOP_HandleScreenWipes(ulong **drawot)

{
  int iVar1;
  undefined4 uStack00000010;
  undefined4 uStack00000014;
  undefined4 uStack00000018;
  undefined4 uStack0000001c;
  int iStack00000020;
  undefined4 uStack0000002c;
  
  FUN_8002a818();
  iVar1 = (int)(short)draw[0].dr_env.code[3];
  if (iVar1 < 1) {
    if (iVar1 < -1) {
      if ((short)draw[0].dr_env.code[4] == 10) {
        uStack00000010 = 0;
        uStack00000018 = 0x200;
        uStack00000014 = 0xf0;
        uStack0000001c = 0xf0;
        uStack0000002c = 2;
        iStack00000020 =
             (int)(short)((((int)draw[0].dr_env.code[3]._2_2_ + iVar1 + 2) * 0xff) /
                         (int)draw[0].dr_env.code[3]._2_2_);
        FUN_8002a8c0(0,0,0x200,0);
      }
      else {
        if ((short)draw[0].dr_env.code[4] == 0xb) {
          uStack00000010 = 0;
          uStack00000018 = 0x200;
          uStack0000002c = 2;
          uStack00000014 = 0x1e;
          uStack0000001c = 0x1e;
          iVar1 = (int)(short)((((int)draw[0].dr_env.code[3]._2_2_ + iVar1) * 0xff) /
                              (int)draw[0].dr_env.code[3]._2_2_);
          iStack00000020 = iVar1;
          FUN_8002a8c0(0,0,0x200,0);
          uStack00000010 = 0;
          uStack00000014 = 0xf0;
          uStack00000018 = 0x200;
          uStack0000001c = 0xf0;
          uStack0000002c = 2;
          iStack00000020 = iVar1;
          FUN_8002a8c0(0,0xd2,0x200,0xd2);
          if ((short)draw[0].dr_env.code[3] == -2) {
            GlobalSave->flags = GlobalSave->flags | 1;
          }
        }
      }
      if (gameTrackerX.controlData[0][4] != 0) {
        draw[0].dr_env.code[3]._0_2_ = (short)draw[0].dr_env.code[3] + 1;
      }
    }
    else {
      if (iVar1 == -1) {
        if ((short)draw[0].dr_env.code[4] == 0xb) {
          GlobalSave->flags = GlobalSave->flags | 1;
        }
        else {
          uStack00000010 = 0;
          uStack00000014 = 0;
          uStack00000018 = 0xf0;
          uStack0000001c = 0x200;
          iStack00000020 = 0xf0;
          FUN_8002a818(0x800d0e94,0,0);
        }
      }
      else {
        uRam800cfd6e = 0x1000;
        _maxVelAccl_63 = 0x1000;
        uRam800cfd6a = 0x1000;
      }
    }
  }
  else {
    if ((short)draw[0].dr_env.code[4] == 10) {
      uStack00000010 = 0;
      uStack00000018 = 0x200;
      uStack00000014 = 0xf0;
      uStack0000001c = 0xf0;
      uStack0000002c = 2;
      iStack00000020 = (int)(short)((iVar1 * 0xff) / (int)draw[0].dr_env.code[3]._2_2_);
      FUN_8002a8c0(0,0,0x200,0);
    }
    else {
      if ((short)draw[0].dr_env.code[4] == 0xb) {
        uStack00000010 = 0;
        uStack00000018 = 0x200;
        uStack0000002c = 2;
        uStack00000014 = 0x1e;
        uStack0000001c = 0x1e;
        iVar1 = (int)(short)((iVar1 * 0xff) / (int)draw[0].dr_env.code[3]._2_2_);
        iStack00000020 = iVar1;
        FUN_8002a8c0(0,0,0x200,0);
        uStack00000010 = 0;
        uStack00000014 = 0xf0;
        uStack00000018 = 0x200;
        uStack0000001c = 0xf0;
        uStack0000002c = 2;
        iStack00000020 = iVar1;
        FUN_8002a8c0(0,0xd2,0x200,0xd2);
        GlobalSave->flags = GlobalSave->flags & 0xfffe;
      }
    }
    if (gameTrackerX.controlData[0][4] != 0) {
      draw[0].dr_env.code[3]._0_2_ = (short)draw[0].dr_env.code[3] + -1;
    }
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ UpdateFogSettings(struct _StreamUnit *currentUnit /*$s2*/, struct Level *level /*$s0*/)
 // line 1662, offset 0x8002e6b4
	/* begin block 1 */
		// Start line: 1663
		// Start offset: 0x8002E6B4
		// Variables:
	// 		int changed; // $a2
	// 		int setflag; // $s1
	// 		int FogFar; // $a1
	// 		int FogNear; // $a0
	/* end block 1 */
	// End offset: 0x8002E7C4
	// End Line: 1710

	/* begin block 2 */
		// Start line: 3668
	/* end block 2 */
	// End Line: 3669

void UpdateFogSettings(_StreamUnit *currentUnit,Level *level)

{
  uint in_v0;
  int unaff_s0;
  int unaff_s1;
  int unaff_s2;
  
  if ((int)level < (int)(in_v0 & 0xffff)) {
    unaff_s1 = 0;
  }
  else {
    *(undefined2 *)(unaff_s0 + 0x44) = (short)level;
  }
  FUN_80036bc8();
  if (unaff_s1 != 0) {
    *(undefined2 *)(unaff_s2 + 0x3a) = *(undefined2 *)(unaff_s0 + 0x46);
    *(undefined2 *)(unaff_s2 + 0x38) = *(undefined2 *)(unaff_s0 + 0x44);
  }
  return;
}



// decompiled code
// original method signature: 
// int /*$ra*/ CheckForNoBlend(struct _ColorType *Color /*$a0*/)
 // line 1712, offset 0x8002e7dc
	/* begin block 1 */
		// Start line: 3779
	/* end block 1 */
	// End Line: 3780

	/* begin block 2 */
		// Start line: 3780
	/* end block 2 */
	// End Line: 3781

int CheckForNoBlend(_ColorType *Color)

{
  bool bVar1;
  int in_v0;
  uint uVar2;
  int iVar3;
  uint *unaff_s0;
  uint *unaff_s1;
  
  uVar2 = (uint)(in_v0 < 5);
  if (in_v0 < 5) {
    iVar3 = (uint)*(byte *)((int)unaff_s1 + 1) - (uint)*(byte *)((int)unaff_s0 + 1);
    if (iVar3 < 0) {
      bVar1 = (int)((uint)*(byte *)((int)unaff_s0 + 1) - (uint)*(byte *)((int)unaff_s1 + 1)) < 5;
      uVar2 = (uint)bVar1;
      if (!bVar1) goto LAB_8002e864;
    }
    else {
      if (iVar3 >= 5) {
        *(undefined *)((int)unaff_s0 + 3) = 0;
        return (uint)(iVar3 < 5);
      }
    }
    iVar3 = (uint)*(byte *)((int)unaff_s1 + 2) - (uint)*(byte *)((int)unaff_s0 + 2);
    if (iVar3 < 0) {
      bVar1 = (int)((uint)*(byte *)((int)unaff_s0 + 2) - (uint)*(byte *)((int)unaff_s1 + 2)) < 5;
      uVar2 = (uint)bVar1;
      if (!bVar1) goto LAB_8002e864;
    }
    else {
      if (iVar3 >= 5) {
        *(undefined *)((int)unaff_s0 + 3) = 0;
        return (uint)(iVar3 < 5);
      }
    }
    uVar2 = *unaff_s1;
    *unaff_s0 = uVar2;
  }
LAB_8002e864:
  *(undefined *)((int)unaff_s0 + 3) = 0;
  return uVar2;
}



// decompiled code
// original method signature: 
// void /*$ra*/ BlendToColor(struct _ColorType *target /*$s1*/, struct _ColorType *current /*$a1*/, struct _ColorType *dest /*$s0*/)
 // line 1722, offset 0x8002e824
	/* begin block 1 */
		// Start line: 3799
	/* end block 1 */
	// End Line: 3800

void BlendToColor(_ColorType *target,_ColorType *current,_ColorType *dest)

{
  _ColorType *p_Var1;
  undefined4 *unaff_s0;
  undefined4 *unaff_s1;
  
  p_Var1 = (_ColorType *)((int)target - (uint)*(byte *)((int)unaff_s0 + 2));
  if ((int)p_Var1 < 0) {
    if (4 < (int)((uint)*(byte *)((int)unaff_s0 + 2) - (int)target)) goto LAB_8002e864;
  }
  else {
    if (4 < (int)p_Var1) {
      *(undefined *)((int)unaff_s0 + 3) = 0;
      return;
    }
  }
  *unaff_s0 = *unaff_s1;
LAB_8002e864:
  *(undefined *)((int)unaff_s0 + 3) = 0;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ MainRenderLevel(struct _StreamUnit *currentUnit /*$s7*/, unsigned long **drawot /*$fp*/)
 // line 1739, offset 0x8002e918
	/* begin block 1 */
		// Start line: 1740
		// Start offset: 0x8002E918
		// Variables:
	// 		struct Level *level; // $s0
	// 		struct GameTracker *gameTracker; // $s5
	// 		struct _Terrain *terrain; // $s4
	// 		int curTree; // $s1
	// 		long BackColor; // stack offset -48
	// 		struct _Position cam_pos_save; // stack offset -96
	// 		struct MATRIX cam_mat_save; // stack offset -88
	// 		struct _Instance *saveLightInstance; // $s2

		/* begin block 1.1 */
			// Start line: 1792
			// Start offset: 0x8002E9E8
			// Variables:
		// 		int time; // $a2
		/* end block 1.1 */
		// End offset: 0x8002EA1C
		// End Line: 1798

		/* begin block 1.2 */
			// Start line: 1806
			// Start offset: 0x8002EA68
			// Variables:
		// 		int tod; // $v1
		/* end block 1.2 */
		// End offset: 0x8002EAE4
		// End Line: 1820

		/* begin block 1.3 */
			// Start line: 1898
			// Start offset: 0x8002EC00
			// Variables:
		// 		struct _SVector tmp; // stack offset -56
		// 		struct BSPTree *bsp; // $s0
		/* end block 1.3 */
		// End offset: 0x8002ECF8
		// End Line: 1955
	/* end block 1 */
	// End offset: 0x8002EDDC
	// End Line: 1975

	/* begin block 2 */
		// Start line: 3834
	/* end block 2 */
	// End Line: 3835

/* WARNING: This function may have set the stack pointer */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void MainRenderLevel(_StreamUnit *currentUnit,ulong **drawot)

{
  DEBUG_LINE_TYPE DVar1;
  long lVar2;
  undefined4 uVar3;
  ushort uVar4;
  int iVar5;
  uint uVar6;
  int unaff_s0;
  int iVar7;
  long lVar8;
  int iVar9;
  int unaff_s4;
  int unaff_s5;
  int *unaff_s7;
  undefined4 *unaff_s8;
  undefined auStackX0 [16];
  undefined4 *in_stack_00000010;
  int in_stack_00000014;
  DEBUG_LINE_TYPE DStack00000018;
  short sStack0000001a;
  short sStack0000001c;
  undefined4 uStack00000020;
  undefined4 uStack00000024;
  undefined4 uStack00000028;
  undefined4 uStack0000002c;
  undefined4 uStack00000030;
  undefined4 uStack00000034;
  undefined4 uStack00000038;
  undefined4 uStack0000003c;
  short in_stack_00000040;
  short in_stack_00000042;
  short in_stack_00000044;
  undefined4 in_stack_00000048;
  
  loadStatus.cdWaitTime._0_1_ = *(undefined *)(unaff_s0 + 0x3c);
  loadStatus.cdWaitTime._1_1_ = *(undefined *)(unaff_s0 + 0x3d);
  loadStatus.cdWaitTime._2_1_ = *(undefined *)(unaff_s0 + 0x3e);
  if ((int)(short)loadStatus.decompressLen == 1000) {
    if (loadStatus.decompressLen._2_2_ == 1) {
      in_stack_00000048 = *(undefined4 *)(unaff_s0 + 0x40);
    }
    else {
      in_stack_00000048 = *(undefined4 *)(unaff_s0 + 0x3c);
    }
  }
  else {
    iVar5 = ((int)(short)loadStatus.decompressLen << 0xc) / 1000;
    if (loadStatus.decompressLen._2_2_ == 1) {
      iVar5 = 0x1000 - iVar5;
    }
    in_stack_00000010 = &stack0x00000048;
    FUN_800bd394(unaff_s0 + 0x40,unaff_s0 + 0x3c,iVar5,0x1000 - iVar5);
  }
  FUN_8002e788(&stack0x00000048,unaff_s7 + 0xc,unaff_s7 + 0xc);
  _depthQBackColor = unaff_s7[0xc];
  iVar5 = FUN_8002dafc();
  if ((((iVar5 != 600) && (iVar5 != 0x708)) || ((*(uint *)(unaff_s0 + 0xcc) & 2) == 0)) &&
     ((short)loadStatus.decompressLen == 1000)) {
    _depthQBackColor = _depthQBackColor & 0xfff8f8f8 | 0x40404;
  }
  _depthQFogStart = (uint)*(ushort *)(unaff_s0 + 0x46);
  _depthQFogFar = (uint)*(ushort *)(unaff_s0 + 0x44);
  iVar5 = FUN_8002e740(&depthQBackColor);
  _depthQBlendStart = 0xffff;
  if (iVar5 == 0) {
    _depthQBlendStart = _depthQFogStart;
  }
  loadStatus.currentQueueFile.retData2._0_1_ = depthQBackColor;
  loadStatus.currentQueueFile.retData2._1_1_ = ram0x800ce185;
  loadStatus.currentQueueFile.retData2._2_1_ = uRam800ce186;
  loadStatus.cdWaitTime._0_1_ = depthQBackColor;
  loadStatus.cdWaitTime._1_1_ = ram0x800ce185;
  loadStatus.cdWaitTime._2_1_ = uRam800ce186;
  FUN_8003bc54(*(undefined4 *)(unaff_s4 + 0x28),*(undefined4 *)(unaff_s5 + 300),
               *(undefined4 *)(unaff_s5 + 0x40));
  FUN_8003bc54(*(undefined4 *)(unaff_s0 + 0x80),*(undefined4 *)(unaff_s5 + 300),
               *(undefined4 *)(unaff_s5 + 0x40));
  *(undefined4 *)(fontTracker.font_buffer._1120_4_ + 0x478) = 0;
  FUN_8003b0b8();
  DStack00000018 = standardMenu.type;
  sStack0000001c = (short)standardMenu.lower;
  uStack00000020 = *(undefined4 *)level2SelectMenu.type;
  uStack00000024 = *(undefined4 *)(level2SelectMenu.type + DEBUG_LINE_TYPE_MENU);
  uStack00000028 = *(undefined4 *)(level2SelectMenu.type + 8);
  uStack0000002c = *(undefined4 *)(level2SelectMenu.type + 0xc);
  uStack00000030 = *(undefined4 *)(level2SelectMenu.type + 0x10);
  uStack00000034 = *(undefined4 *)(level2SelectMenu.type + 0x14);
  uStack00000038 = *(undefined4 *)(level2SelectMenu.type + 0x18);
  uStack0000003c = *(undefined4 *)(level2SelectMenu.type + 0x1c);
  iVar5 = 0;
  if (0 < *(int *)(unaff_s4 + 0x44)) {
    iVar9 = 0;
    do {
      lVar2 = loadStatus.checksum;
      iVar7 = *(int *)(unaff_s4 + 0x48) + iVar9;
      if ((-1 < *(short *)(iVar7 + 0x1a)) && ((*(ushort *)(iVar7 + 0x12) & 1) == 0)) {
        lVar8 = 0;
        if ((*(ushort *)(iVar7 + 0x12) & 0x40) != 0) {
          loadStatus.checksum = 0;
          lVar8 = lVar2;
        }
        uVar6 = (DStack00000018 & 0xffff) - (uint)*(ushort *)(iVar7 + 0xc);
        in_stack_00000040 = -(short)uVar6;
        uVar4 = sStack0000001a - *(short *)(iVar7 + 0xe);
        standardMenu.type = uVar6 & 0xffff | (uint)uVar4 << 0x10;
        in_stack_00000042 = -uVar4;
        standardMenu.lower._0_2_ = sStack0000001c - *(short *)(iVar7 + 0x10);
        in_stack_00000044 = -(short)standardMenu.lower;
        FUN_800bcd5c(&stack0x00000020,&stack0x00000040,level2SelectMenu.type + 0x14);
        FUN_80079254(iVar7,&standardMenu,fontTracker.font_buffer[184]._0_4_);
        in_stack_00000014 = iVar7 + 0xc;
        in_stack_00000010 = unaff_s8;
        uVar3 = (**(code **)(unaff_s5 + 0x150))(fontTracker.font_buffer[184]._0_4_);
        *(undefined4 *)(*(int *)(unaff_s5 + 0x40) + 4) = uVar3;
        if ((*(ushort *)(iVar7 + 0x12) & 0x40) != 0) {
          loadStatus.checksum = lVar8;
        }
      }
      iVar5 = iVar5 + 1;
      iVar9 = iVar9 + 0x24;
    } while (iVar5 < *(int *)(unaff_s4 + 0x44));
  }
  DVar1 = level2SelectMenu.type;
  standardMenu.type = DStack00000018;
  standardMenu.lower._0_2_ = sStack0000001c;
  *(undefined4 *)level2SelectMenu.type = uStack00000020;
  *(undefined4 *)(DVar1 + DEBUG_LINE_TYPE_MENU) = uStack00000024;
  *(undefined4 *)(DVar1 + 8) = uStack00000028;
  *(undefined4 *)(DVar1 + 0xc) = uStack0000002c;
  *(undefined4 *)(DVar1 + 0x10) = uStack00000030;
  *(undefined4 *)(DVar1 + 0x14) = uStack00000034;
  *(undefined4 *)(DVar1 + 0x18) = uStack00000038;
  *(undefined4 *)(DVar1 + 0x1c) = uStack0000003c;
  FUN_8003d924();
  fontTracker.font_buffer[193]._2_4_ = (undefined *)register0x00000074;
  FUN_800448f0(fontTracker.font_buffer[194]._0_4_,0x800d0dcc,clearRect[1]._8_4_,
               level2SelectMenu.type);
  if (*(int *)(loadStatus.bigFile.searchDirID + 0x38) == *unaff_s7) {
    FUN_800448a4(loadStatus.changeDir,clearRect[1]._8_4_,level2SelectMenu.type);
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ StreamIntroInstancesForUnit(struct _StreamUnit *currentUnit /*$a1*/)
 // line 1982, offset 0x8002ee18
	/* begin block 1 */
		// Start line: 1983
		// Start offset: 0x8002EE18
	/* end block 1 */
	// End offset: 0x8002EE48
	// End Line: 1995

	/* begin block 2 */
		// Start line: 4500
	/* end block 2 */
	// End Line: 4501

/* WARNING: This function may have set the stack pointer */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void StreamIntroInstancesForUnit(_StreamUnit *currentUnit)

{
  DEBUG_LINE_TYPE DVar1;
  int iVar2;
  undefined4 uVar3;
  ushort uVar4;
  uint uVar5;
  int unaff_s0;
  int iVar6;
  int unaff_s1;
  int unaff_s2;
  int iVar7;
  undefined4 unaff_s6;
  int *unaff_s7;
  long unaff_s8;
  undefined auStackX0 [16];
  int in_stack_00000014;
  DEBUG_LINE_TYPE DStack00000018;
  short sStack0000001a;
  short sStack0000001c;
  undefined4 uStack00000020;
  undefined4 uStack00000024;
  undefined4 uStack00000028;
  undefined4 uStack0000002c;
  undefined4 uStack00000030;
  undefined4 uStack00000034;
  undefined4 uStack00000038;
  undefined4 uStack0000003c;
  short in_stack_00000040;
  short in_stack_00000042;
  short in_stack_00000044;
  
  _depthQFogFar = (uint)*(ushort *)(unaff_s1 + 0x44);
  _depthQFogStart = (uint)*(ushort *)(unaff_s1 + 0x46);
  _depthQBackColor = unaff_s0;
  unaff_s7[0xc] = unaff_s0;
  level2SelectMenu.lower = _depthQFogFar;
  iVar2 = FUN_8002e740(&depthQBackColor);
  _depthQBlendStart = 0xffff;
  if (iVar2 == 0) {
    _depthQBlendStart = _depthQFogStart;
  }
  FUN_800bd414(_depthQFogStart,_depthQFogFar,0x140);
  FUN_8003bc54(*(undefined4 *)(unaff_s2 + 0x28),draw[1].dr_env.code[4],loadStatus.changeDir);
  FUN_8003bc54(*(undefined4 *)(unaff_s1 + 0x80),draw[1].dr_env.code[4],loadStatus.changeDir);
  FUN_8003b0b8();
  DStack00000018 = standardMenu.type;
  sStack0000001c = (short)standardMenu.lower;
  uStack00000020 = *(undefined4 *)level2SelectMenu.type;
  uStack00000024 = *(undefined4 *)(level2SelectMenu.type + DEBUG_LINE_TYPE_MENU);
  uStack00000028 = *(undefined4 *)(level2SelectMenu.type + 8);
  uStack0000002c = *(undefined4 *)(level2SelectMenu.type + 0xc);
  uStack00000030 = *(undefined4 *)(level2SelectMenu.type + 0x10);
  uStack00000034 = *(undefined4 *)(level2SelectMenu.type + 0x14);
  uStack00000038 = *(undefined4 *)(level2SelectMenu.type + 0x18);
  uStack0000003c = *(undefined4 *)(level2SelectMenu.type + 0x1c);
  iVar2 = 0;
  if (0 < *(int *)(unaff_s2 + 0x44)) {
    iVar7 = 0;
    do {
      iVar6 = *(int *)(unaff_s2 + 0x48) + iVar7;
      if ((-1 < *(short *)(iVar6 + 0x1a)) && ((*(ushort *)(iVar6 + 0x12) & 1) == 0)) {
        uVar5 = (DStack00000018 & 0xffff) - (uint)*(ushort *)(iVar6 + 0xc);
        in_stack_00000040 = -(short)uVar5;
        uVar4 = sStack0000001a - *(short *)(iVar6 + 0xe);
        standardMenu.type = uVar5 & 0xffff | (uint)uVar4 << 0x10;
        in_stack_00000042 = -uVar4;
        standardMenu.lower._0_2_ = sStack0000001c - *(short *)(iVar6 + 0x10);
        in_stack_00000044 = -(short)standardMenu.lower;
        FUN_800bcd5c(&stack0x00000020,&stack0x00000040,level2SelectMenu.type + 0x14);
        FUN_80079254(iVar6,&standardMenu,fontTracker.font_buffer[184]._0_4_);
        in_stack_00000014 = iVar6 + 0xc;
        uVar3 = (*(code *)draw[1].dr_env.code[13])(fontTracker.font_buffer[184]._0_4_);
        *(undefined4 *)(loadStatus.changeDir + 4) = uVar3;
      }
      iVar2 = iVar2 + 1;
      iVar7 = iVar7 + 0x24;
    } while (iVar2 < *(int *)(unaff_s2 + 0x44));
  }
  DVar1 = level2SelectMenu.type;
  standardMenu.type = DStack00000018;
  standardMenu.lower._0_2_ = sStack0000001c;
  fontTracker.font_buffer[191]._2_4_ = 1;
  *(undefined4 *)level2SelectMenu.type = uStack00000020;
  *(undefined4 *)(DVar1 + DEBUG_LINE_TYPE_MENU) = uStack00000024;
  *(undefined4 *)(DVar1 + 8) = uStack00000028;
  *(undefined4 *)(DVar1 + 0xc) = uStack0000002c;
  *(undefined4 *)(DVar1 + 0x10) = uStack00000030;
  *(undefined4 *)(DVar1 + 0x14) = uStack00000034;
  *(undefined4 *)(DVar1 + 0x18) = uStack00000038;
  *(undefined4 *)(DVar1 + 0x1c) = uStack0000003c;
  FUN_8003d924();
  fontTracker.font_buffer[191]._2_4_ = 0;
  level2SelectMenu.lower = unaff_s8;
  if (*(int *)(loadStatus.bigFile.searchDirID + 0x38) == *unaff_s7) {
    level2SelectMenu.lower = unaff_s8;
    fontTracker.font_buffer._1156_4_ = unaff_s6;
    fontTracker.font_buffer[193]._2_4_ = (undefined *)register0x00000074;
    FUN_800448a4(loadStatus.changeDir,unaff_s6,level2SelectMenu.type);
  }
  return;
}



// decompiled code
// original method signature: 
// long /*$ra*/ StreamRenderLevel(struct _StreamUnit *currentUnit /*$s7*/, struct Level *mainLevel /*$a1*/, unsigned long **drawot /*$s6*/, long portalFogColor /*$s0*/)
 // line 1999, offset 0x8002ee58
	/* begin block 1 */
		// Start line: 2000
		// Start offset: 0x8002EE58
		// Variables:
	// 		struct GameTracker *gameTracker; // $s4
	// 		struct Level *level; // $s1
	// 		struct _Terrain *terrain; // $s2
	// 		int curTree; // $s1
	// 		int farplanesave; // $fp
	// 		struct _Position cam_pos_save; // stack offset -88
	// 		struct MATRIX cam_mat_save; // stack offset -80

		/* begin block 1.1 */
			// Start line: 2085
			// Start offset: 0x8002EFBC
			// Variables:
		// 		struct _SVector tmp; // stack offset -48
		// 		struct BSPTree *bsp; // $s0
		/* end block 1.1 */
		// End offset: 0x8002F088
		// End Line: 2133

		/* begin block 1.2 */
			// Start line: 2151
			// Start offset: 0x8002F134
		/* end block 1.2 */
		// End offset: 0x8002F168
		// End Line: 2161
	/* end block 1 */
	// End offset: 0x8002F168
	// End Line: 2163

	/* begin block 2 */
		// Start line: 4534
	/* end block 2 */
	// End Line: 4535

/* WARNING: This function may have set the stack pointer */
/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

long StreamRenderLevel(_StreamUnit *currentUnit,Level *mainLevel,ulong **drawot,long portalFogColor)

{
  DEBUG_LINE_TYPE DVar1;
  undefined4 in_v0;
  undefined4 uVar2;
  ushort uVar3;
  uint uVar4;
  int iVar5;
  int unaff_s1;
  int iVar6;
  int unaff_s2;
  int iVar7;
  int unaff_s4;
  undefined4 unaff_s6;
  int *unaff_s7;
  long unaff_s8;
  undefined auStackX0 [16];
  int in_stack_00000014;
  DEBUG_LINE_TYPE DStack00000018;
  short sStack0000001a;
  short sStack0000001c;
  undefined4 uStack00000020;
  undefined4 uStack00000024;
  undefined4 uStack00000028;
  undefined4 uStack0000002c;
  undefined4 uStack00000030;
  undefined4 uStack00000034;
  undefined4 uStack00000038;
  undefined4 uStack0000003c;
  short in_stack_00000040;
  short in_stack_00000042;
  short in_stack_00000044;
  
  _depthQBlendStart = in_v0;
  FUN_800bd414(_depthQFogStart,_depthQFogFar,0x140);
  FUN_8003bc54(*(undefined4 *)(unaff_s2 + 0x28),*(undefined4 *)(unaff_s4 + 300),
               *(undefined4 *)(unaff_s4 + 0x40));
  FUN_8003bc54(*(undefined4 *)(unaff_s1 + 0x80),*(undefined4 *)(unaff_s4 + 300),
               *(undefined4 *)(unaff_s4 + 0x40));
  FUN_8003b0b8();
  DStack00000018 = standardMenu.type;
  sStack0000001c = (short)standardMenu.lower;
  uStack00000020 = *(undefined4 *)level2SelectMenu.type;
  uStack00000024 = *(undefined4 *)(level2SelectMenu.type + DEBUG_LINE_TYPE_MENU);
  uStack00000028 = *(undefined4 *)(level2SelectMenu.type + 8);
  uStack0000002c = *(undefined4 *)(level2SelectMenu.type + 0xc);
  uStack00000030 = *(undefined4 *)(level2SelectMenu.type + 0x10);
  uStack00000034 = *(undefined4 *)(level2SelectMenu.type + 0x14);
  uStack00000038 = *(undefined4 *)(level2SelectMenu.type + 0x18);
  uStack0000003c = *(undefined4 *)(level2SelectMenu.type + 0x1c);
  iVar6 = 0;
  if (0 < *(int *)(unaff_s2 + 0x44)) {
    iVar7 = 0;
    do {
      iVar5 = *(int *)(unaff_s2 + 0x48) + iVar7;
      if ((-1 < *(short *)(iVar5 + 0x1a)) && ((*(ushort *)(iVar5 + 0x12) & 1) == 0)) {
        uVar4 = (DStack00000018 & 0xffff) - (uint)*(ushort *)(iVar5 + 0xc);
        in_stack_00000040 = -(short)uVar4;
        uVar3 = sStack0000001a - *(short *)(iVar5 + 0xe);
        standardMenu.type = uVar4 & 0xffff | (uint)uVar3 << 0x10;
        in_stack_00000042 = -uVar3;
        standardMenu.lower._0_2_ = sStack0000001c - *(short *)(iVar5 + 0x10);
        in_stack_00000044 = -(short)standardMenu.lower;
        FUN_800bcd5c(&stack0x00000020,&stack0x00000040,level2SelectMenu.type + 0x14);
        FUN_80079254(iVar5,&standardMenu,fontTracker.font_buffer[184]._0_4_);
        in_stack_00000014 = iVar5 + 0xc;
        uVar2 = (**(code **)(unaff_s4 + 0x150))(fontTracker.font_buffer[184]._0_4_);
        *(undefined4 *)(*(int *)(unaff_s4 + 0x40) + 4) = uVar2;
      }
      iVar6 = iVar6 + 1;
      iVar7 = iVar7 + 0x24;
    } while (iVar6 < *(int *)(unaff_s2 + 0x44));
  }
  DVar1 = level2SelectMenu.type;
  standardMenu.type = DStack00000018;
  standardMenu.lower._0_2_ = sStack0000001c;
  fontTracker.font_buffer[191]._2_4_ = 1;
  *(undefined4 *)level2SelectMenu.type = uStack00000020;
  *(undefined4 *)(DVar1 + DEBUG_LINE_TYPE_MENU) = uStack00000024;
  *(undefined4 *)(DVar1 + 8) = uStack00000028;
  *(undefined4 *)(DVar1 + 0xc) = uStack0000002c;
  *(undefined4 *)(DVar1 + 0x10) = uStack00000030;
  *(undefined4 *)(DVar1 + 0x14) = uStack00000034;
  *(undefined4 *)(DVar1 + 0x18) = uStack00000038;
  *(undefined4 *)(DVar1 + 0x1c) = uStack0000003c;
  FUN_8003d924();
  fontTracker.font_buffer[191]._2_4_ = 0;
  level2SelectMenu.lower = unaff_s8;
  if (*(int *)(loadStatus.bigFile.searchDirID + 0x38) == *unaff_s7) {
    level2SelectMenu.lower = unaff_s8;
    fontTracker.font_buffer._1156_4_ = unaff_s6;
    fontTracker.font_buffer[193]._2_4_ = (undefined *)register0x00000074;
    FUN_800448a4(loadStatus.changeDir,unaff_s6,level2SelectMenu.type);
  }
  return 0;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_FlipScreenAndDraw(struct GameTracker *gameTracker /*$s0*/, unsigned long **drawot /*$a1*/)
 // line 2187, offset 0x8002f1a0
	/* begin block 1 */
		// Start line: 5067
	/* end block 1 */
	// End Line: 5068

void GAMELOOP_FlipScreenAndDraw(GameTracker *gameTracker,ulong **drawot)

{
  int in_v0;
  int in_v1;
  int unaff_s0;
  
  *(int *)(unaff_s0 + 4) = in_v0 - in_v1;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_AddClearPrim(unsigned long **drawot /*$a3*/, int override /*$a1*/)
 // line 2219, offset 0x8002f254
	/* begin block 1 */
		// Start line: 2220
		// Start offset: 0x8002F254

		/* begin block 1.1 */
			// Start line: 2224
			// Start offset: 0x8002F270
			// Variables:
		// 		struct BLK_FILL *blkfill; // $a0
		/* end block 1.1 */
		// End offset: 0x8002F270
		// End Line: 2224

		/* begin block 1.2 */
			// Start line: 2240
			// Start offset: 0x8002F2DC
			// Variables:
		// 		struct BLK_FILL *blkfill; // $v1
		/* end block 1.2 */
		// End offset: 0x8002F2F4
		// End Line: 2242
	/* end block 1 */
	// End offset: 0x8002F2F4
	// End Line: 2243

	/* begin block 2 */
		// Start line: 5138
	/* end block 2 */
	// End Line: 5139

	/* begin block 3 */
		// Start line: 5140
	/* end block 3 */
	// End Line: 5141

void GAMELOOP_AddClearPrim(ulong **drawot,int override)

{
  int in_v0;
  int in_v1;
  
  *(undefined2 *)(in_v1 + 10) = *(undefined2 *)(in_v0 + 10);
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_SwitchTheDrawBuffer(unsigned long **drawot /*$a0*/)
 // line 2245, offset 0x8002f2fc
	/* begin block 1 */
		// Start line: 5209
	/* end block 1 */
	// End Line: 5210

void GAMELOOP_SwitchTheDrawBuffer(ulong **drawot)

{
  int iVar1;
  int iVar2;
  
  iVar1 = cwTransform2X.m._4_4_;
  if (wcTransform2X.m[2][0] == 5) {
    FUN_8005a130(theCamera.focusDistanceList[2][0]);
  }
  else {
    if ((cwTransform2X.m._4_4_ == loadStatus.bigFile.searchDirID) && (BmenuLines[2].textureW != 0))
    {
      iVar2 = FUN_80059398(DAT_800d0f6c);
      if (iVar2 == 0) {
        FUN_80059398(*(undefined4 *)(iVar1 + 0x38));
        return;
      }
    }
    else {
      FUN_80059398(*(undefined4 *)(cwTransform2X.m._4_4_ + 0x38));
    }
    FUN_800243a8(&standardMenu);
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_SetupRenderFunction(struct GameTracker *gameTracker /*$a0*/)
 // line 2277, offset 0x8002f37c
	/* begin block 1 */
		// Start line: 5274
	/* end block 1 */
	// End Line: 5275

	/* begin block 2 */
		// Start line: 5289
	/* end block 2 */
	// End Line: 5290

void GAMELOOP_SetupRenderFunction(GameTracker *gameTracker)

{
  int unaff_s1;
  
  FUN_80059398(*(undefined4 *)(unaff_s1 + 0x38));
  FUN_800243a8(&standardMenu);
  return;
}



// decompiled code
// original method signature: 
// struct _StreamUnit * /*$ra*/ GAMELOOP_GetMainRenderUnit()
 // line 2303, offset 0x8002f398
	/* begin block 1 */
		// Start line: 2304
		// Start offset: 0x8002F398
		// Variables:
	// 		struct _StreamUnit *streamUnit; // $s0

		/* begin block 1.1 */
			// Start line: 2315
			// Start offset: 0x8002F3C8
			// Variables:
		// 		struct _Instance *focusInstance; // $s1

			/* begin block 1.1.1 */
				// Start line: 2336
				// Start offset: 0x8002F428
				// Variables:
			// 		struct _StreamUnit *cameraUnit; // $v0
			/* end block 1.1.1 */
			// End offset: 0x8002F440
			// End Line: 2344
		/* end block 1.1 */
		// End offset: 0x8002F440
		// End Line: 2345
	/* end block 1 */
	// End offset: 0x8002F444
	// End Line: 2349

	/* begin block 2 */
		// Start line: 5326
	/* end block 2 */
	// End Line: 5327

/* WARNING: Unknown calling convention yet parameter storage is locked */

_StreamUnit * GAMELOOP_GetMainRenderUnit(void)

{
  _StreamUnit *in_v0;
  _StreamUnit *unaff_s0;
  
  if (in_v0 != (_StreamUnit *)0x0) {
    unaff_s0 = in_v0;
  }
  return unaff_s0;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_DisplayFrame(struct GameTracker *gameTracker /*stack 0*/)
 // line 2355, offset 0x8002f458
	/* begin block 1 */
		// Start line: 2356
		// Start offset: 0x8002F458
		// Variables:
	// 		unsigned long **drawot; // stack offset -64
	// 		struct Level *mainLevel; // stack offset -60
	// 		struct StreamUnitPortal *streamPortal; // stack offset -56
	// 		int numportals; // stack offset -52
	// 		int d; // $s6
	// 		struct _StreamUnit *mainStreamUnit; // $fp
	// 		void *savedNextPrim; // stack offset -48

		/* begin block 1.1 */
			// Start line: 2467
			// Start offset: 0x8002F6D0
			// Variables:
		// 		struct _StreamUnit *toStreamUnit; // $s2
		// 		long toStreamUnitID; // stack offset -44
		// 		struct StreamUnitPortal *streamPortal2; // $s4
		// 		int i; // $s5
		// 		int draw; // $s3
		// 		struct RECT cliprect; // stack offset -72

			/* begin block 1.1.1 */
				// Start line: 2508
				// Start offset: 0x8002F7B4
				// Variables:
			// 		int streamID; // $s0
			// 		struct _Instance *instance; // $v0
			/* end block 1.1.1 */
			// End offset: 0x8002F810
			// End Line: 2518
		/* end block 1.1 */
		// End offset: 0x8002F994
		// End Line: 2587
	/* end block 1 */
	// End offset: 0x8002FBF0
	// End Line: 2704

	/* begin block 2 */
		// Start line: 5433
	/* end block 2 */
	// End Line: 5434

void GAMELOOP_DisplayFrame(GameTracker *gameTracker)

{
  bool bVar1;
  short *psVar2;
  int iVar3;
  int *piVar4;
  int iVar5;
  uint uVar6;
  ulong uVar7;
  ulong **drawot;
  DVECTOR *pDVar8;
  int iVar9;
  int iVar10;
  int iVar11;
  int iVar12;
  short in_stack_00000018;
  short in_stack_0000001a;
  short in_stack_0000001c;
  short in_stack_0000001e;
  ulong **ot;
  int *piStack00000024;
  int *piStack00000028;
  int iStack0000002c;
  undefined4 in_stack_00000030;
  int in_stack_00000034;
  GameTracker *gameTracker_00;
  
  if (fontTracker.font_buffer[190]._0_4_ == 0) {
    *(int *)(loadStatus.changeDir + 4) = loadStatus.changeDir + 0xc;
  }
  else {
    *(int *)(loadStatus.changeDir + 4) = fontTracker.font_buffer[190]._0_4_;
  }
  drawot = (ulong **)&loadStatus.compControl;
  gameTrackerX.controlData[0][3] = 0;
  draw[1].dr_env.code[3] = draw[1].dr_env.code[3] + 1;
  FUN_8002f2e0();
  if (((GlobalSave->flags & 1U) == 0) &&
     (((gameTracker_00->wipeType != 0xb || (gameTracker_00->wipeTime == 0)) &&
      ((gameTracker_00->debugFlags2 & 0x800U) != 0)))) {
    drawot = (ulong **)loadStatus.changeDir;
    FUN_8004d560(loadStatus.changeDir,ot);
  }
  psVar2 = (short *)(int)fontTracker.font_buffer[189].y;
  if (psVar2 == (short *)0x0) {
    psVar2 = (short *)FUN_8007c4fc();
  }
  GAMELOOP_SwitchTheDrawBuffer(drawot);
  piStack00000024 = *(int **)(psVar2 + 4);
  if ((gameTracker_00->debugFlags & 4U) != 0) {
    FUN_8002d310(&_stacksize,piStack00000024[0x26]);
  }
  fontTracker.font_buffer[192].x = *psVar2;
  debugRazielMenu.upper = 0x140;
  debugRazielMenu.lower = 0;
  debugRazielMenu.text = (char *)0x0;
  debugRazielMenu.var_address = (long *)0xf0;
  FUN_80014aa8(&standardMenu);
  iVar3 = FUN_800500cc(piStack00000024);
  if (iVar3 != 0) {
    if ((uint)*(ushort *)(piStack00000024 + 0x11) != level2SelectMenu.lower) {
      level2SelectMenu.lower = (uint)*(ushort *)(piStack00000024 + 0x11);
    }
    if ((gameTracker_00->debugFlags & 0x8000U) == 0) {
      FUN_8002e87c(psVar2,ot);
    }
  }
  piVar4 = *(int **)(*piStack00000024 + 0x30);
  iStack0000002c = *piVar4;
  piStack00000028 = piVar4 + 1;
  iVar3 = 0;
  if (0 < iStack0000002c) {
    iVar12 = (int)piVar4 + 0x22;
    do {
      in_stack_00000034 = *(int *)(iVar12 + -10);
      iVar9 = *(int *)(iVar12 + 10);
      if ((iVar9 == 0) || (*(ulong *)(iVar9 + 0x20) != draw[1].dr_env.code[3])) {
        in_stack_00000018 = 0x200;
        in_stack_0000001a = 0xf0;
        in_stack_0000001c = -0x200;
        in_stack_0000001e = -0xf0;
        debugRazielMenu.upper = 0x140;
        debugRazielMenu.lower = 0;
        debugRazielMenu.text = (char *)0x0;
        debugRazielMenu.var_address = (long *)0xf0;
        FUN_80014aa8(&standardMenu);
        iVar11 = 0;
        bVar1 = false;
        iVar10 = *(int *)(*piStack00000024 + 0x30) + 4;
        if (0 < iStack0000002c) {
          piVar4 = (int *)(*(int *)(*piStack00000024 + 0x30) + 0x2c);
          do {
            if (piVar4[-5] == in_stack_00000034) {
              iVar5 = FUN_8005e564(iVar10,&stack0x00000018);
              if (iVar5 == 0) {
                if (((theCamera.savedCinematic[0]._28_4_ & 0x2000000) != 0) && (*piVar4 != 0)) {
                    /* WARNING: Subroutine does not return */
                  FUN_8003432c(loadStatus.bigFile.searchDirID,0x22);
                }
              }
              else {
                bVar1 = true;
              }
            }
            iVar11 = iVar11 + 1;
            piVar4 = piVar4 + 0x17;
            iVar10 = iVar10 + 0x5c;
          } while (iVar11 < iStack0000002c);
        }
        if (bVar1) {
          iVar3 = (int)in_stack_00000018 * 0x140;
          if (iVar3 < 0) {
            iVar3 = iVar3 + 0x1ff;
          }
          debugRazielMenu.text = (char *)(int)in_stack_0000001a;
          debugRazielMenu.lower = iVar3 >> 9;
          iVar3 = ((int)in_stack_00000018 + (int)in_stack_0000001c) * 0x140;
          if (iVar3 < 0) {
            iVar3 = iVar3 + 0x1ff;
          }
          debugRazielMenu.upper = iVar3 >> 9;
          debugRazielMenu.var_address = (long *)(debugRazielMenu.text + (int)in_stack_0000001e);
          FUN_80014aa8(&standardMenu);
          FUN_800bce3c(level2SelectMenu.type);
                    /* WARNING: Subroutine does not return */
          FUN_800bce1c(level2SelectMenu.type);
        }
        if ((iVar9 != 0) && (*(ulong *)(iVar9 + 0x20) != draw[1].dr_env.code[3])) {
          *(ulong *)(iVar9 + 0x20) = draw[1].dr_env.code[3];
          FUN_8002ed7c(iVar9);
        }
      }
      iVar3 = iVar3 + 1;
      piStack00000028 = piStack00000028 + 0x17;
      iVar12 = iVar12 + 0x5c;
    } while (iVar3 < iStack0000002c);
  }
  iVar3 = 0;
  pDVar8 = &DVECTOR_800d1740;
  do {
    if ((pDVar8[1].vx == 2) && (pDVar8[8] != (DVECTOR)draw[1].dr_env.code[3])) {
      *(ulong *)(pDVar8 + 8) = draw[1].dr_env.code[3];
      FUN_8002ed7c(pDVar8);
    }
    iVar3 = iVar3 + 1;
    pDVar8 = pDVar8 + 0x10;
  } while (iVar3 < 0x10);
  debugRazielMenu.upper = 0x140;
  debugRazielMenu.lower = 0;
  debugRazielMenu.text = (char *)0x0;
  debugRazielMenu.var_address = (long *)0xf0;
  FUN_80014aa8(&standardMenu);
  if (fontTracker.font_buffer[189].y != 0) {
    FUN_8002f1b8(ot,1);
    FUN_8002fe34();
    FUN_800bac5c(clearRect[1]._8_4_,0xc00);
    FUN_8002fda8();
    ot = gameTracker_00->drawOT;
    fontTracker.font_buffer[189].y = 0;
    *(undefined4 *)(loadStatus.changeDir + 4) = in_stack_00000030;
  }
  if ((draw[1].dr_env.code[9] & 0x8000000) != 0) {
    FUN_8007c4fc();
  }
  DEBUG_Draw(gameTracker_00,ot);
  FUN_8002d464();
  FUN_8002f260(ot);
  uVar6 = FUN_800bd8a0(0xf2000000);
  gameTracker_00->idleTime = uVar6 & 0xffff | gameTimer << 0x10;
  if ((uint)gameTracker_00->frameRateLock < gameTracker_00->vblFrames) {
    if (gameTracker_00->reqDisp != (void *)0x0) {
      FUN_800bae94();
      gameTracker_00->reqDisp = (void *)0x0;
      gameTracker_00->vblFrames = 0;
    }
  }
  else {
    do {
      iVar3 = FUN_80024e14(gameTracker_00->reqDisp);
    } while (iVar3 != 0);
  }
  uVar7 = FUN_8003d7d8(gameTracker_00->idleTime);
  drawot = ot + 0xbff;
  iVar3 = (gameTracker_00->gameData).asmData.dispPage;
  gameTracker_00->idleTime = uVar7;
  (gameTracker_00->gameData).asmData.dispPage = 1 - iVar3;
  FUN_80014178(drawot);
  FUN_8002e1b8(ot);
  uVar6 = FUN_800bd8a0(0xf2000000);
  *(ulong **)&gameTracker_00->drawTimerReturn = &gameTracker_00->drawTime;
  gameTracker_00->usecsStartDraw = uVar6 & 0xffff | gameTimer << 0x10;
  if ((draw[1].dr_env.code[9] & 0x8000000) == 0) {
    FUN_800bad64(drawot);
  }
  else {
    FUN_8002fb84(ot);
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_DrawSavedOT(unsigned long **newOT /*$t3*/)
 // line 2710, offset 0x8002fc20
	/* begin block 1 */
		// Start line: 2711
		// Start offset: 0x8002FC20
		// Variables:
	// 		struct P_TAG *tag; // $a1
	// 		int y; // $a2

		/* begin block 1.1 */
			// Start line: 2719
			// Start offset: 0x8002FC84
			// Variables:
		// 		int tpage; // $v1
		/* end block 1.1 */
		// End offset: 0x8002FCAC
		// End Line: 2727

		/* begin block 1.2 */
			// Start line: 2732
			// Start offset: 0x8002FCC0
			// Variables:
		// 		int tpage; // $v1
		/* end block 1.2 */
		// End offset: 0x8002FCE8
		// End Line: 2740

		/* begin block 1.3 */
			// Start line: 2745
			// Start offset: 0x8002FCFC
		/* end block 1.3 */
		// End offset: 0x8002FD30
		// End Line: 2756
	/* end block 1 */
	// End offset: 0x8002FD54
	// End Line: 2759

	/* begin block 2 */
		// Start line: 6396
	/* end block 2 */
	// End Line: 6397

/* WARNING: Globals starting with '_' overlap smaller symbols at the same address */

void GAMELOOP_DrawSavedOT(ulong **newOT)

{
  ushort uVar1;
  uint uVar2;
  byte bVar3;
  uint uVar4;
  uint *in_a1;
  int in_a2;
  uint in_a3;
  uint in_t0;
  ushort in_t1;
  byte in_t2;
  int in_t3;
  
  do {
    uVar1 = *(ushort *)((int)in_a1 + 0x16);
    if ((uVar1 & 0xf) < 8) {
      if (in_a2 == 0) {
        *(ushort *)((int)in_a1 + 0x16) = uVar1 & in_t1;
      }
      else {
        *(ushort *)((int)in_a1 + 0x16) = uVar1 | 0x10;
      }
    }
    while( true ) {
      while( true ) {
        in_a1 = (uint *)(*in_a1 & 0xffffff | 0x80000000);
        if (in_a1 == (uint *)gameTrackerX.gameData.asmData.drawBackFaces) {
          *(uint *)gameTrackerX.gameData.asmData.drawBackFaces =
               *(uint *)gameTrackerX.gameData.asmData.drawBackFaces & 0xff000000 |
               (uint)(&DAT_00002ffc + in_t3) & 0xffffff;
          FUN_800bad64(_mainMenuTimeOut);
          return;
        }
        bVar3 = *(byte *)((int)in_a1 + 7) & in_t2;
        if (bVar3 != 0x34) break;
        uVar1 = *(ushort *)((int)in_a1 + 0x1a);
        if ((uVar1 & 0xf) < 8) {
          if (in_a2 == 0) {
            *(ushort *)((int)in_a1 + 0x1a) = uVar1 & in_t1;
          }
          else {
            *(ushort *)((int)in_a1 + 0x1a) = uVar1 | 0x10;
          }
        }
      }
      if (bVar3 == 0x24) break;
      if (*(byte *)((int)in_a1 + 7) == 0xe3) {
        if (in_a2 == 0) {
          uVar2 = in_a1[1] & in_a3;
          uVar4 = in_a1[2] & in_a3;
        }
        else {
          uVar2 = in_a1[1] | in_t0;
          uVar4 = in_a1[2] | in_t0;
        }
        in_a1[1] = uVar2;
        in_a1[2] = uVar4;
      }
    }
  } while( true );
}



// decompiled code
// original method signature: 
// void /*$ra*/ ResetPrimPool()
 // line 2764, offset 0x8002fd98
	/* begin block 1 */
		// Start line: 6554
	/* end block 1 */
	// End Line: 6555

/* WARNING: Unknown calling convention yet parameter storage is locked */

void ResetPrimPool(void)

{
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ Switch_For_Redraw()
 // line 2793, offset 0x8002fe44
	/* begin block 1 */
		// Start line: 2795
		// Start offset: 0x8002FE44
		// Variables:
	// 		unsigned long **temp; // $v1
	/* end block 1 */
	// End offset: 0x8002FEA4
	// End Line: 2820

	/* begin block 2 */
		// Start line: 6612
	/* end block 2 */
	// End Line: 6613

	/* begin block 3 */
		// Start line: 6613
	/* end block 3 */
	// End Line: 6614

	/* begin block 4 */
		// Start line: 6616
	/* end block 4 */
	// End Line: 6617

/* WARNING: Unknown calling convention yet parameter storage is locked */

void Switch_For_Redraw(void)

{
                    /* WARNING: Subroutine does not return */
  FUN_800ba930();
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_Set_Pause_Redraw()
 // line 2824, offset 0x8002fec0
	/* begin block 1 */
		// Start line: 6677
	/* end block 1 */
	// End Line: 6678

	/* begin block 2 */
		// Start line: 6678
	/* end block 2 */
	// End Line: 6679

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GAMELOOP_Set_Pause_Redraw(void)

{
  char cVar1;
  uint *puVar2;
  uint in_v1;
  uint *in_a0;
  uint *unaff_s0;
  uint *puVar3;
  uint *unaff_s1;
  
  puVar2 = in_a0;
  if ((*in_a0 & in_v1) != in_v1) {
    do {
      while (puVar3 = unaff_s0, in_a0 = puVar2, *(char *)((int)in_a0 + 3) != '\0') {
        if ((*in_a0 & 0xffffff) == 0xffffff) goto LAB_8002ff9c;
        puVar2 = (uint *)(*in_a0 & 0xffffff | 0x80000000);
        unaff_s0 = in_a0;
        unaff_s1 = puVar3;
      }
      if ((*in_a0 & 0xffffff) == 0xffffff) goto LAB_8002ff9c;
      cVar1 = *(char *)((int)in_a0 + 3);
      while ((cVar1 == '\0' && ((*in_a0 & 0xffffff) != 0xffffff))) {
        in_a0 = (uint *)(*in_a0 & 0xffffff | 0x80000000);
        cVar1 = *(char *)((int)in_a0 + 3);
      }
      *puVar3 = *puVar3 & 0xff000000 | (uint)in_a0 & 0xffffff;
      puVar2 = in_a0;
      unaff_s0 = puVar3;
    } while ((*in_a0 & 0xffffff) != 0xffffff);
    if ((*in_a0 & 0xffffff) != 0xffffff) {
      gameTrackerX.gameData.asmData.drawBackFaces = (long)in_a0;
      return;
    }
  }
LAB_8002ff9c:
  gameTrackerX.gameData.asmData.drawBackFaces = (long)in_a0;
  if (unaff_s1 != (uint *)0x0) {
    gameTrackerX.gameData.asmData.drawBackFaces = (long)unaff_s1;
    *unaff_s1 = *unaff_s1 | 0xffffff;
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SaveOT()
 // line 2829, offset 0x8002fed0
	/* begin block 1 */
		// Start line: 2830
		// Start offset: 0x8002FED0
		// Variables:
	// 		struct P_TAG *tag; // $a0
	// 		struct P_TAG *last; // $s0
	// 		struct P_TAG *lastlast; // $s1
	/* end block 1 */
	// End offset: 0x8003005C
	// End Line: 2880

	/* begin block 2 */
		// Start line: 6687
	/* end block 2 */
	// End Line: 6688

/* WARNING: Unknown calling convention yet parameter storage is locked */

void SaveOT(void)

{
  char cVar1;
  uint *in_a0;
  uint *puVar2;
  uint *unaff_s0;
  uint *puVar3;
  uint *unaff_s1;
  
  gameTrackerX.gameData.asmData.drawBackFaces = (long)unaff_s1;
  do {
    while (puVar3 = unaff_s0, puVar2 = in_a0, *(char *)((int)puVar2 + 3) != '\0') {
      if ((*puVar2 & 0xffffff) == 0xffffff) goto LAB_8002ff9c;
      in_a0 = (uint *)(*puVar2 & 0xffffff | 0x80000000);
      unaff_s0 = puVar2;
      gameTrackerX.gameData.asmData.drawBackFaces = (long)puVar3;
    }
    if ((*puVar2 & 0xffffff) == 0xffffff) goto LAB_8002ff9c;
    cVar1 = *(char *)((int)puVar2 + 3);
    while ((cVar1 == '\0' && ((*puVar2 & 0xffffff) != 0xffffff))) {
      puVar2 = (uint *)(*puVar2 & 0xffffff | 0x80000000);
      cVar1 = *(char *)((int)puVar2 + 3);
    }
    *puVar3 = *puVar3 & 0xff000000 | (uint)puVar2 & 0xffffff;
    in_a0 = puVar2;
    unaff_s0 = puVar3;
  } while ((*puVar2 & 0xffffff) != 0xffffff);
  if ((*puVar2 & 0xffffff) == 0xffffff) {
LAB_8002ff9c:
    if ((uint *)gameTrackerX.gameData.asmData.drawBackFaces != (uint *)0x0) {
      *(uint *)gameTrackerX.gameData.asmData.drawBackFaces =
           *(uint *)gameTrackerX.gameData.asmData.drawBackFaces | 0xffffff;
      puVar2 = (uint *)gameTrackerX.gameData.asmData.drawBackFaces;
    }
  }
  gameTrackerX.gameData.asmData.drawBackFaces = (long)puVar2;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ ResetDrawPage()
 // line 2882, offset 0x80030070
	/* begin block 1 */
		// Start line: 2883
		// Start offset: 0x80030070

		/* begin block 1.1 */
			// Start line: 2883
			// Start offset: 0x80030070
			// Variables:
		// 		unsigned long **temp; // $v0
		/* end block 1.1 */
		// End offset: 0x80030070
		// End Line: 2883
	/* end block 1 */
	// End offset: 0x80030070
	// End Line: 2883

	/* begin block 2 */
		// Start line: 6813
	/* end block 2 */
	// End Line: 6814

/* WARNING: Unknown calling convention yet parameter storage is locked */

void ResetDrawPage(void)

{
  bool bVar1;
  uint in_v0;
  uint uVar2;
  uint unaff_s0;
  int unaff_s1;
  uint uVar3;
  
  if (gameTrackerX.controlData[1][1] < 1) {
    gameTrackerX.controlData[1][1] = 1;
  }
  if (2 < gameTrackerX.controlData[1][1]) {
    gameTrackerX.controlData[1][1] = 2;
  }
  if ((gameTrackerX.vertexPool == (_VertexPool *)0x0) || ((draw[1].dr_env.code[9] & unaff_s0) != 0))
  {
    if (gameTrackerX.controlData[1][1] == 1) {
      gameTrackerX.controlCommand[1][0] = 0x21;
    }
    else {
      if (gameTrackerX.controlData[1][1] == 2) {
        gameTrackerX.controlCommand[1][0] = 0x32;
      }
    }
    uVar3 = (uint)((ulonglong)(uint)(gameTrackerX.controlCommand[1][0] << 0xc) * 0x3e0f83e1 >> 0x20)
    ;
  }
  else {
    uVar2 = 0x21;
    if ((gameTrackerX.controlData[1][1] != 1) && (gameTrackerX.controlData[1][1] == 2)) {
      uVar2 = 0x32;
    }
    uVar3 = uVar2;
    if (gameTrackerX.controlCommand[1][0] != -1) {
      uVar3 = unaff_s1 - gameTrackerX.controlCommand[0][1];
    }
    bVar1 = uVar3 < uVar2;
    if ((gameTrackerX.controlData[1][1] == 1) &&
       (bVar1 = uVar3 < uVar2, (short)gameTrackerX.controlData[1][2] != 0)) {
      uVar3 = uVar3 - 9;
      bVar1 = uVar3 < uVar2;
    }
    if (((!bVar1) && ((short)loadStatus.decompressLen == 1000)) && (uVar2 = uVar3, 0x42 < uVar3)) {
      uVar2 = 0x42;
    }
    uVar3 = (uint)((ulonglong)(uVar2 << 0xc) * 0x3e0f83e1 >> 0x20);
    gameTrackerX.controlCommand[1][0] = uVar2;
  }
  gameTrackerX.controlCommand[1][1] = uVar3 >> 3;
  gameTrackerX.controlData[0][4] = 0;
  gameTrackerX.controlData[1][0] =
       gameTrackerX.controlData[1][0] + gameTrackerX.controlCommand[1][1];
  while (0x1000 < (uint)gameTrackerX.controlData[1][0]) {
    gameTrackerX.controlData[0][4] = 1;
    gameTrackerX.controlData[1][0] = gameTrackerX.controlData[1][0] - 0x1000;
    draw[1].dr_env.code[5] = draw[1].dr_env.code[5] + 1;
  }
  gameTrackerX.controlCommand[0][1] = unaff_s1;
  gameTrackerX.controlCommand[1][2] = gameTrackerX.controlCommand[1][1];
  gameTrackerX.controlData[0][0] = in_v0 & 0xffff | gameTimer << 0x10;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_Set24FPS()
 // line 2914, offset 0x800300b0
	/* begin block 1 */
		// Start line: 6889
	/* end block 1 */
	// End Line: 6890

	/* begin block 2 */
		// Start line: 6890
	/* end block 2 */
	// End Line: 6891

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GAMELOOP_Set24FPS(void)

{
  bool bVar1;
  uint uVar2;
  uint unaff_s0;
  int unaff_s1;
  uint uVar3;
  
  if ((gameTrackerX.vertexPool == (_VertexPool *)0x0) || ((draw[1].dr_env.code[9] & unaff_s0) != 0))
  {
    if (gameTrackerX.controlData[1][1] == 1) {
      gameTrackerX.controlCommand[1][0] = 0x21;
    }
    else {
      if (gameTrackerX.controlData[1][1] == 2) {
        gameTrackerX.controlCommand[1][0] = 0x32;
      }
    }
    uVar3 = (uint)((ulonglong)(uint)(gameTrackerX.controlCommand[1][0] << 0xc) * 0x3e0f83e1 >> 0x20)
    ;
  }
  else {
    uVar2 = 0x21;
    if ((gameTrackerX.controlData[1][1] != 1) && (gameTrackerX.controlData[1][1] == 2)) {
      uVar2 = 0x32;
    }
    uVar3 = uVar2;
    if (gameTrackerX.controlCommand[1][0] != -1) {
      uVar3 = unaff_s1 - gameTrackerX.controlCommand[0][1];
    }
    bVar1 = uVar3 < uVar2;
    if ((gameTrackerX.controlData[1][1] == 1) &&
       (bVar1 = uVar3 < uVar2, (short)gameTrackerX.controlData[1][2] != 0)) {
      uVar3 = uVar3 - 9;
      bVar1 = uVar3 < uVar2;
    }
    if (((!bVar1) && ((short)loadStatus.decompressLen == 1000)) && (uVar2 = uVar3, 0x42 < uVar3)) {
      uVar2 = 0x42;
    }
    uVar3 = (uint)((ulonglong)(uVar2 << 0xc) * 0x3e0f83e1 >> 0x20);
    gameTrackerX.controlCommand[1][0] = uVar2;
  }
  gameTrackerX.controlCommand[1][1] = uVar3 >> 3;
  gameTrackerX.controlData[0][4] = 0;
  gameTrackerX.controlData[1][0] =
       gameTrackerX.controlData[1][0] + gameTrackerX.controlCommand[1][1];
  while (0x1000 < (uint)gameTrackerX.controlData[1][0]) {
    gameTrackerX.controlData[0][4] = 1;
    gameTrackerX.controlData[1][0] = gameTrackerX.controlData[1][0] - 0x1000;
    draw[1].dr_env.code[5] = draw[1].dr_env.code[5] + 1;
  }
  gameTrackerX.controlCommand[0][1] = unaff_s1;
  gameTrackerX.controlCommand[1][2] = gameTrackerX.controlCommand[1][1];
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_Reset24FPS()
 // line 2920, offset 0x800300c0
	/* begin block 1 */
		// Start line: 6901
	/* end block 1 */
	// End Line: 6902

	/* begin block 2 */
		// Start line: 6902
	/* end block 2 */
	// End Line: 6903

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GAMELOOP_Reset24FPS(void)

{
  bool bVar1;
  uint uVar2;
  uint unaff_s0;
  int unaff_s1;
  uint uVar3;
  
  if ((draw[1].dr_env.code[9] & unaff_s0) == 0) {
    uVar2 = 0x21;
    if ((gameTrackerX.controlData[1][1] != 1) && (gameTrackerX.controlData[1][1] == 2)) {
      uVar2 = 0x32;
    }
    uVar3 = uVar2;
    if (gameTrackerX.controlCommand[1][0] != -1) {
      uVar3 = unaff_s1 - gameTrackerX.controlCommand[0][1];
    }
    bVar1 = uVar3 < uVar2;
    if ((gameTrackerX.controlData[1][1] == 1) &&
       (bVar1 = uVar3 < uVar2, (short)gameTrackerX.controlData[1][2] != 0)) {
      uVar3 = uVar3 - 9;
      bVar1 = uVar3 < uVar2;
    }
    if (((!bVar1) && ((short)loadStatus.decompressLen == 1000)) && (uVar2 = uVar3, 0x42 < uVar3)) {
      uVar2 = 0x42;
    }
    uVar3 = (uint)((ulonglong)(uVar2 << 0xc) * 0x3e0f83e1 >> 0x20);
    gameTrackerX.controlCommand[1][0] = uVar2;
  }
  else {
    if (gameTrackerX.controlData[1][1] == 1) {
      gameTrackerX.controlCommand[1][0] = 0x21;
    }
    else {
      if (gameTrackerX.controlData[1][1] == 2) {
        gameTrackerX.controlCommand[1][0] = 0x32;
      }
    }
    uVar3 = (uint)((ulonglong)(uint)(gameTrackerX.controlCommand[1][0] << 0xc) * 0x3e0f83e1 >> 0x20)
    ;
  }
  gameTrackerX.controlCommand[1][1] = uVar3 >> 3;
  gameTrackerX.controlData[0][4] = 0;
  gameTrackerX.controlData[1][0] =
       gameTrackerX.controlData[1][0] + gameTrackerX.controlCommand[1][1];
  while (0x1000 < (uint)gameTrackerX.controlData[1][0]) {
    gameTrackerX.controlData[0][4] = 1;
    gameTrackerX.controlData[1][0] = gameTrackerX.controlData[1][0] - 0x1000;
    draw[1].dr_env.code[5] = draw[1].dr_env.code[5] + 1;
  }
  gameTrackerX.controlCommand[0][1] = unaff_s1;
  gameTrackerX.controlCommand[1][2] = gameTrackerX.controlCommand[1][1];
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_DoTimeProcess()
 // line 2925, offset 0x800300cc
	/* begin block 1 */
		// Start line: 2926
		// Start offset: 0x800300CC
		// Variables:
	// 		int holdTime; // $s1

		/* begin block 1.1 */
			// Start line: 2961
			// Start offset: 0x800301B0
			// Variables:
		// 		int lockRate; // $a1
		// 		unsigned long last; // $a0
		/* end block 1.1 */
		// End offset: 0x80030260
		// End Line: 2998
	/* end block 1 */
	// End offset: 0x800302B8
	// End Line: 3014

	/* begin block 2 */
		// Start line: 6911
	/* end block 2 */
	// End Line: 6912

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GAMELOOP_DoTimeProcess(void)

{
  bool bVar1;
  int in_v0;
  uint uVar2;
  int unaff_s1;
  uint uVar3;
  
  if (in_v0 == 0) {
    uVar2 = 0x21;
    if ((gameTrackerX.controlData[1][1] != 1) && (gameTrackerX.controlData[1][1] == 2)) {
      uVar2 = 0x32;
    }
    uVar3 = uVar2;
    if (gameTrackerX.controlCommand[1][0] != -1) {
      uVar3 = unaff_s1 - gameTrackerX.controlCommand[0][1];
    }
    bVar1 = uVar3 < uVar2;
    if ((gameTrackerX.controlData[1][1] == 1) &&
       (bVar1 = uVar3 < uVar2, (short)gameTrackerX.controlData[1][2] != 0)) {
      uVar3 = uVar3 - 9;
      bVar1 = uVar3 < uVar2;
    }
    if (((!bVar1) && ((short)loadStatus.decompressLen == 1000)) && (uVar2 = uVar3, 0x42 < uVar3)) {
      uVar2 = 0x42;
    }
    uVar3 = (uint)((ulonglong)(uVar2 << 0xc) * 0x3e0f83e1 >> 0x20);
    gameTrackerX.controlCommand[1][0] = uVar2;
  }
  else {
    if (gameTrackerX.controlData[1][1] == 1) {
      gameTrackerX.controlCommand[1][0] = 0x21;
    }
    else {
      if (gameTrackerX.controlData[1][1] == 2) {
        gameTrackerX.controlCommand[1][0] = 0x32;
      }
    }
    uVar3 = (uint)((ulonglong)(uint)(gameTrackerX.controlCommand[1][0] << 0xc) * 0x3e0f83e1 >> 0x20)
    ;
  }
  gameTrackerX.controlCommand[1][1] = uVar3 >> 3;
  gameTrackerX.controlData[0][4] = 0;
  gameTrackerX.controlData[1][0] =
       gameTrackerX.controlData[1][0] + gameTrackerX.controlCommand[1][1];
  while (0x1000 < (uint)gameTrackerX.controlData[1][0]) {
    gameTrackerX.controlData[0][4] = 1;
    gameTrackerX.controlData[1][0] = gameTrackerX.controlData[1][0] - 0x1000;
    draw[1].dr_env.code[5] = draw[1].dr_env.code[5] + 1;
  }
  gameTrackerX.controlCommand[0][1] = unaff_s1;
  gameTrackerX.controlCommand[1][2] = gameTrackerX.controlCommand[1][1];
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_Process(struct GameTracker *gameTracker /*$s5*/)
 // line 3021, offset 0x800302d0
	/* begin block 1 */
		// Start line: 3022
		// Start offset: 0x800302D0
		// Variables:
	// 		int d; // $s2

		/* begin block 1.1 */
			// Start line: 3064
			// Start offset: 0x80030378
			// Variables:
		// 		int useTime; // $s0

			/* begin block 1.1.1 */
				// Start line: 3067
				// Start offset: 0x80030388
				// Variables:
			// 		struct Level *level; // $v0
			/* end block 1.1.1 */
			// End offset: 0x800303AC
			// End Line: 3072
		/* end block 1.1 */
		// End offset: 0x800303DC
		// End Line: 3077

		/* begin block 1.2 */
			// Start line: 3184
			// Start offset: 0x8003057C
			// Variables:
		// 		int i; // $s0

			/* begin block 1.2.1 */
				// Start line: 3191
				// Start offset: 0x800305A8
				// Variables:
			// 		struct _SFXMkr *sfxMkr; // $a2
			/* end block 1.2.1 */
			// End offset: 0x800305FC
			// End Line: 3203
		/* end block 1.2 */
		// End offset: 0x80030624
		// End Line: 3205
	/* end block 1 */
	// End offset: 0x800308F8
	// End Line: 3407

	/* begin block 2 */
		// Start line: 7120
	/* end block 2 */
	// End Line: 7121

	/* begin block 3 */
		// Start line: 7129
	/* end block 3 */
	// End Line: 7130

void GAMELOOP_Process(GameTracker *gameTracker)

{
  int in_v0;
  int in_v1;
  int unaff_s5;
  
  *(int *)(unaff_s5 + 0x234) = in_v0 + in_v1;
  *(undefined2 *)(unaff_s5 + 0xd2) = 0;
  FUN_80030a34();
  FUN_8002fcfc();
                    /* WARNING: Subroutine does not return */
  FUN_800bcdac(unaff_s5 + 0x98,0,0x28);
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_ModeStartRunning()
 // line 3411, offset 0x80030920
	/* begin block 1 */
		// Start line: 7987
	/* end block 1 */
	// End Line: 7988

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GAMELOOP_ModeStartRunning(void)

{
  uint in_v0;
  int in_a0;
  
  *(uint *)(in_a0 + 0x14) = in_v0 & 0xfffffeff;
  BmenuLines[1].vramBlock._2_2_ = 0;
  FUN_80031db4();
                    /* WARNING: Subroutine does not return */
  FUN_80034368(loadStatus.bigFile.searchDirID,&DAT_0010000a,0);
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_ModeStartPause()
 // line 3441, offset 0x800309f8
	/* begin block 1 */
		// Start line: 8050
	/* end block 1 */
	// End Line: 8051

void GAMELOOP_ModeStartPause(void)

{
  *(int *)(loadStatus.changeDir + 4) = loadStatus.changeDir + 0xc;
  *(undefined4 *)loadStatus.changeDir = 0;
  FUN_8002fe34();
  fontTracker.font_buffer[189].y = 1;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_ChangeMode()
 // line 3493, offset 0x80030ad0
	/* begin block 1 */
		// Start line: 3494
		// Start offset: 0x80030AD0
		// Variables:
	// 		long *controlCommand; // $s0
	/* end block 1 */
	// End offset: 0x80030E6C
	// End Line: 3661

	/* begin block 2 */
		// Start line: 6986
	/* end block 2 */
	// End Line: 6987

/* WARNING: Unknown calling convention yet parameter storage is locked */

void GAMELOOP_ChangeMode(void)

{
  int in_v0;
  uint uVar1;
  int in_v1;
  uint *unaff_s0;
  
  if (in_v1 != in_v0) {
    if (((((draw[0].dr_env.code[0] & 0x40000) == 0) || (((uint)gameTrackerX.memcard & 2) != 0)) &&
        ((unaff_s0[1] & 0x60) == 0x60)) && ((*unaff_s0 & 0xf) == 0)) {
      if (BmenuLines[1].vramBlock._2_2_ == 0) {
        BmenuLines[1].vramBlock._2_2_ = 4;
        if (clearRect[0].b0 == '\0') {
          draw[0].dr_env.code[0] = draw[0].dr_env.code[0] & 0xfff7ffff;
        }
        else {
          draw[0].dr_env.code[0] = draw[0].dr_env.code[0] | 0x80000;
        }
        if (clearRect[0].g0 == '\0') {
          uVar1 = draw[0].dr_env.code[1] & 0xffffefff;
        }
        else {
          uVar1 = draw[0].dr_env.code[1] | 0x1000;
        }
        if (clearRect[0].r0 == '\0') {
          draw[0].dr_env.code[1] = uVar1 & 0xffffdfff;
          currentMenu = (DebugMenuLine *)FontPos_ARRAY_800c8584;
        }
        else {
          draw[0].dr_env.code[1] = uVar1 | 0x2000;
          currentMenu = (DebugMenuLine *)FontPos_ARRAY_800c8584;
        }
      }
      else {
        if (BmenuLines[1].vramBlock._2_2_ == 7) {
          FUN_800141d4(0x800d0dcc);
          BmenuLines[1].vramBlock._2_2_ = 0;
        }
        else {
          FUN_80030884();
        }
      }
    }
    if (((((unaff_s0[1] & 0x4000) == 0) && (fontTracker.font_buffer._1444_4_ < 6)) ||
        ((BmenuLines[1].vramBlock._2_2_ != 0 || ((draw[1].dr_env.code[9] & 0x80) != 0)))) ||
       (((short)draw[0].dr_env.code[3] != 0 &&
        (((short)draw[0].dr_env.code[4] == 0xb || ((short)draw[0].dr_env.code[3] != -1)))))) {
      if ((((((unaff_s0[1] & 0x4000) != 0) || ((draw[1].dr_env.code[9] & 0x40000000) != 0)) &&
           (BmenuLines[1].vramBlock._2_2_ != 0)) && ((draw[1].dr_env.code[9] & 0x20000000) == 0)) &&
         (((short)draw[0].dr_env.code[3] == 0 ||
          (((short)draw[0].dr_env.code[4] != 0xb && ((short)draw[0].dr_env.code[3] == -1)))))) {
        if (((unaff_s0[1] & 0x4000) != 0) && ((draw[1].dr_env.code[9] & 0x40000000) == 0)) {
          SOUND_SfxOn();
        }
        draw[1].dr_env.code[9] = draw[1].dr_env.code[9] & 0xbfffffff;
        FUN_80030884();
      }
    }
    else {
      FUN_8003095c();
    }
    if ((loadStatus.currentDirLoading & 0x40000000U) == 0) {
      if ((mainMenuSfx & 0x40000000U) != 0) {
        *(uint *)(loadStatus.bigFile.searchDirID + 0x14) =
             *(uint *)(loadStatus.bigFile.searchDirID + 0x14) & 0xfffffeff;
      }
    }
    else {
      *(uint *)(loadStatus.bigFile.searchDirID + 0x14) =
           *(uint *)(loadStatus.bigFile.searchDirID + 0x14) | 0x100;
    }
    return;
  }
  theCamera.noTeleport._0_2_ = 1;
  *(short *)(loadStatus.bigFile.searchDirID + 0x60) =
       *(short *)(loadStatus.bigFile.searchDirID + 0x60) + -100;
  *(undefined4 *)(loadStatus.bigFile.searchDirID + 0x15c) = 0;
  clearRect[0].y0._1_1_ = 0;
                    /* WARNING: Subroutine does not return */
  FUN_80034368(loadStatus.bigFile.searchDirID,&DAT_00100010,0);
}



// decompiled code
// original method signature: 
// void /*$ra*/ GAMELOOP_RequestLevelChange(char *name /*$s2*/, short number /*$a1*/, struct GameTracker *gameTracker /*$s0*/)
 // line 3664, offset 0x80030e7c
	/* begin block 1 */
		// Start line: 8558
	/* end block 1 */
	// End Line: 8559

void GAMELOOP_RequestLevelChange(char *name,short number,GameTracker *gameTracker)

{
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ PSX_GameLoop(struct GameTracker *gameTracker /*$s0*/)
 // line 3686, offset 0x80030efc
	/* begin block 1 */
		// Start line: 8602
	/* end block 1 */
	// End Line: 8603

void PSX_GameLoop(GameTracker *gameTracker)

{
  uint *in_v0;
  uint *puVar1;
  int iVar2;
  int iVar3;
  uint in_v1;
  uint uVar4;
  short *psVar5;
  long (*data) [5];
  int pad;
  uint *puVar6;
  int iVar7;
  uint uVar8;
  uint uVar9;
  int in_t3;
  int in_t4;
  
  *(long (**) [5])(*data + 2) = (long (*) [5])((uint)gameTracker & in_v1);
  uVar9 = in_v0[3];
  uVar8 = in_v0[4];
  if ((*in_v0 & 1) == 0) {
    if ((*in_v0 & 2) != 0) {
      uVar8 = 0x80;
    }
  }
  else {
    uVar8 = 0xffffff80;
  }
  uVar4 = *(uint *)(pad * 0x14 + in_t3);
  if ((uVar4 & 4) != 0) {
    GAMEPAD_Commands((long (*) [5])((uint)gameTracker & in_v1),data,pad);
    return;
  }
  if ((uVar4 & 8) != 0) {
    uVar9 = 0x80;
  }
  if ((int)uVar8 < -0x37) {
    puVar1 = (uint *)(pad * 0x14 + in_t3);
    uVar4 = *puVar1 | 1;
LAB_80030fb4:
    *puVar1 = uVar4;
  }
  else {
    if (0x37 < (int)uVar8) {
      puVar1 = (uint *)(pad * 0x14 + in_t3);
      uVar4 = *puVar1 | 2;
      goto LAB_80030fb4;
    }
  }
  if ((int)uVar9 < -0x37) {
    puVar1 = (uint *)(pad * 0x14 + in_t3);
    uVar4 = *puVar1 | 4;
  }
  else {
    iVar2 = pad * 4;
    if ((int)uVar9 < 0x38) goto LAB_80031008;
    puVar1 = (uint *)(pad * 0x14 + in_t3);
    uVar4 = *puVar1 | 8;
  }
  *puVar1 = uVar4;
  iVar2 = pad << 2;
LAB_80031008:
  iVar2 = iVar2 + pad;
  iVar7 = iVar2 * 4;
  psVar5 = &fontTracker.font_buffer[0xc3].y + pad;
  puVar6 = (uint *)(iVar7 + in_t3);
  puVar6[1] = ~(int)*psVar5 & *puVar6;
  *psVar5 = *(short *)puVar6;
  puVar1 = (uint *)(iVar7 + in_t4);
  puVar1[3] = uVar9;
  puVar1[4] = uVar8;
  if ((draw[1].dr_env.code[9] & 0x10) == 0) {
    iVar2 = 0;
    if ((draw[1].dr_env.code[9] & 1) != 0) {
                    /* WARNING: Subroutine does not return */
      FUN_800bcdac(0x800d0e14,0,0x28);
    }
    puVar1[1] = ~*puVar1 & *puVar6;
    *puVar1 = *puVar6;
    iVar7 = 0;
    if ((*puVar6 & 1) == 0) {
      if ((*puVar6 & 2) != 0) {
        iVar7 = 0x80;
      }
    }
    else {
      iVar7 = -0x80;
    }
    uVar8 = *(uint *)(pad * 0x14 + in_t3);
    if ((uVar8 & 4) == 0) {
      if ((uVar8 & 8) != 0) {
        iVar2 = 0x80;
      }
    }
    else {
      iVar2 = -0x80;
    }
    if ((iVar2 != 0) || (iVar7 != 0)) {
      iVar3 = pad * 0x14 + in_t3;
      *(int *)(iVar3 + 0xc) = iVar2;
      *(int *)(iVar3 + 0x10) = iVar7;
    }
  }
  else {
    puVar1[1] = ~*puVar1 & *(uint *)(&DISPENV_800d0e54.isinter + iVar7);
    *puVar1 = *(uint *)(&DISPENV_800d0e54.isinter + iVar7);
    puVar6[3] = *(uint *)(&draw[0].clip.w + iVar2 * 2);
    puVar6[4] = *(uint *)(draw[0].ofs + iVar2 * 2);
    uVar8 = 0xffffff80;
    if (((*(uint *)(&DISPENV_800d0e54.isinter + iVar7) & 1) != 0) ||
       (uVar8 = 0x80, (*(uint *)(&DISPENV_800d0e54.isinter + iVar7) & 2) != 0)) {
      puVar6[4] = uVar8;
    }
    if ((*(uint *)&(&DISPENV_800d0e54)[pad].isinter & 4) == 0) {
      if ((*(uint *)&(&DISPENV_800d0e54)[pad].isinter & 8) != 0) {
        *(undefined4 *)(pad * 0x14 + in_t3 + 0xc) = 0x80;
      }
    }
    else {
      *(undefined4 *)(pad * 0x14 + in_t3 + 0xc) = 0xffffff80;
    }
  }
  if ((((draw[0].dr_env.code[0] & 0x40000) == 0) && ((draw[0].dr_env.code[1] & 0x2000000) != 0)) &&
     (puVar1 = (uint *)(pad * 0x14 + in_t4), (*(uint *)(pad * 0x14 + in_t3) & 0x300) == 0x300)) {
    *puVar1 = *puVar1 & 0xfffff3ff | 0x40000000;
    if ((puVar1[1] & 0xc00) != 0) {
      puVar1[1] = puVar1[1] | 0x40000000;
    }
    puVar1[1] = puVar1[1] & 0xfffff3ff;
  }
  return;
}



// decompiled code
// original method signature: 
// struct MATRIX * /*$ra*/ GAMELOOP_GetMatrices(int numMatrices /*$a0*/)
 // line 3696, offset 0x80030f28
	/* begin block 1 */
		// Start line: 3698
		// Start offset: 0x80030F28
		// Variables:
	// 		struct MATRIX *matrix; // $a1
	// 		struct _PrimPool *pool; // $v1
	/* end block 1 */
	// End offset: 0x80030F4C
	// End Line: 3715

	/* begin block 2 */
		// Start line: 8622
	/* end block 2 */
	// End Line: 8623

	/* begin block 3 */
		// Start line: 8623
	/* end block 3 */
	// End Line: 8624

	/* begin block 4 */
		// Start line: 8624
	/* end block 4 */
	// End Line: 8625

/* WARNING: Removing unreachable block (ram,0x80030f74) */

MATRIX * GAMELOOP_GetMatrices(int numMatrices)

{
  MATRIX *pMVar1;
  uint *puVar2;
  int iVar3;
  int iVar4;
  uint uVar5;
  short *psVar6;
  long (*data) [5];
  int pad;
  uint *puVar7;
  int iVar8;
  uint in_t2;
  int in_t3;
  int in_t4;
  
  uVar5 = *(uint *)(pad * 0x14 + in_t3);
  pMVar1 = (MATRIX *)(uVar5 & 8);
  if ((uVar5 & 4) != 0) {
    GAMEPAD_Commands((long (*) [5])numMatrices,data,pad);
    return pMVar1;
  }
  if (pMVar1 != (MATRIX *)0x0) {
    in_t2 = 0x80;
  }
  puVar2 = (uint *)(pad * 0x14 + in_t3);
  *puVar2 = *puVar2 | 2;
  if ((int)in_t2 < -0x37) {
    puVar2 = (uint *)(pad * 0x14 + in_t3);
    uVar5 = *puVar2 | 4;
  }
  else {
    iVar3 = pad * 4;
    if ((int)in_t2 < 0x38) goto LAB_80031008;
    puVar2 = (uint *)(pad * 0x14 + in_t3);
    uVar5 = *puVar2 | 8;
  }
  *puVar2 = uVar5;
  iVar3 = pad << 2;
LAB_80031008:
  iVar3 = iVar3 + pad;
  iVar8 = iVar3 * 4;
  psVar6 = &fontTracker.font_buffer[0xc3].y + pad;
  puVar7 = (uint *)(iVar8 + in_t3);
  puVar7[1] = ~(int)*psVar6 & *puVar7;
  *psVar6 = *(short *)puVar7;
  puVar2 = (uint *)(iVar8 + in_t4);
  puVar2[3] = in_t2;
  puVar2[4] = 0x80;
  if ((draw[1].dr_env.code[9] & 0x10) == 0) {
    iVar3 = 0;
    if ((draw[1].dr_env.code[9] & 1) != 0) {
                    /* WARNING: Subroutine does not return */
      FUN_800bcdac(0x800d0e14,0,0x28);
    }
    puVar2[1] = ~*puVar2 & *puVar7;
    *puVar2 = *puVar7;
    iVar8 = 0;
    if ((*puVar7 & 1) == 0) {
      if ((*puVar7 & 2) != 0) {
        iVar8 = 0x80;
      }
    }
    else {
      iVar8 = -0x80;
    }
    uVar5 = *(uint *)(pad * 0x14 + in_t3);
    if ((uVar5 & 4) == 0) {
      if ((uVar5 & 8) != 0) {
        iVar3 = 0x80;
      }
    }
    else {
      iVar3 = -0x80;
    }
    if ((iVar3 != 0) || (iVar8 != 0)) {
      iVar4 = pad * 0x14 + in_t3;
      *(int *)(iVar4 + 0xc) = iVar3;
      *(int *)(iVar4 + 0x10) = iVar8;
    }
  }
  else {
    puVar2[1] = ~*puVar2 & *(uint *)(&DISPENV_800d0e54.isinter + iVar8);
    *puVar2 = *(uint *)(&DISPENV_800d0e54.isinter + iVar8);
    puVar7[3] = *(uint *)(&draw[0].clip.w + iVar3 * 2);
    puVar7[4] = *(uint *)(draw[0].ofs + iVar3 * 2);
    uVar5 = 0xffffff80;
    if (((*(uint *)(&DISPENV_800d0e54.isinter + iVar8) & 1) != 0) ||
       (uVar5 = 0x80, (*(uint *)(&DISPENV_800d0e54.isinter + iVar8) & 2) != 0)) {
      puVar7[4] = uVar5;
    }
    if ((*(uint *)&(&DISPENV_800d0e54)[pad].isinter & 4) == 0) {
      if ((*(uint *)&(&DISPENV_800d0e54)[pad].isinter & 8) != 0) {
        *(undefined4 *)(pad * 0x14 + in_t3 + 0xc) = 0x80;
      }
    }
    else {
      *(undefined4 *)(pad * 0x14 + in_t3 + 0xc) = 0xffffff80;
    }
  }
  pMVar1 = (MATRIX *)(draw[0].dr_env.code[0] & 0x40000);
  if ((pMVar1 == (MATRIX *)0x0) &&
     (pMVar1 = (MATRIX *)(pad * 4), (draw[0].dr_env.code[1] & 0x2000000) != 0)) {
    pMVar1 = (MATRIX *)(*(uint *)(pad * 0x14 + in_t3) & 0x300);
    puVar2 = (uint *)(pad * 0x14 + in_t4);
    if (pMVar1 == (MATRIX *)0x300) {
      *puVar2 = *puVar2 & 0xfffff3ff | 0x40000000;
      if ((puVar2[1] & 0xc00) != 0) {
        puVar2[1] = puVar2[1] | 0x40000000;
      }
      pMVar1 = (MATRIX *)(puVar2[1] & 0xfffff3ff);
      *(MATRIX **)(puVar2 + 1) = pMVar1;
    }
  }
  return pMVar1;
}



// decompiled code
// original method signature: 
// struct GameTracker * /*$ra*/ GAMELOOP_GetGT()
 // line 3720, offset 0x80030f5c
	/* begin block 1 */
		// Start line: 8672
	/* end block 1 */
	// End Line: 8673

	/* begin block 2 */
		// Start line: 8673
	/* end block 2 */
	// End Line: 8674

/* WARNING: Unknown calling convention yet parameter storage is locked */

GameTracker * GAMELOOP_GetGT(void)

{
  int in_v0;
  uint *puVar1;
  int iVar2;
  int iVar3;
  GameTracker *pGVar4;
  uint uVar5;
  short *psVar6;
  int in_a2;
  uint *puVar7;
  int iVar8;
  uint in_t1;
  uint in_t2;
  int in_t3;
  int in_t4;
  
  if (in_v0 != 0) {
    in_t2 = 0x80;
  }
  if ((int)in_t1 < -0x37) {
    puVar1 = (uint *)(in_a2 * 0x14 + in_t3);
    uVar5 = *puVar1 | 1;
LAB_80030fb4:
    *puVar1 = uVar5;
  }
  else {
    if (0x37 < (int)in_t1) {
      puVar1 = (uint *)(in_a2 * 0x14 + in_t3);
      uVar5 = *puVar1 | 2;
      goto LAB_80030fb4;
    }
  }
  if ((int)in_t2 < -0x37) {
    puVar1 = (uint *)(in_a2 * 0x14 + in_t3);
    uVar5 = *puVar1 | 4;
  }
  else {
    iVar2 = in_a2 * 4;
    if ((int)in_t2 < 0x38) goto LAB_80031008;
    puVar1 = (uint *)(in_a2 * 0x14 + in_t3);
    uVar5 = *puVar1 | 8;
  }
  *puVar1 = uVar5;
  iVar2 = in_a2 << 2;
LAB_80031008:
  iVar2 = iVar2 + in_a2;
  iVar8 = iVar2 * 4;
  psVar6 = &fontTracker.font_buffer[0xc3].y + in_a2;
  puVar7 = (uint *)(iVar8 + in_t3);
  puVar7[1] = ~(int)*psVar6 & *puVar7;
  *psVar6 = *(short *)puVar7;
  puVar1 = (uint *)(iVar8 + in_t4);
  puVar1[3] = in_t2;
  puVar1[4] = in_t1;
  if ((draw[1].dr_env.code[9] & 0x10) == 0) {
    iVar2 = 0;
    if ((draw[1].dr_env.code[9] & 1) != 0) {
                    /* WARNING: Subroutine does not return */
      FUN_800bcdac(0x800d0e14,0,0x28);
    }
    puVar1[1] = ~*puVar1 & *puVar7;
    *puVar1 = *puVar7;
    iVar8 = 0;
    if ((*puVar7 & 1) == 0) {
      if ((*puVar7 & 2) != 0) {
        iVar8 = 0x80;
      }
    }
    else {
      iVar8 = -0x80;
    }
    uVar5 = *(uint *)(in_a2 * 0x14 + in_t3);
    if ((uVar5 & 4) == 0) {
      if ((uVar5 & 8) != 0) {
        iVar2 = 0x80;
      }
    }
    else {
      iVar2 = -0x80;
    }
    if ((iVar2 != 0) || (iVar8 != 0)) {
      iVar3 = in_a2 * 0x14 + in_t3;
      *(int *)(iVar3 + 0xc) = iVar2;
      *(int *)(iVar3 + 0x10) = iVar8;
    }
  }
  else {
    puVar1[1] = ~*puVar1 & *(uint *)(&DISPENV_800d0e54.isinter + iVar8);
    *puVar1 = *(uint *)(&DISPENV_800d0e54.isinter + iVar8);
    puVar7[3] = *(uint *)(&draw[0].clip.w + iVar2 * 2);
    puVar7[4] = *(uint *)(draw[0].ofs + iVar2 * 2);
    uVar5 = 0xffffff80;
    if (((*(uint *)(&DISPENV_800d0e54.isinter + iVar8) & 1) != 0) ||
       (uVar5 = 0x80, (*(uint *)(&DISPENV_800d0e54.isinter + iVar8) & 2) != 0)) {
      puVar7[4] = uVar5;
    }
    if ((*(uint *)&(&DISPENV_800d0e54)[in_a2].isinter & 4) == 0) {
      if ((*(uint *)&(&DISPENV_800d0e54)[in_a2].isinter & 8) != 0) {
        *(undefined4 *)(in_a2 * 0x14 + in_t3 + 0xc) = 0x80;
      }
    }
    else {
      *(undefined4 *)(in_a2 * 0x14 + in_t3 + 0xc) = 0xffffff80;
    }
  }
  pGVar4 = (GameTracker *)(draw[0].dr_env.code[0] & 0x40000);
  if ((pGVar4 == (GameTracker *)0x0) &&
     (pGVar4 = (GameTracker *)(in_a2 * 4), (draw[0].dr_env.code[1] & 0x2000000) != 0)) {
    pGVar4 = (GameTracker *)(*(uint *)(in_a2 * 0x14 + in_t3) & 0x300);
    puVar1 = (uint *)(in_a2 * 0x14 + in_t4);
    if (pGVar4 == (GameTracker *)0x300) {
      *puVar1 = *puVar1 & 0xfffff3ff | 0x40000000;
      if ((puVar1[1] & 0xc00) != 0) {
        puVar1[1] = puVar1[1] | 0x40000000;
      }
      pGVar4 = (GameTracker *)(puVar1[1] & 0xfffff3ff);
      *(GameTracker **)(puVar1 + 1) = pGVar4;
    }
  }
  return pGVar4;
}





