#include "THISDUST.H"
#include "SAVEINFO.H"


// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_GetInstanceRotation(struct _Instance *instance /*$s0*/, struct _SmallRotation *vector /*$s1*/)
 // line 103, offset 0x800b5560
	/* begin block 1 */
		// Start line: 104
		// Start offset: 0x800B5560
		// Variables:
	// 		struct evPositionData *rotation; // $v1
	/* end block 1 */
	// End offset: 0x800B55D4
	// End Line: 121

	/* begin block 2 */
		// Start line: 191
	/* end block 2 */
	// End Line: 192

	/* begin block 3 */
		// Start line: 206
	/* end block 3 */
	// End Line: 207

void SAVE_GetInstanceRotation(_Instance *instance,_SmallRotation *vector)

{
  uchar *uv;
  uchar *puVar1;
  UW_ScreenXY *p0;
  int tx;
  int iVar2;
  int unaff_s4;
  undefined uStack0000001b;
  undefined uStack0000001c;
  undefined uStack0000001d;
  undefined uStack0000001e;
  undefined uStack0000001f;
  undefined2 uStack00000020;
  undefined2 uStack00000022;
  undefined2 uStack00000024;
  undefined2 uStack00000026;
  undefined2 uStack00000028;
  undefined2 uStack0000002a;
  undefined2 uStack0000002c;
  undefined2 uStack0000002e;
  undefined uStack00000033;
  undefined4 uStack00000034;
  
  p0 = (UW_ScreenXY *)&stack0x00000010;
  FUN_8005b490();
  fontTracker.font_buffer[192].x = *(short *)(unaff_s4 + 0x178);
  *(undefined2 *)(unaff_s4 + 0xd0) = 10;
  *(undefined2 *)(unaff_s4 + 0xce) = 0x1e;
  *(undefined2 *)(unaff_s4 + 0xcc) = 0x1e;
  while (puVar1 = (uchar *)FUN_8005fd78(), puVar1 != (uchar *)0x0) {
    UNDERWORLD_DoUV(uv,p0,tx);
    uv = puVar1;
  }
  iVar2 = 0;
  uStack00000033 = 1;
  uStack0000001b = 5;
  uStack00000034 = 0xe1000740;
  uStack0000002a = 0xf0;
  uStack0000002e = 0xf0;
  uStack0000001c = 8;
  uStack0000001d = 8;
  uStack0000001e = 8;
  uStack00000020 = 0;
  uStack00000022 = 0;
  uStack00000024 = 0x200;
  uStack00000026 = 0;
  uStack00000028 = 0;
  uStack0000002c = 0x200;
  uStack0000001f = 0x2a;
  do {
    FUN_800bce6c(0);
    FUN_800bad08(&stack0x00000030);
    FUN_800bad08(&stack0x00000018);
    iVar2 = iVar2 + 1;
  } while (iVar2 < 0x1e);
                    /* WARNING: Subroutine does not return */
  FUN_800ba930(0);
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_ClearMemory(struct GameTracker *gameTracker /*$a0*/)
 // line 124, offset 0x800b55e8
	/* begin block 1 */
		// Start line: 125
		// Start offset: 0x800B55E8
		// Variables:
	// 		char *buffer; // $v0
	/* end block 1 */
	// End offset: 0x800B55E8
	// End Line: 125

	/* begin block 2 */
		// Start line: 233
	/* end block 2 */
	// End Line: 234

void SAVE_ClearMemory(GameTracker *gameTracker)

{
  int unaff_s1;
  undefined uStack0000001f;
  undefined2 uStack00000020;
  undefined2 uStack00000022;
  undefined2 uStack00000026;
  undefined2 uStack00000028;
  
  uStack00000020 = 0;
  uStack00000022 = 0;
  uStack00000026 = 0;
  uStack00000028 = 0;
  uStack0000001f = 0x2a;
  do {
    FUN_800bce6c(0);
    FUN_800bad08(&stack0x00000030);
    FUN_800bad08(&stack0x00000018);
    unaff_s1 = unaff_s1 + 1;
  } while (unaff_s1 < 0x1e);
                    /* WARNING: Subroutine does not return */
  FUN_800ba930(0);
}



// autogenerated function stub: 
// void /*$ra*/ SAVE_Init(struct GameTracker *gt /*$s0*/)
void SAVE_Init(struct GameTracker *gt)
{ // line 148, offset 0x800b5668
	/* begin block 1 */
		// Start line: 149
		// Start offset: 0x800B5668
		// Variables:
			void *buffer; // $s1

		/* begin block 1.1 */
			// Start line: 158
			// Start offset: 0x800B5698
		/* end block 1.1 */
		// End offset: 0x800B5698
		// End Line: 160
	/* end block 1 */
	// End offset: 0x800B56CC
	// End Line: 169

	/* begin block 2 */
		// Start line: 302
	/* end block 2 */
	// End Line: 303

}


// autogenerated function stub: 
// void * /*$ra*/ SAVE_GetSavedBlock(long saveType /*$s3*/, long extraSize /*$s0*/)
void * SAVE_GetSavedBlock(long saveType, long extraSize)
{ // line 189, offset 0x800b56ec
	/* begin block 1 */
		// Start line: 190
		// Start offset: 0x800B56EC
		// Variables:
			struct SavedBasic *savedInfo; // $s2
			long sizeOfSave; // $s0
			long done; // $s1
	/* end block 1 */
	// End offset: 0x800B57E8
	// End Line: 232

	/* begin block 2 */
		// Start line: 386
	/* end block 2 */
	// End Line: 387

	return null;
}


// decompiled code
// original method signature: 
// long /*$ra*/ SAVE_PurgeAMemoryBlock()
 // line 237, offset 0x800b5808
	/* begin block 1 */
		// Start line: 238
		// Start offset: 0x800B5808
		// Variables:
	// 		struct SavedBasic *curSave; // $a0
	// 		long result; // $a1
	/* end block 1 */
	// End offset: 0x800B5898
	// End Line: 259

	/* begin block 2 */
		// Start line: 488
	/* end block 2 */
	// End Line: 489

/* WARNING: Unknown calling convention yet parameter storage is locked */

long SAVE_PurgeAMemoryBlock(void)

{
  long lVar1;
  int in_a0;
  int unaff_s0;
  undefined4 unaff_s1;
  undefined4 uStack00000010;
  
  *(int *)(unaff_s0 + 0x24) = in_a0 + -0x6dc8;
  uStack00000010 = 0x6000;
  the_header_size = FUN_800b9bcc();
  _G2AnimInterpInfo_Type_ARRAY_800d57e0[0]._0_4_ = unaff_s1;
  lVar1 = FUN_800b5754();
  return lVar1;
}



// decompiled code
// original method signature: 
// long /*$ra*/ SAVE_SaveableInstance(struct _Instance *instance /*$a0*/)
 // line 265, offset 0x800b58a8
	/* begin block 1 */
		// Start line: 267
		// Start offset: 0x800B58A8
		// Variables:
	// 		long result; // $a1
	/* end block 1 */
	// End offset: 0x800B599C
	// End Line: 320

	/* begin block 2 */
		// Start line: 551
	/* end block 2 */
	// End Line: 552

	/* begin block 3 */
		// Start line: 552
	/* end block 3 */
	// End Line: 553

	/* begin block 4 */
		// Start line: 554
	/* end block 4 */
	// End Line: 555

long SAVE_SaveableInstance(_Instance *instance)

{
  bool bVar1;
  _G2AnimInterpStateBlock_Type *p_Var2;
  int in_v0;
  int iVar3;
  int iVar4;
  int unaff_s0;
  int iVar5;
  _G2AnimInterpStateBlock_Type *unaff_s2;
  undefined unaff_s3;
  
  iVar3 = in_v0 + unaff_s0 + 3 >> 2;
  iVar5 = iVar3 * 4;
  bVar1 = false;
  if (0x3fc < iVar5) {
                    /* WARNING: Subroutine does not return */
    FUN_80014454(0x800cfb38,iVar5);
  }
  do {
    p_Var2 = _G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList;
    if (&(_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList)->next + iVar3 <
        _G2AnimInterpInfo_Type_ARRAY_800d57e0[1]._0_4_) {
      *(undefined *)&(_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList)->next = unaff_s3;
      *(undefined *)((int)&p_Var2->next + 1) = (char)(iVar5 >> 2);
      _G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList =
           (_G2AnimInterpStateBlock_Type *)
           (&(_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList)->next + iVar3);
      bVar1 = true;
      unaff_s2 = p_Var2;
    }
    else {
      iVar4 = FUN_800b5974();
      if (iVar4 == 0) {
                    /* WARNING: Subroutine does not return */
        FUN_80014454(&DAT_800cfb58,iVar5,
                     (_G2AnimInterpStateBlock_Type **)
                     ((int)_G2AnimInterpInfo_Type_ARRAY_800d57e0[1]._0_4_ -
                     (int)_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList),0x6000);
      }
    }
  } while (!bVar1);
  return (long)unaff_s2;
}



// decompiled code
// original method signature: 
// struct _SavedIntro * /*$ra*/ SAVE_UpdateSavedIntro(struct _Instance *instance /*$s1*/, struct Level *level /*$a1*/, struct _SavedIntro *savedIntro /*$s0*/, struct evControlSaveDataData *extraData /*$s2*/)
 // line 471, offset 0x800b59a4
	/* begin block 1 */
		// Start line: 472
		// Start offset: 0x800B59A4
		// Variables:
	// 		struct _Position *levelOffset; // $t1

		/* begin block 1.1 */
			// Start line: 483
			// Start offset: 0x800B59D4
			// Variables:
		// 		short _x0; // $v0
		// 		short _y0; // $a2
		// 		short _z0; // $v1
		// 		short _x1; // $a3
		// 		short _y1; // $t0
		// 		short _z1; // $t1
		// 		struct _Position *_v; // $v0
		// 		struct _Position *_v0; // $v1
		/* end block 1.1 */
		// End offset: 0x800B59D4
		// End Line: 483
	/* end block 1 */
	// End offset: 0x800B5A94
	// End Line: 510

	/* begin block 2 */
		// Start line: 942
	/* end block 2 */
	// End Line: 943

_SavedIntro *
SAVE_UpdateSavedIntro
          (_Instance *instance,Level *level,_SavedIntro *savedIntro,evControlSaveDataData *extraData
          )

{
  _SavedIntro *in_v1;
  
  while (((uint)instance->data & 0x100) == 0) {
    do {
      if ((in_v1 == savedIntro) && ((instance->instanceID & 0x100U) != 0)) goto LAB_800b59d8;
      instance = (_Instance *)
                 (&(instance->node).prev + (uint)*(byte *)((int)&(instance->node).prev + 1));
      if (_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList <= instance) {
        return (_SavedIntro *)level;
      }
      in_v1 = (_SavedIntro *)(uint)*(byte *)&(instance->node).prev;
    } while (in_v1 != (_SavedIntro *)extraData);
  }
LAB_800b59d8:
  FUN_800b6504();
  return (_SavedIntro *)&DAT_00000001;
}



// decompiled code
// original method signature: 
// struct _SavedIntroWithIntro * /*$ra*/ SAVE_UpdateSavedIntroWithIntro(struct _Instance *instance /*$s1*/, struct Level *level /*$a1*/, struct _SavedIntroWithIntro *savedIntro /*$s0*/, struct evControlSaveDataData *extraData /*$s2*/)
 // line 513, offset 0x800b5ab0
	/* begin block 1 */
		// Start line: 514
		// Start offset: 0x800B5AB0
		// Variables:
	// 		struct _Position *levelOffset; // $t1

		/* begin block 1.1 */
			// Start line: 525
			// Start offset: 0x800B5AF0
			// Variables:
		// 		short _x0; // $v0
		// 		short _y0; // $a2
		// 		short _z0; // $v1
		// 		short _x1; // $a3
		// 		short _y1; // $t0
		// 		short _z1; // $t1
		// 		struct _Position *_v; // $v0
		// 		struct _Position *_v0; // $v1
		/* end block 1.1 */
		// End offset: 0x800B5AF0
		// End Line: 525
	/* end block 1 */
	// End offset: 0x800B5BCC
	// End Line: 553

	/* begin block 2 */
		// Start line: 916
	/* end block 2 */
	// End Line: 917

_SavedIntroWithIntro *
SAVE_UpdateSavedIntroWithIntro
          (_Instance *instance,Level *level,_SavedIntroWithIntro *savedIntro,
          evControlSaveDataData *extraData)

{
  uint in_v0;
  
  if ((in_v0 & 0x100000) != 0) {
    level = (Level *)0x0;
  }
  if ((((level == (Level *)&DAT_00000001) &&
       (instance->currentStreamUnitID == instance->birthStreamUnitID)) &&
      (instance->introUniqueID < 0x2000)) && (instance->intro != (Intro *)0x0)) {
    level = (Level *)&DAT_00000002;
  }
  return (_SavedIntroWithIntro *)level;
}



// decompiled code
// original method signature: 
// struct SavedBasic * /*$ra*/ SAVE_GetSavedEvent(long areaID /*$a0*/, long eventNumber /*$a1*/)
 // line 556, offset 0x800b5be8
	/* begin block 1 */
		// Start line: 558
		// Start offset: 0x800B5BE8
		// Variables:
	// 		struct SavedBasic *curSave; // $v1
	/* end block 1 */
	// End offset: 0x800B5C88
	// End Line: 577

	/* begin block 2 */
		// Start line: 1022
	/* end block 2 */
	// End Line: 1023

	/* begin block 3 */
		// Start line: 1023
	/* end block 3 */
	// End Line: 1024

	/* begin block 4 */
		// Start line: 1025
	/* end block 4 */
	// End Line: 1026

SavedBasic * SAVE_GetSavedEvent(long areaID,long eventNumber)

{
  SavedBasic in_v0;
  SavedBasic *unaff_s0;
  undefined4 *unaff_s2;
  
  unaff_s0[9] = in_v0;
  if (unaff_s2 != (undefined4 *)0x0) {
    FUN_8007919c(unaff_s0 + 0x14,unaff_s2[1],*unaff_s2);
  }
  return unaff_s0;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_DeleteSavedEvent(long areaID /*$a0*/, long eventNumber /*$a1*/)
 // line 579, offset 0x800b5c90
	/* begin block 1 */
		// Start line: 580
		// Start offset: 0x800B5C90
		// Variables:
	// 		struct SavedBasic *savedEvent; // $v0
	/* end block 1 */
	// End offset: 0x800B5CB0
	// End Line: 589

	/* begin block 2 */
		// Start line: 1068
	/* end block 2 */
	// End Line: 1069

void SAVE_DeleteSavedEvent(long areaID,long eventNumber)

{
  short sVar1;
  short sVar2;
  short sVar3;
  short sVar4;
  int in_v0;
  int in_a3;
  int in_t1;
  int unaff_s0;
  int unaff_s1;
  undefined4 *unaff_s2;
  
  *(undefined2 *)(unaff_s0 + 4) = (short)(-in_v0 >> 2);
  *(undefined2 *)(unaff_s0 + 8) = *(undefined2 *)(unaff_s1 + 0x3c);
  *(undefined2 *)(unaff_s0 + 6) = *(undefined2 *)(unaff_s1 + 0x34);
  sVar1 = *(short *)(unaff_s1 + 0x5e);
  sVar2 = *(short *)(unaff_s1 + 0x60);
  sVar3 = *(short *)(in_t1 + 2);
  sVar4 = *(short *)(in_t1 + 4);
  *(short *)(unaff_s0 + 0x1a) = *(short *)(unaff_s1 + 0x5c) - *(short *)(in_a3 + 0xc);
  *(short *)(unaff_s0 + 0x1c) = sVar1 - sVar3;
  *(short *)(unaff_s0 + 0x1e) = sVar2 - sVar4;
  FUN_800b56cc(areaID,unaff_s0 + 0x14);
  *(undefined4 *)(unaff_s0 + 0xc) = *(undefined4 *)(unaff_s1 + 0x14);
  *(undefined4 *)(unaff_s0 + 0x10) = *(undefined4 *)(unaff_s1 + 0x18);
  *(undefined *)(unaff_s0 + 0xb) = *(undefined *)(unaff_s1 + 0x6a);
  *(undefined *)(unaff_s0 + 10) = *(undefined *)(unaff_s1 + 0x62);
  *(undefined2 *)(unaff_s0 + 2) = *(undefined2 *)(unaff_s1 + 0x8c);
  if (unaff_s2 != (undefined4 *)0x0) {
    FUN_8007919c(unaff_s0 + 0x20,unaff_s2[1],*unaff_s2);
  }
  return;
}



// decompiled code
// original method signature: 
// struct SavedBasic * /*$ra*/ SAVE_GetSavedNextEvent(long areaID /*$a0*/, struct SavedBasic *curSave /*$a1*/)
 // line 591, offset 0x800b5cc0
	/* begin block 1 */
		// Start line: 1092
	/* end block 1 */
	// End Line: 1093

	/* begin block 2 */
		// Start line: 1093
	/* end block 2 */
	// End Line: 1094

SavedBasic * SAVE_GetSavedNextEvent(long areaID,SavedBasic *curSave)

{
  short sVar1;
  short sVar2;
  short in_v0;
  short in_v1;
  short in_a2;
  int in_a3;
  int in_t1;
  SavedBasic *unaff_s0;
  int unaff_s1;
  undefined4 *unaff_s2;
  
  sVar1 = *(short *)(in_t1 + 2);
  sVar2 = *(short *)(in_t1 + 4);
  *(short *)(unaff_s0 + 0xd) = in_v0 - *(short *)(in_a3 + 0xc);
  *(short *)(unaff_s0 + 0xe) = in_a2 - sVar1;
  *(short *)(unaff_s0 + 0xf) = in_v1 - sVar2;
  FUN_800b56cc();
  *(undefined4 *)(unaff_s0 + 6) = *(undefined4 *)(unaff_s1 + 0x14);
  *(undefined4 *)(unaff_s0 + 8) = *(undefined4 *)(unaff_s1 + 0x18);
  unaff_s0[5].shiftedSaveSize = *(uchar *)(unaff_s1 + 0x6a);
  unaff_s0[5].savedID = *(uchar *)(unaff_s1 + 0x62);
  unaff_s0[1] = *(SavedBasic *)(unaff_s1 + 0x8c);
  if (unaff_s2 != (undefined4 *)0x0) {
    FUN_8007919c(unaff_s0 + 0x10,unaff_s2[1],*unaff_s2);
  }
  return unaff_s0;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_BufferIntro(struct SavedBasic *savedIntro /*$a0*/)
 // line 619, offset 0x800b5d64
	/* begin block 1 */
		// Start line: 621
		// Start offset: 0x800B5D64
		// Variables:
	// 		long i; // $a1
	/* end block 1 */
	// End offset: 0x800B5DDC
	// End Line: 655

	/* begin block 2 */
		// Start line: 1148
	/* end block 2 */
	// End Line: 1149

	/* begin block 3 */
		// Start line: 1149
	/* end block 3 */
	// End Line: 1150

	/* begin block 4 */
		// Start line: 1151
	/* end block 4 */
	// End Line: 1152

void SAVE_BufferIntro(SavedBasic *savedIntro)

{
  char cVar1;
  int in_v0;
  char *in_v1;
  uint in_a1;
  char *in_a2;
  
  if (in_v0 != 0) {
    do {
      cVar1 = *in_v1;
      if (cVar1 == '\x02') {
        if (((SavedBasic *)(int)*(short *)(in_v1 + 2) == savedIntro) &&
           ((int)*(short *)(in_v1 + 4) == in_a1)) {
          return;
        }
        cVar1 = *in_v1;
      }
      if (((cVar1 == '\t') && ((SavedBasic *)(int)*(short *)(in_v1 + 2) == savedIntro)) &&
         ((uint)(byte)in_v1[4] == in_a1)) {
        return;
      }
      in_v1 = in_v1 + (uint)(byte)in_v1[1] * 4;
    } while (in_v1 < in_a2);
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_IntroduceBufferIntros()
 // line 657, offset 0x800b5de4
	/* begin block 1 */
		// Start line: 658
		// Start offset: 0x800B5DE4
		// Variables:
	// 		long i; // $s2
	// 		struct _StreamUnit *streamUnit; // $v0

		/* begin block 1.1 */
			// Start line: 664
			// Start offset: 0x800B5E10
			// Variables:
		// 		int deleted; // stack offset -24

			/* begin block 1.1.1 */
				// Start line: 670
				// Start offset: 0x800B5E38
			/* end block 1.1.1 */
			// End offset: 0x800B5E60
			// End Line: 686

			/* begin block 1.1.2 */
				// Start line: 692
				// Start offset: 0x800B5E60
			/* end block 1.1.2 */
			// End offset: 0x800B5E98
			// End Line: 711
		/* end block 1.1 */
		// End offset: 0x800B5E98
		// End Line: 713
	/* end block 1 */
	// End offset: 0x800B5EA8
	// End Line: 714

	/* begin block 2 */
		// Start line: 1232
	/* end block 2 */
	// End Line: 1233

	/* begin block 3 */
		// Start line: 1236
	/* end block 3 */
	// End Line: 1237

/* WARNING: Unknown calling convention yet parameter storage is locked */

void SAVE_IntroduceBufferIntros(void)

{
  uint uVar1;
  int in_v0;
  byte *in_v1;
  int in_a0;
  uint in_a1;
  byte *in_a2;
  uint in_a3;
  uint in_t0;
  
  while( true ) {
    in_v1 = in_v1 + in_v0;
    if (in_a2 <= in_v1) {
      return;
    }
    uVar1 = (uint)*in_v1;
    if (uVar1 == in_t0) {
      if (((int)*(short *)(in_v1 + 2) == in_a0) && ((int)*(short *)(in_v1 + 4) == in_a1)) {
        return;
      }
      uVar1 = (uint)*in_v1;
    }
    if (((uVar1 == in_a3) && ((int)*(short *)(in_v1 + 2) == in_a0)) && ((uint)in_v1[4] == in_a1))
    break;
    in_v0 = (uint)in_v1[1] << 2;
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_IntroForStreamID(struct _StreamUnit *streamUnit /*$s2*/)
 // line 716, offset 0x800b5ec0
	/* begin block 1 */
		// Start line: 717
		// Start offset: 0x800B5EC0
		// Variables:
	// 		struct SavedBasic *saveIntro; // $s0
	// 		long streamID; // $s1
	// 		int deleted; // stack offset -24
	/* end block 1 */
	// End offset: 0x800B5F84
	// End Line: 741

	/* begin block 2 */
		// Start line: 1410
	/* end block 2 */
	// End Line: 1411

void SAVE_IntroForStreamID(_StreamUnit *streamUnit)

{
  uint in_v0;
  byte *in_a1;
  byte *in_a2;
  uint in_a3;
  uint in_t0;
  
  while( true ) {
    if (in_v0 == 0) {
      return;
    }
    if ((((uint)*in_a1 == in_t0) && ((_StreamUnit *)(int)*(short *)(in_a1 + 2) == streamUnit)) ||
       (((uint)*in_a1 == in_a3 && ((_StreamUnit *)(int)*(short *)(in_a1 + 2) == streamUnit))))
    break;
    in_a1 = in_a1 + (uint)in_a1[1] * 4;
    in_v0 = (uint)(in_a1 < in_a2);
  }
  return;
}



// decompiled code
// original method signature: 
// long /*$ra*/ SAVE_HasSavedIntro(struct Intro *intro /*$a0*/, long currentStreamID /*$a1*/)
 // line 743, offset 0x800b5f9c
	/* begin block 1 */
		// Start line: 745
		// Start offset: 0x800B5F9C
		// Variables:
	// 		long result; // $a3
	// 		struct _SavedIntro *saveIntro; // $a1
	/* end block 1 */
	// End offset: 0x800B6024
	// End Line: 767

	/* begin block 2 */
		// Start line: 1472
	/* end block 2 */
	// End Line: 1473

	/* begin block 3 */
		// Start line: 1473
	/* end block 3 */
	// End Line: 1474

	/* begin block 4 */
		// Start line: 1476
	/* end block 4 */
	// End Line: 1477

long SAVE_HasSavedIntro(Intro *intro,long currentStreamID)

{
  uint in_v0;
  int iVar1;
  uint in_v1;
  _G2AnimAlphaTable_Type *unaff_s0;
  _G2AnimAlphaTable_Type **unaff_s1;
  int unaff_s2;
  
  do {
    if (in_v1 == in_v0) {
      iVar1 = FUN_80059398((int)*(short *)&unaff_s0[3].field_0x2);
      if (iVar1 == 0) goto LAB_800b5ff4;
      iVar1 = FUN_800346ac(unaff_s0,iVar1,&stack0x00000010);
LAB_800b5fec:
      if (iVar1 != 0) goto LAB_800b5ff4;
    }
    else {
      iVar1 = FUN_80059398((int)*(short *)&unaff_s0[1].field_0x2);
      if (iVar1 != 0) {
        iVar1 = FUN_80034b24(unaff_s0,iVar1,&stack0x00000010);
        goto LAB_800b5fec;
      }
LAB_800b5ff4:
      *unaff_s1 = (_G2AnimAlphaTable_Type *)0x0;
      numbufferedIntros = numbufferedIntros + -1;
    }
    do {
      unaff_s2 = unaff_s2 + 1;
      if (numbufferedIntros == 0) {
        return 0;
      }
      if (unaff_s2 >= 0x40) {
        return (uint)(unaff_s2 < 0x40);
      }
      unaff_s1 = &_G2AnimInterpInfo_Type_ARRAY_800d57e0[1].alphaTable + unaff_s2;
      unaff_s0 = *unaff_s1;
      in_v0 = 1;
    } while (unaff_s0 == (_G2AnimAlphaTable_Type *)0x0);
    in_v1 = (uint)*(byte *)&unaff_s0->size;
  } while( true );
}



// decompiled code
// original method signature: 
// struct SavedLevel * /*$ra*/ SAVE_HasSavedLevel(long areaID /*$a0*/)
 // line 795, offset 0x800b602c
	/* begin block 1 */
		// Start line: 797
		// Start offset: 0x800B602C
		// Variables:
	// 		struct SavedLevel *savedLevel; // $v1
	/* end block 1 */
	// End offset: 0x800B6080
	// End Line: 812

	/* begin block 2 */
		// Start line: 1581
	/* end block 2 */
	// End Line: 1582

	/* begin block 3 */
		// Start line: 1582
	/* end block 3 */
	// End Line: 1583

	/* begin block 4 */
		// Start line: 1584
	/* end block 4 */
	// End Line: 1585

SavedLevel * SAVE_HasSavedLevel(long areaID)

{
  bool bVar1;
  _G2AnimInterpStateBlock_Type *p_Var2;
  int iVar3;
  int local_18 [2];
  
  iVar3 = *(int *)areaID;
  bVar1 = _G2AnimInterpInfo_Type_ARRAY_800d57e0[0].alphaTable <
          _G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList;
  p_Var2 = (_G2AnimInterpStateBlock_Type *)_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].alphaTable;
  if (bVar1) {
    do {
      local_18[0] = 0;
      if ((*(char *)&p_Var2->next == '\x01') && ((int)p_Var2->quatInfo[0].destQuat.y == iVar3)) {
        FUN_800346ac(p_Var2,areaID,local_18);
      }
      else {
        if ((*(char *)&p_Var2->next == '\a') && ((int)p_Var2->quatInfo[0].srcQuat.y == iVar3)) {
          FUN_80034b24(p_Var2,areaID,local_18);
        }
      }
      if (local_18[0] == 0) {
        p_Var2 = (_G2AnimInterpStateBlock_Type *)
                 (&p_Var2->next + (uint)*(byte *)((int)&p_Var2->next + 1));
      }
      bVar1 = p_Var2 < _G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList;
    } while (bVar1);
  }
  return (SavedLevel *)(uint)bVar1;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_UpdateLevelWithSave(struct _StreamUnit *streamUnit /*$s0*/)
 // line 814, offset 0x800b6090
	/* begin block 1 */
		// Start line: 815
		// Start offset: 0x800B6090
		// Variables:
	// 		long i; // $t2
	// 		struct ActualSavedLevel *savedLevel; // $t3
	// 		struct _Terrain *terrain; // $t4
	// 		struct BSPTree *bspTree; // $v1
	// 		long Zoffset; // $s1
	/* end block 1 */
	// End offset: 0x800B61C8
	// End Line: 858

	/* begin block 2 */
		// Start line: 1619
	/* end block 2 */
	// End Line: 1620

void SAVE_UpdateLevelWithSave(_StreamUnit *streamUnit)

{
  _G2AnimInterpStateBlock_Type *unaff_s0;
  int unaff_s1;
  int in_stack_00000010;
  
  while( true ) {
    if (in_stack_00000010 == 0) {
      unaff_s0 = (_G2AnimInterpStateBlock_Type *)
                 (&unaff_s0->next + (uint)*(byte *)((int)&unaff_s0->next + 1));
    }
    if (_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList <= unaff_s0) break;
    in_stack_00000010 = 0;
    if ((*(char *)&unaff_s0->next == '\x01') && ((int)unaff_s0->quatInfo[0].destQuat.y == unaff_s1))
    {
      FUN_800346ac(unaff_s0);
    }
    else {
      if ((*(char *)&unaff_s0->next == '\a') && ((int)unaff_s0->quatInfo[0].srcQuat.y == unaff_s1))
      {
        FUN_80034b24(unaff_s0);
      }
    }
  }
  return;
}



// decompiled code
// original method signature: 
// struct SavedLevel * /*$ra*/ SAVE_CreatedSavedLevel(long areaID /*$s3*/, struct Level *level /*$s2*/)
 // line 860, offset 0x800b61dc
	/* begin block 1 */
		// Start line: 861
		// Start offset: 0x800B61DC
		// Variables:
	// 		struct SavedLevel *savedLevel; // $s0
	// 		struct ActualSavedLevel *slevel; // $a0
	// 		long doSave; // $a1
	// 		long i; // $a1
	// 		struct BSPTree *bspTree; // $v1
	// 		long Zoffset; // $s4

		/* begin block 1.1 */
			// Start line: 881
			// Start offset: 0x800B623C
			// Variables:
		// 		long numBSPTrees; // $s1

			/* begin block 1.1.1 */
				// Start line: 886
				// Start offset: 0x800B6258
			/* end block 1.1.1 */
			// End offset: 0x800B6350
			// End Line: 931
		/* end block 1.1 */
		// End offset: 0x800B6350
		// End Line: 932
	/* end block 1 */
	// End offset: 0x800B6374
	// End Line: 943

	/* begin block 2 */
		// Start line: 1738
	/* end block 2 */
	// End Line: 1739

SavedLevel * SAVE_CreatedSavedLevel(long areaID,Level *level)

{
  int in_v0;
  Level *in_v1;
  uint in_a2;
  
  while( true ) {
    in_v1 = (Level *)((int)&in_v1->terrain + in_v0);
    if (level <= in_v1) {
      return (SavedLevel *)0x0;
    }
    if (((uint)*(byte *)&in_v1->terrain == in_a2) &&
       ((int)*(short *)((int)&in_v1->terrain + 2) == areaID)) break;
    in_v0 = (uint)*(byte *)((int)&in_v1->terrain + 1) << 2;
  }
  return (SavedLevel *)in_v1;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_DeleteBlock(struct SavedBasic *savedBlock /*$a0*/)
 // line 947, offset 0x800b6398
	/* begin block 1 */
		// Start line: 948
		// Start offset: 0x800B6398
		// Variables:
	// 		long size; // $s0
	// 		char *nextBlock; // $a1

		/* begin block 1.1 */
			// Start line: 960
			// Start offset: 0x800B63C0
			// Variables:
		// 		int i; // $a3
		/* end block 1.1 */
		// End offset: 0x800B63FC
		// End Line: 978
	/* end block 1 */
	// End offset: 0x800B63FC
	// End Line: 980

	/* begin block 2 */
		// Start line: 1932
	/* end block 2 */
	// End Line: 1933

/* WARNING: Removing unreachable block (ram,0x800b64c4) */
/* WARNING: Removing unreachable block (ram,0x800b64d8) */

void SAVE_DeleteBlock(SavedBasic *savedBlock)

{
  undefined2 uVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  int *unaff_s2;
  undefined2 unaff_s3;
  short unaff_s4;
  
  iVar5 = *(int *)(*unaff_s2 + 0x44) + -2;
  if ((0 < iVar5) &&
     ((iVar2 = FUN_800b6198(), iVar2 != 0 || (iVar2 = FUN_800b5858(3,iVar5 * 8), iVar2 != 0)))) {
    *(undefined2 *)(iVar2 + 2) = unaff_s3;
    if ((unaff_s2[0xe] == -0x7fff) || (unaff_s2[0xe] == 0x7fff)) {
      *(undefined2 *)(iVar2 + 4) = *(undefined2 *)(unaff_s2 + 0xe);
    }
    else {
      *(short *)(iVar2 + 4) = *(short *)(unaff_s2 + 0xe) - unaff_s4;
    }
    *(undefined2 *)(iVar2 + 6) = (short)iVar5;
    iVar5 = *unaff_s2;
    iVar3 = 0;
    if (0 < *(int *)(iVar5 + 0x44)) {
      iVar4 = 0;
      do {
        iVar5 = *(int *)(iVar5 + 0x48) + iVar4;
        if (1 < (ushort)(*(short *)(iVar5 + 0x1a) + 1U)) {
          *(undefined *)(iVar2 + 0xf) = (char)iVar3;
          uVar1 = *(undefined2 *)(iVar5 + 0x18);
          *(undefined4 *)(iVar2 + 8) = *(undefined4 *)(iVar5 + 0x14);
          *(undefined2 *)(iVar2 + 0xc) = uVar1;
          *(undefined *)(iVar2 + 0xe) = *(undefined *)(iVar5 + 0x12);
          iVar2 = iVar2 + 8;
        }
        iVar5 = *unaff_s2;
        iVar3 = iVar3 + 1;
        iVar4 = iVar4 + 0x24;
      } while (iVar3 < *(int *)(iVar5 + 0x44));
    }
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_Instance(struct _Instance *instance /*$s1*/, struct Level *level /*$s3*/)
 // line 991, offset 0x800b6424
	/* begin block 1 */
		// Start line: 992
		// Start offset: 0x800B6424
		// Variables:
	// 		struct _SavedIntro *savedIntro; // $v0
	// 		struct evControlSaveDataData *extraData; // $s0
	// 		long extraSize; // $s2
	// 		long saveType; // $v1

		/* begin block 1.1 */
			// Start line: 1003
			// Start offset: 0x800B646C
			// Variables:
		// 		struct SavedIntroSmall *savedSmallIntro; // $a0

			/* begin block 1.1.1 */
				// Start line: 1010
				// Start offset: 0x800B648C
			/* end block 1.1.1 */
			// End offset: 0x800B64A4
			// End Line: 1016
		/* end block 1.1 */
		// End offset: 0x800B64A4
		// End Line: 1016

		/* begin block 1.2 */
			// Start line: 1048
			// Start offset: 0x800B6524
			// Variables:
		// 		struct _SavedIntroWithIntro *savedIntroWithIntro; // $v0
		/* end block 1.2 */
		// End offset: 0x800B6558
		// End Line: 1062

		/* begin block 1.3 */
			// Start line: 1069
			// Start offset: 0x800B6578
			// Variables:
		// 		struct SavedIntroSpline *savedIntroSpline; // $s0

			/* begin block 1.3.1 */
				// Start line: 1076
				// Start offset: 0x800B6598
				// Variables:
			// 		struct MultiSpline *multi; // $a1
			/* end block 1.3.1 */
			// End offset: 0x800B663C
			// End Line: 1096
		/* end block 1.3 */
		// End offset: 0x800B663C
		// End Line: 1097
	/* end block 1 */
	// End offset: 0x800B663C
	// End Line: 1102

	/* begin block 2 */
		// Start line: 2041
	/* end block 2 */
	// End Line: 2042

void SAVE_Instance(_Instance *instance,Level *level)

{
  undefined2 uVar1;
  undefined2 in_v0;
  int iVar2;
  int iVar3;
  int iVar4;
  undefined2 unaff_s1;
  int *unaff_s2;
  
  *(undefined2 *)&(instance->node).next = in_v0;
  *(undefined2 *)((int)&(instance->node).next + 2) = unaff_s1;
  iVar2 = *unaff_s2;
  iVar3 = 0;
  if (0 < *(int *)(iVar2 + 0x44)) {
    iVar4 = 0;
    do {
      iVar2 = *(int *)(iVar2 + 0x48) + iVar4;
      if (1 < (ushort)(*(short *)(iVar2 + 0x1a) + 1U)) {
        *(undefined *)((int)&instance->prev + 3) = (char)iVar3;
        uVar1 = *(undefined2 *)(iVar2 + 0x18);
        instance->next = *(_Instance **)(iVar2 + 0x14);
        *(undefined2 *)&instance->prev = uVar1;
        *(undefined *)((int)&instance->prev + 2) = *(undefined *)(iVar2 + 0x12);
        instance = (_Instance *)&instance->next;
      }
      iVar2 = *unaff_s2;
      iVar3 = iVar3 + 1;
      iVar4 = iVar4 + 0x24;
    } while (iVar3 < *(int *)(iVar2 + 0x44));
  }
  return;
}



// autogenerated function stub: 
// void /*$ra*/ SAVE_DeleteInstance(struct _Instance *instance /*$a2*/)
void SAVE_DeleteInstance(struct _Instance *instance)
{ // line 1104, offset 0x800b6658
	/* begin block 1 */
		// Start line: 1105
		// Start offset: 0x800B6658
		// Variables:
			struct SavedBasic *saveIntro; // $a0
	/* end block 1 */
	// End offset: 0x800B6718
	// End Line: 1132

	/* begin block 2 */
		// Start line: 2270
	/* end block 2 */
	// End Line: 2271

}


// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_SetDeadDeadBit(int uniqueID /*$a0*/, long set /*$a1*/)
 // line 1134, offset 0x800b6728
	/* begin block 1 */
		// Start line: 1136
		// Start offset: 0x800B6728
		// Variables:
	// 		struct _SavedIntro *saveIntro; // $a2
	// 		struct SavedDeadDeadBits *deadDeadBits; // $v1

		/* begin block 1.1 */
			// Start line: 1155
			// Start offset: 0x800B6784
			// Variables:
		// 		int deadByte; // $a2
		// 		int deadBit; // $a0
		/* end block 1.1 */
		// End offset: 0x800B67E4
		// End Line: 1177
	/* end block 1 */
	// End offset: 0x800B67E4
	// End Line: 1180

	/* begin block 2 */
		// Start line: 2336
	/* end block 2 */
	// End Line: 2337

	/* begin block 3 */
		// Start line: 2337
	/* end block 3 */
	// End Line: 2338

	/* begin block 4 */
		// Start line: 2340
	/* end block 4 */
	// End Line: 2341

void SAVE_SetDeadDeadBit(int uniqueID,long set)

{
  undefined2 uVar1;
  uint in_v1;
  undefined *unaff_s0;
  int unaff_s1;
  
  *(ushort *)(unaff_s1 + 0x24c) = (ushort)uniqueID;
  if ((*(uint *)(unaff_s1 + 0x14) & in_v1) != 0) {
    *(ushort *)(unaff_s1 + 0x24c) = (ushort)uniqueID | 0x80;
  }
  if ((*(uint *)(unaff_s1 + 0x14) & 0x2000000) != 0) {
    *(ushort *)(unaff_s1 + 0x24c) = *(ushort *)(unaff_s1 + 0x24c) | 0x100;
  }
  *unaff_s0 = 8;
  *(undefined2 *)(unaff_s0 + 2) = *(undefined2 *)(unaff_s1 + 0x3c);
  *(undefined2 *)(unaff_s0 + 4) = *(undefined2 *)(unaff_s1 + 0x24c);
  uVar1 = FUN_800332b0();
  *(undefined2 *)(unaff_s0 + 6) = uVar1;
  *(undefined2 *)(unaff_s0 + 8) = *(undefined2 *)(unaff_s1 + 0x250);
  *(undefined2 *)(unaff_s0 + 10) = *(undefined2 *)(unaff_s1 + 0x252);
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_RestoreGlobalSavePointer()
 // line 1182, offset 0x800b67ec
	/* begin block 1 */
		// Start line: 1184
		// Start offset: 0x800B67EC
		// Variables:
	// 		struct _SavedIntro *saveIntro; // $v1
	/* end block 1 */
	// End offset: 0x800B683C
	// End Line: 1199

	/* begin block 2 */
		// Start line: 2449
	/* end block 2 */
	// End Line: 2450

	/* begin block 3 */
		// Start line: 2450
	/* end block 3 */
	// End Line: 2451

	/* begin block 4 */
		// Start line: 2453
	/* end block 4 */
	// End Line: 2454

/* WARNING: Unknown calling convention yet parameter storage is locked */

void SAVE_RestoreGlobalSavePointer(void)

{
  _G2AnimInterpStateBlock_Type *in_a0;
  uint in_a1;
  int in_a2;
  
  while ((int)in_a0->quatInfo[0].destQuat.x != *(int *)(in_a2 + 0x3c)) {
    do {
      if ((((in_a1 == 7) && ((int)in_a0->quatInfo[0].srcQuat.z == *(int *)(in_a2 + 0x3c))) ||
          ((in_a1 == 5 && ((int)*(short *)((int)&in_a0->next + 2) == *(int *)(in_a2 + 0x3c))))) ||
         ((in_a1 == 8 && ((int)*(short *)((int)&in_a0->next + 2) == *(int *)(in_a2 + 0x3c)))))
      goto LAB_800b6858;
      in_a0 = (_G2AnimInterpStateBlock_Type *)
              (&in_a0->next + (uint)*(byte *)((int)&in_a0->next + 1));
      if (_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList <= in_a0) {
        return;
      }
      in_a1 = (uint)*(byte *)&in_a0->next;
    } while (*(byte *)&in_a0->next != 1);
  }
LAB_800b6858:
  FUN_800b6504();
  return;
}



// autogenerated function stub: 
// long /*$ra*/ SAVE_IsUniqueIDDeadDead(long uniqueID /*$a0*/)
long SAVE_IsUniqueIDDeadDead(long uniqueID)
{ // line 1201, offset 0x800b6844
	/* begin block 1 */
		// Start line: 1203
		// Start offset: 0x800B6844
		// Variables:
			struct _SavedIntro *saveIntro; // $v1
			struct SavedDeadDeadBits *deadDeadBits; // $a2
			long result; // $a3

		/* begin block 1.1 */
			// Start line: 1224
			// Start offset: 0x800B68AC
			// Variables:
				int deadByte; // $a1
				int deadBit; // $v1
		/* end block 1.1 */
		// End offset: 0x800B68E8
		// End Line: 1238
	/* end block 1 */
	// End offset: 0x800B68E8
	// End Line: 1240

	/* begin block 2 */
		// Start line: 2489
	/* end block 2 */
	// End Line: 2490

	/* begin block 3 */
		// Start line: 2490
	/* end block 3 */
	// End Line: 2491

	/* begin block 4 */
		// Start line: 2491
	/* end block 4 */
	// End Line: 2492

	return 0;
}


// decompiled code
// original method signature: 
// long /*$ra*/ SAVE_IsIntroDeadDead(struct Intro *intro /*$a0*/)
 // line 1243, offset 0x800b68f0
	/* begin block 1 */
		// Start line: 2573
	/* end block 1 */
	// End Line: 2574

long SAVE_IsIntroDeadDead(Intro *intro)

{
  Intro *pIVar1;
  uint uVar2;
  int in_v1;
  uint uVar3;
  int in_a1;
  int iVar4;
  
  pIVar1 = intro;
  if ((int)intro < 0) {
    pIVar1 = (Intro *)(intro->name + 7);
  }
  iVar4 = (int)pIVar1 >> 3;
  uVar3 = 1 << ((uint)intro & 7);
  uVar2 = (uint)(iVar4 < 0x340);
  if (iVar4 < 0x340) {
    uVar2 = in_v1 + iVar4;
    if (in_a1 == 1) {
      uVar3 = (uint)*(byte *)(in_v1 + iVar4 + 2) | uVar3;
      *(undefined *)(in_v1 + iVar4 + 2) = (char)uVar3;
      return uVar3;
    }
    *(byte *)(uVar2 + 2) = *(byte *)(uVar2 + 2) & ~(byte)uVar3;
  }
  return uVar2;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_DoInstanceDeadDead(struct _Instance *instance /*$s0*/)
 // line 1249, offset 0x800b6914
	/* begin block 1 */
		// Start line: 2585
	/* end block 1 */
	// End Line: 2586

void SAVE_DoInstanceDeadDead(_Instance *instance)

{
  int in_v1;
  int in_a1;
  int in_a2;
  int in_a3;
  
  if (in_a1 == in_a3) {
    *(byte *)(in_v1 + in_a2 + 2) = *(byte *)(in_v1 + in_a2 + 2) | (byte)instance;
    return;
  }
  *(byte *)(in_v1 + in_a2 + 2) = *(byte *)(in_v1 + in_a2 + 2) & ~(byte)instance;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_MarkDeadDead(struct _Instance *instance /*$a0*/)
 // line 1259, offset 0x800b6944
	/* begin block 1 */
		// Start line: 2605
	/* end block 1 */
	// End Line: 2606

	/* begin block 2 */
		// Start line: 2606
	/* end block 2 */
	// End Line: 2607

void SAVE_MarkDeadDead(_Instance *instance)

{
  int in_v0;
  byte in_v1;
  
  *(byte *)(in_v0 + 2) = in_v1 & ~(byte)instance;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_UndestroyInstance(struct _Instance *instance /*$a0*/)
 // line 1264, offset 0x800b6958
	/* begin block 1 */
		// Start line: 2615
	/* end block 1 */
	// End Line: 2616

void SAVE_UndestroyInstance(_Instance *instance)

{
  _G2AnimInterpStateBlock_Type *p_Var1;
  
  GlobalSave = (_GlobalSaveTracker *)0x0;
  p_Var1 = (_G2AnimInterpStateBlock_Type *)_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].alphaTable;
  if (_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].alphaTable <
      _G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList) {
    while (GlobalSave = (_GlobalSaveTracker *)p_Var1, *(char *)&p_Var1->next != '\x06') {
      p_Var1 = (_G2AnimInterpStateBlock_Type *)
               (&p_Var1->next + (uint)*(byte *)((int)&p_Var1->next + 1));
      if (_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList <= p_Var1) {
        GlobalSave = (_GlobalSaveTracker *)0x0;
        return;
      }
    }
  }
  return;
}



// decompiled code
// original method signature: 
// struct SavedIntroSmall * /*$ra*/ SAVE_GetSavedSmallIntro(struct _Instance *instance /*$a0*/)
 // line 1269, offset 0x800b697c
	/* begin block 1 */
		// Start line: 1271
		// Start offset: 0x800B697C
		// Variables:
	// 		struct SavedBasic *curSave; // $a1
	/* end block 1 */
	// End offset: 0x800B69D8
	// End Line: 1289

	/* begin block 2 */
		// Start line: 2625
	/* end block 2 */
	// End Line: 2626

	/* begin block 3 */
		// Start line: 2626
	/* end block 3 */
	// End Line: 2627

	/* begin block 4 */
		// Start line: 2630
	/* end block 4 */
	// End Line: 2631

SavedIntroSmall * SAVE_GetSavedSmallIntro(_Instance *instance)

{
  SavedIntroSmall *in_v0;
  _GlobalSaveTracker *in_v1;
  
  GlobalSave = in_v1;
  return in_v0;
}



// decompiled code
// original method signature: 
// struct SavedIntroSpline * /*$ra*/ SAVE_GetIntroSpline(struct _Instance *instance /*$a0*/)
 // line 1291, offset 0x800b69e8
	/* begin block 1 */
		// Start line: 1293
		// Start offset: 0x800B69E8
		// Variables:
	// 		struct SavedBasic *curSave; // $a1
	/* end block 1 */
	// End offset: 0x800B6A44
	// End Line: 1310

	/* begin block 2 */
		// Start line: 2669
	/* end block 2 */
	// End Line: 2670

	/* begin block 3 */
		// Start line: 2670
	/* end block 3 */
	// End Line: 2671

	/* begin block 4 */
		// Start line: 2673
	/* end block 4 */
	// End Line: 2674

SavedIntroSpline * SAVE_GetIntroSpline(_Instance *instance)

{
  _Instance *p_Var1;
  int in_v1;
  uint uVar2;
  SavedIntroSpline *in_a3;
  
  if (in_v1 != 0) {
    p_Var1 = instance;
    if ((int)instance < 0) {
      p_Var1 = (_Instance *)((int)&(instance->node).next + 3);
    }
    uVar2 = 1 << ((uint)instance & 7);
    if ((int)p_Var1 >> 3 < 0x340) {
      in_a3 = (SavedIntroSpline *)
              (uint)(((uint)*(byte *)(in_v1 + ((int)p_Var1 >> 3) + 2) & uVar2) == uVar2);
    }
  }
  return in_a3;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_UpdateGlobalSaveTracker()
 // line 1313, offset 0x800b6a54
	/* begin block 1 */
		// Start line: 2713
	/* end block 1 */
	// End Line: 2714

	/* begin block 2 */
		// Start line: 2714
	/* end block 2 */
	// End Line: 2715

/* WARNING: Unknown calling convention yet parameter storage is locked */

void SAVE_UpdateGlobalSaveTracker(void)

{
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_RestoreGlobalSaveTracker()
 // line 1326, offset 0x800b6ae8
	/* begin block 1 */
		// Start line: 2740
	/* end block 1 */
	// End Line: 2741

	/* begin block 2 */
		// Start line: 2742
	/* end block 2 */
	// End Line: 2743

/* WARNING: Unknown calling convention yet parameter storage is locked */

void SAVE_RestoreGlobalSaveTracker(void)

{
  _G2AnimInterpStateBlock_Type **pp_Var1;
  _G2AnimInterpStateBlock_Type **pp_Var2;
  int in_a0;
  _G2AnimInterpStateBlock_Type *p_Var3;
  
  p_Var3 = (_G2AnimInterpStateBlock_Type *)_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].alphaTable;
  if (_G2AnimInterpInfo_Type_ARRAY_800d57e0[0].alphaTable <
      _G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList) {
    do {
      if ((*(char *)&p_Var3->next == '\x05') &&
         ((int)(short)*(ushort *)((int)&p_Var3->next + 2) == *(int *)(in_a0 + 0x3c))) {
        return;
      }
      pp_Var1 = &p_Var3->next;
      pp_Var2 = &p_Var3->next;
      p_Var3 = (_G2AnimInterpStateBlock_Type *)(pp_Var2 + (uint)*(byte *)((int)pp_Var1 + 1));
    } while ((_G2AnimInterpStateBlock_Type *)(pp_Var2 + (uint)*(byte *)((int)pp_Var1 + 1)) <
             _G2AnimInterpInfo_Type_ARRAY_800d57e0[0].stateBlockList);
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_SaveEverythingInMemory()
 // line 1354, offset 0x800b6bb8
	/* begin block 1 */
		// Start line: 1355
		// Start offset: 0x800B6BB8
		// Variables:
	// 		struct _Instance *instance; // $s0
	// 		long i; // $s1

		/* begin block 1.1 */
			// Start line: 1363
			// Start offset: 0x800B6BE0
			// Variables:
		// 		struct _Instance *next; // $s1
		// 		struct Level *level; // $v0
		/* end block 1.1 */
		// End offset: 0x800B6C00
		// End Line: 1372
	/* end block 1 */
	// End offset: 0x800B6C54
	// End Line: 1388

	/* begin block 2 */
		// Start line: 2798
	/* end block 2 */
	// End Line: 2799

	/* begin block 3 */
		// Start line: 2804
	/* end block 3 */
	// End Line: 2805

/* WARNING: Unknown calling convention yet parameter storage is locked */

void SAVE_SaveEverythingInMemory(void)

{
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_SaveGame()
 // line 1391, offset 0x800b6c6c
	/* begin block 1 */
		// Start line: 2900
	/* end block 1 */
	// End Line: 2901

/* WARNING: Unknown calling convention yet parameter storage is locked */

void SAVE_SaveGame(void)

{
  FUN_800b5754(0x800d0dcc);
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ SAVE_RestoreGame()
 // line 1406, offset 0x800b6cb8
	/* begin block 1 */
		// Start line: 2930
	/* end block 1 */
	// End Line: 2931

/* WARNING: Unknown calling convention yet parameter storage is locked */

void SAVE_RestoreGame(void)

{
  undefined4 in_a2;
  int in_t0;
  
  *(undefined4 *)(in_t0 + 0x10) = in_a2;
  FUN_8003ff7c(__timerEvent);
  FUN_8003ff48(DAT_800d0f80);
  SOUND_SetMusicVolume(clearRect[0].tag);
  if ((GlobalSave->flags & 2U) == 0) {
    FUN_800312a0();
  }
  else {
    FUN_800312e0();
  }
  return;
}



// decompiled code
// original method signature: 
// long /*$ra*/ SAVE_SizeOfFreeSpace()
 // line 1500, offset 0x800b6d1c
	/* begin block 1 */
		// Start line: 3000
	/* end block 1 */
	// End Line: 3001

	/* begin block 2 */
		// Start line: 3035
	/* end block 2 */
	// End Line: 3036

/* WARNING: Unknown calling convention yet parameter storage is locked */

long SAVE_SizeOfFreeSpace(void)

{
  long in_v0;
  
  return in_v0;
}





