#include "THISDUST.H"
#include "VRAM.H"


// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_InitVramBlockCache()
 // line 153, offset 0x800728d0
	/* begin block 1 */
		// Start line: 154
		// Start offset: 0x800728D0
		// Variables:
	// 		int i; // $v1
	/* end block 1 */
	// End offset: 0x800728FC
	// End Line: 179

	/* begin block 2 */
		// Start line: 228
	/* end block 2 */
	// End Line: 229

	/* begin block 3 */
		// Start line: 306
	/* end block 3 */
	// End Line: 307

/* WARNING: Unknown calling convention yet parameter storage is locked */

void VRAM_InitVramBlockCache(void)

{
  ushort uVar1;
  uint uVar2;
  int iVar3;
  int iVar4;
  _G2AnimSection_Type *section;
  _G2AnimKeylist_Type *p_Var5;
  _G2AnimSection_Type *section_00;
  uint unaff_s4;
  int unaff_s5;
  int unaff_s6;
  int *unaff_s7;
  int unaff_s8;
  
  do {
    unaff_s5 = unaff_s5 + 0x11c;
    if (2 < (int)unaff_s4) {
      return;
    }
    if (*(int *)((int)unaff_s7 + unaff_s5) == *(int *)((int)unaff_s7 + unaff_s6)) {
      section = (_G2AnimSection_Type *)(*unaff_s7 + (unaff_s4 - 1 & 0xff) * 0x30 + 0x1b8);
      section_00 = (_G2AnimSection_Type *)(*unaff_s7 + (unaff_s4 & 0xff) * 0x30 + 0x1b8);
      uVar2 = (uint)section_00->keylistID;
      if ((((uint)section->keylistID == uVar2) && (G2AnimSection_SetLooping(section), uVar2 == 0))
         && (G2AnimSection_SetLooping(section_00), uVar2 == 0)) {
        iVar3 = FUN_8008ff58(section);
        iVar4 = FUN_8008ff58(section_00);
        if (iVar3 != iVar4) {
          p_Var5 = section->keylist;
          uVar1 = section->keylistID;
          iVar3 = FUN_8008ff58();
          iVar4 = FUN_8008ff0c(p_Var5);
                    /* WARNING: Subroutine does not return */
          FUN_8008ffd4(section_00,p_Var5,(uint)uVar1,(iVar3 + unaff_s8) % iVar4);
        }
      }
    }
    unaff_s6 = unaff_s6 + 0x11c;
    unaff_s4 = unaff_s4 + 1;
  } while( true );
}



// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_EnableTerrainArea()
 // line 184, offset 0x80072930
	/* begin block 1 */
		// Start line: 300
	/* end block 1 */
	// End Line: 301

/* WARNING: Unknown calling convention yet parameter storage is locked */

void VRAM_EnableTerrainArea(void)

{
  int in_v0;
  int in_v1;
  undefined4 uStack00000010;
  
  while (-1 < in_v1) {
    *(undefined *)(in_v0 + -0x17) = 0;
    in_v1 = in_v1 + -1;
    in_v0 = in_v0 + -0x1c;
  }
                    /* WARNING: Subroutine does not return */
  uStack00000010 = 1;
  FUN_80072ed8(0x200,0x100,0x200,0x100);
}



// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_DisableTerrainArea()
 // line 189, offset 0x80072960
	/* begin block 1 */
		// Start line: 311
	/* end block 1 */
	// End Line: 312

/* WARNING: Unknown calling convention yet parameter storage is locked */

void VRAM_DisableTerrainArea(void)

{
  return;
}



// autogenerated function stub: 
// int /*$ra*/ VRAM_ConcatanateMemory(struct _BlockVramEntry *curBlock /*$s1*/)
int VRAM_ConcatanateMemory(struct _BlockVramEntry *curBlock)
{ // line 195, offset 0x8007298c
	/* begin block 1 */
		// Start line: 196
		// Start offset: 0x8007298C
		// Variables:
			struct _BlockVramEntry *nextBlock; // $s0
	/* end block 1 */
	// End offset: 0x80072B60
	// End Line: 261

	/* begin block 2 */
		// Start line: 324
	/* end block 2 */
	// End Line: 325

	return 0;
}


// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_GarbageCollect()
 // line 263, offset 0x80072b74
	/* begin block 1 */
		// Start line: 463
	/* end block 1 */
	// End Line: 464

/* WARNING: Unknown calling convention yet parameter storage is locked */

void VRAM_GarbageCollect(void)

{
  int iVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  int *unaff_s0;
  int **unaff_s1;
  
  *(undefined *)((int)unaff_s1 + 5) = 0;
  do {
    do {
      unaff_s0 = (int *)*unaff_s0;
      while (unaff_s0 == (int *)0x0) {
        unaff_s1 = (int **)*unaff_s1;
        if (unaff_s1 == (int **)0x0) {
          return;
        }
        unaff_s0 = *unaff_s1;
      }
      if ((*(short *)(unaff_s1 + 3) == *(short *)(unaff_s0 + 3)) &&
         (*(short *)(unaff_s1 + 4) == *(short *)(unaff_s0 + 4))) {
        iVar2 = (uint)*(ushort *)((int)unaff_s1 + 0xe) << 0x10;
        iVar4 = iVar2 >> 0x10;
        iVar1 = (uint)*(ushort *)((int)unaff_s0 + 0xe) << 0x10;
        iVar3 = iVar1 >> 0x10;
        if (iVar2 >> 0x18 == iVar1 >> 0x18) {
          if (iVar4 + (int)*(short *)((int)unaff_s1 + 0x12) == iVar3) {
            *(short *)((int)unaff_s1 + 0x12) =
                 *(short *)((int)unaff_s1 + 0x12) + *(short *)((int)unaff_s0 + 0x12);
            goto LAB_80072b00;
          }
          if (iVar3 + (int)*(short *)((int)unaff_s0 + 0x12) == iVar4) {
            *(short *)((int)unaff_s0 + 0x12) =
                 *(short *)((int)unaff_s0 + 0x12) + *(short *)((int)unaff_s1 + 0x12);
            goto LAB_80072b64;
          }
        }
      }
    } while ((*(short *)((int)unaff_s1 + 0xe) != *(short *)((int)unaff_s0 + 0xe)) ||
            (*(short *)((int)unaff_s1 + 0x12) != *(short *)((int)unaff_s0 + 0x12)));
    if (((int)*(short *)(unaff_s1 + 3) + (int)*(short *)(unaff_s1 + 4) ==
         (int)*(short *)(unaff_s0 + 3)) &&
       (((*(ushort *)(unaff_s1 + 3) & 0x3f) == 0 ||
        ((int)*(short *)(unaff_s1 + 4) + (int)*(short *)(unaff_s0 + 4) < 0x41)))) {
      *(short *)(unaff_s1 + 4) = *(short *)(unaff_s1 + 4) + *(short *)(unaff_s0 + 4);
LAB_80072b00:
      FUN_80072c74(unaff_s0);
      *(undefined *)((int)unaff_s0 + 5) = 0;
      return;
    }
  } while (((int)*(short *)(unaff_s0 + 3) + (int)*(short *)(unaff_s0 + 4) !=
            (int)*(short *)(unaff_s1 + 3)) ||
          (((*(ushort *)(unaff_s0 + 3) & 0x3f) != 0 &&
           (0x40 < (int)*(short *)(unaff_s1 + 4) + (int)*(short *)(unaff_s0 + 4)))));
  *(short *)(unaff_s0 + 4) = *(short *)(unaff_s0 + 4) + *(short *)(unaff_s1 + 4);
LAB_80072b64:
  FUN_80072c74(unaff_s1);
  *(undefined *)((int)unaff_s1 + 5) = 0;
  return;
}



// decompiled code
// original method signature: 
// int /*$ra*/ VRAM_InsertFreeBlock(struct _BlockVramEntry *block /*$a0*/)
 // line 270, offset 0x80072ba8
	/* begin block 1 */
		// Start line: 271
		// Start offset: 0x80072BA8
		// Variables:
	// 		struct _BlockVramEntry *next; // $v1
	// 		struct _BlockVramEntry *prev; // $a1
	/* end block 1 */
	// End offset: 0x80072C28
	// End Line: 301

	/* begin block 2 */
		// Start line: 478
	/* end block 2 */
	// End Line: 479

int VRAM_InsertFreeBlock(_BlockVramEntry *block)

{
  int in_v0;
  
  return in_v0;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_DeleteFreeBlock(struct _BlockVramEntry *block /*$a0*/)
 // line 304, offset 0x80072c38
	/* begin block 1 */
		// Start line: 306
		// Start offset: 0x80072C38
		// Variables:
	// 		struct _BlockVramEntry *next; // $v1
	// 		struct _BlockVramEntry *prev; // $a1
	/* end block 1 */
	// End offset: 0x80072C98
	// End Line: 330

	/* begin block 2 */
		// Start line: 547
	/* end block 2 */
	// End Line: 548

	/* begin block 3 */
		// Start line: 548
	/* end block 3 */
	// End Line: 549

	/* begin block 4 */
		// Start line: 549
	/* end block 4 */
	// End Line: 550

void VRAM_DeleteFreeBlock(_BlockVramEntry *block)

{
  _BlockVramEntry *p_Var1;
  _BlockVramEntry *in_v1;
  _BlockVramEntry **in_a1;
  
  if (in_a1 == (_BlockVramEntry **)0x0) {
    p_Var1 = block;
    block->next = vramBlockList[74]._8_4_;
    vramBlockList[74]._8_4_ = p_Var1;
  }
  else {
    block->next = in_v1;
    *in_a1 = block;
  }
  FUN_80072bb0();
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_InsertUsedBlock(struct _BlockVramEntry *block /*$a0*/)
 // line 333, offset 0x80072ca0
	/* begin block 1 */
		// Start line: 605
	/* end block 1 */
	// End Line: 606

	/* begin block 2 */
		// Start line: 606
	/* end block 2 */
	// End Line: 607

void VRAM_InsertUsedBlock(_BlockVramEntry *block)

{
  _BlockVramEntry *in_v1;
  _BlockVramEntry **in_a1;
  
  if (block == in_v1) {
    if (in_a1 == (_BlockVramEntry **)0x0) {
      vramBlockList[74]._8_4_ = block->next;
      return;
    }
    *in_a1 = block->next;
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_DeleteUsedBlock(struct _BlockVramEntry *block /*$a0*/)
 // line 349, offset 0x80072cd4
	/* begin block 1 */
		// Start line: 351
		// Start offset: 0x80072CD4
		// Variables:
	// 		struct _BlockVramEntry *next; // $v1
	// 		struct _BlockVramEntry *prev; // $a1
	/* end block 1 */
	// End offset: 0x80072D30
	// End Line: 372

	/* begin block 2 */
		// Start line: 637
	/* end block 2 */
	// End Line: 638

	/* begin block 3 */
		// Start line: 638
	/* end block 3 */
	// End Line: 639

	/* begin block 4 */
		// Start line: 640
	/* end block 4 */
	// End Line: 641

void VRAM_DeleteUsedBlock(_BlockVramEntry *block)

{
  return;
}



// decompiled code
// original method signature: 
// struct _BlockVramEntry * /*$ra*/ VRAM_GetOpenBlock()
 // line 374, offset 0x80072d38
	/* begin block 1 */
		// Start line: 376
		// Start offset: 0x80072D38
		// Variables:
	// 		int i; // $a0
	/* end block 1 */
	// End offset: 0x80072D64
	// End Line: 389

	/* begin block 2 */
		// Start line: 689
	/* end block 2 */
	// End Line: 690

	/* begin block 3 */
		// Start line: 690
	/* end block 3 */
	// End Line: 691

	/* begin block 4 */
		// Start line: 692
	/* end block 4 */
	// End Line: 693

/* WARNING: Unknown calling convention yet parameter storage is locked */

_BlockVramEntry * VRAM_GetOpenBlock(void)

{
  _BlockVramEntry *in_v0;
  _BlockVramEntry **in_v1;
  _BlockVramEntry **in_a0;
  _BlockVramEntry **in_a1;
  
  if (in_a0 == in_v1) {
    if (in_a1 == (_BlockVramEntry **)0x0) {
      vramBlockList[74]._4_4_ = *in_a0;
      return *in_a0;
    }
    in_v0 = *in_a0;
    *in_a1 = in_v0;
  }
  return in_v0;
}



// decompiled code
// original method signature: 
// int /*$ra*/ VRAM_DeleteFreeVram(short x /*$a0*/, short y /*$a1*/, short w /*$a2*/, short h /*$a3*/)
 // line 391, offset 0x80072d6c
	/* begin block 1 */
		// Start line: 392
		// Start offset: 0x80072D6C
		// Variables:
	// 		struct _BlockVramEntry *prev; // $t1
	// 		struct _BlockVramEntry *vblock; // $a2
	// 		struct _BlockVramEntry *nextVBlock; // $t0
	// 		struct _BlockVramEntry (*blockLists[2]); // stack offset -24
	// 		int i; // $t2
	// 		int delCount; // $t3
	/* end block 1 */
	// End offset: 0x80072E88
	// End Line: 427

	/* begin block 2 */
		// Start line: 727
	/* end block 2 */
	// End Line: 728

int VRAM_DeleteFreeVram(short x,short y,short w,short h)

{
  int in_v0;
  
  return in_v0;
}



// decompiled code
// original method signature: 
// int /*$ra*/ VRAM_InsertFreeVram(short x /*stack -48*/, short y /*stack -46*/, short w /*$s7*/, short h /*$fp*/, int flags /*stack 16*/)
 // line 430, offset 0x80072e9c
	/* begin block 1 */
		// Start line: 431
		// Start offset: 0x80072E9C
		// Variables:
	// 		struct _BlockVramEntry *useBlock; // $a0
	/* end block 1 */
	// End offset: 0x80072FFC
	// End Line: 476

	/* begin block 2 */
		// Start line: 841
	/* end block 2 */
	// End Line: 842

int VRAM_InsertFreeVram(short x,short y,short w,short h,int flags)

{
  undefined2 in_register_00000012;
  undefined4 *puVar1;
  undefined4 *in_t0;
  undefined4 *in_t1;
  undefined4 *puVar2;
  int in_t2;
  int in_t3;
  int in_t4;
  int in_t5;
  int *in_t6;
  int in_t7;
  
  do {
    in_t3 = in_t3 + 1;
    puVar2 = in_t1;
    while( true ) {
      do {
        puVar1 = in_t0;
        in_t1 = puVar2;
        if (puVar1 == (undefined4 *)0x0) {
          do {
            in_t2 = in_t2 + 1;
            in_t6 = in_t6 + 1;
            if (1 < in_t2) {
              return in_t3;
            }
            puVar1 = (undefined4 *)*in_t6;
            in_t1 = (undefined4 *)0x0;
          } while (puVar1 == (undefined4 *)0x0);
          in_t4 = (int)y;
          in_t5 = in_t4 + (int)h;
        }
        in_t0 = (undefined4 *)*puVar1;
        puVar2 = puVar1;
      } while (((((int)*(short *)(puVar1 + 3) < CONCAT22(in_register_00000012,x)) ||
                (puVar2 = puVar1, in_t7 < (int)*(short *)(puVar1 + 3) + (int)*(short *)(puVar1 + 4))
                ) || (puVar2 = puVar1, (int)*(short *)((int)puVar1 + 0xe) < in_t4)) ||
              (puVar2 = puVar1,
              in_t5 < (int)*(short *)((int)puVar1 + 0xe) + (int)*(short *)((int)puVar1 + 0x12)));
      *(undefined *)((int)puVar1 + 5) = 0;
      if (in_t1 != (undefined4 *)0x0) break;
      if (in_t2 == 0) {
        in_t3 = in_t3 + 1;
        puVar2 = in_t1;
        vramBlockList[74]._8_4_ = in_t0;
      }
      else {
        in_t3 = in_t3 + 1;
        puVar2 = in_t1;
        vramBlockList[74]._4_4_ = in_t0;
      }
    }
    *(undefined4 **)in_t1 = in_t0;
  } while( true );
}



// decompiled code
// original method signature: 
// struct _BlockVramEntry * /*$ra*/ VRAM_CheckVramSlot(short *x /*stack 0*/, short *y /*stack 4*/, short w /*$s7*/, short h /*$s6*/, int type /*stack 16*/, int startY /*stack 20*/)
 // line 487, offset 0x80073030
	/* begin block 1 */
		// Start line: 488
		// Start offset: 0x80073030
		// Variables:
	// 		struct _BlockVramEntry *vblock; // $s1
	// 		short hldx; // $s3
	// 		short hldy; // $s4
	// 		short hldw; // $s0
	// 		short hldh; // $s5
	// 		long fits; // $s2
	// 		long offset; // $s0
	// 		int wdiff; // $t1
	// 		int hdiff; // $v1
	// 		struct _BlockVramEntry *vblockleft; // $t3
	// 		long offsetleft; // $t2
	// 		struct _BlockVramEntry *vblockright; // $s4
	// 		long offsetright; // $s3

		/* begin block 1.1 */
			// Start line: 546
			// Start offset: 0x80073170
			// Variables:
		// 		int newx; // $v0
		/* end block 1.1 */
		// End offset: 0x800731AC
		// End Line: 553

		/* begin block 1.2 */
			// Start line: 570
			// Start offset: 0x800731C4
		/* end block 1.2 */
		// End offset: 0x800731F4
		// End Line: 590
	/* end block 1 */
	// End offset: 0x800733F8
	// End Line: 741

	/* begin block 2 */
		// Start line: 997
	/* end block 2 */
	// End Line: 998

_BlockVramEntry * VRAM_CheckVramSlot(short *x,short *y,short w,short h,int type,int startY)

{
  undefined4 in_t0;
  
  *(undefined4 *)(x + 10) = in_t0;
  FUN_80072be4();
  return (_BlockVramEntry *)&DAT_00000001;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_ClearVramBlock(struct _BlockVramEntry *block /*$s0*/)
 // line 745, offset 0x8007342c
	/* begin block 1 */
		// Start line: 1593
	/* end block 1 */
	// End Line: 1594

void VRAM_ClearVramBlock(_BlockVramEntry *block)

{
                    /* WARNING: Subroutine does not return */
  FUN_80072ed8();
}



// decompiled code
// original method signature: 
// void /*$ra*/ AdjustVramCoordsObject(int oldx /*$s3*/, int oldy /*$s1*/, int newx /*$a2*/, int newy /*$t7*/, struct Object *object /*stack 16*/)
 // line 825, offset 0x80073460
	/* begin block 1 */
		// Start line: 826
		// Start offset: 0x80073460
		// Variables:
	// 		struct TextureMT3 *texture; // $t1
	// 		int oldclutxoffset; // $v0
	// 		int oldclutyoffset; // $a0
	// 		int newclut; // $a0
	// 		int d; // $t4
	// 		int oldtpagexoffset; // $v1
	// 		int oldtpageyoffset; // $v0
	// 		int newtpage; // $a3
	// 		struct _Model *model; // $t3
	// 		short diffy; // $s5
	// 		short diffx; // $s6
	/* end block 1 */
	// End offset: 0x80073628
	// End Line: 884

	/* begin block 2 */
		// Start line: 1753
	/* end block 2 */
	// End Line: 1754

void AdjustVramCoordsObject(int oldx,int oldy,int newx,int newy,Object *object)

{
  return;
}



// decompiled code
// original method signature: 
// struct _BlockVramEntry * /*$ra*/ VRAM_InsertionSort(struct _BlockVramEntry *rootNode /*$a0*/, struct _BlockVramEntry *newBlock /*$a1*/, int pack_type /*$a2*/)
 // line 922, offset 0x8007364c
	/* begin block 1 */
		// Start line: 925
		// Start offset: 0x8007364C
		// Variables:
	// 		struct _BlockVramEntry *next; // $a3
	// 		struct _BlockVramEntry *prev; // $t0
	/* end block 1 */
	// End offset: 0x800736FC
	// End Line: 965

	/* begin block 2 */
		// Start line: 2127
	/* end block 2 */
	// End Line: 2128

	/* begin block 3 */
		// Start line: 2129
	/* end block 3 */
	// End Line: 2130

	/* begin block 4 */
		// Start line: 2131
	/* end block 4 */
	// End Line: 2132

_BlockVramEntry *
VRAM_InsertionSort(_BlockVramEntry *rootNode,_BlockVramEntry *newBlock,int pack_type)

{
  ushort uVar1;
  ushort uVar2;
  bool bVar3;
  char cVar4;
  uint uVar5;
  char *pcVar6;
  ushort *puVar7;
  int iVar8;
  int in_t4;
  int in_t7;
  int unaff_s0;
  uint unaff_s1;
  int unaff_s2;
  uint unaff_s3;
  uint unaff_s4;
  char unaff_s5;
  short unaff_s6;
  int in_t8;
  int in_t9;
  
  while( true ) {
    in_t4 = in_t4 + 1;
    bVar3 = in_t4 < (int)*(short *)(unaff_s2 + 8);
    if (!bVar3) break;
    iVar8 = *(int *)(in_t4 * 4 + *(int *)(unaff_s2 + 0xc));
    pcVar6 = *(char **)(iVar8 + 0x30);
    if ((pcVar6 != (char *)0x0) && (pcVar6 < *(char **)(iVar8 + 0x34))) {
      puVar7 = (ushort *)(pcVar6 + 2);
      do {
        uVar1 = puVar7[2];
        uVar5 = in_t7 + (((uint)uVar1 & 0x10) * 0x10 - (unaff_s1 & 0xffffff00));
        uVar2 = *puVar7;
        *(char *)((int)puVar7 + -1) = *(char *)((int)puVar7 + -1) + unaff_s5;
        *(char *)((int)puVar7 + 7) = *(char *)((int)puVar7 + 7) + unaff_s5;
        *(char *)((int)puVar7 + 3) = *(char *)((int)puVar7 + 3) + unaff_s5;
        cVar4 = (char)((int)unaff_s6 << (2 - ((uint)(uVar1 >> 7) & 3) & 0x1f));
        *pcVar6 = *pcVar6 + cVar4;
        pcVar6 = pcVar6 + 0x10;
        puVar7[2] = uVar1 & 0x1e0 |
                    (ushort)((int)(uVar5 & 0x100) >> 4) |
                    (ushort)((int)(in_t9 + (((uint)uVar1 & 0xf) * 0x40 - in_t8) & 0x3ff) >> 6) |
                    (ushort)((uVar5 & 0x200) << 2);
        *puVar7 = ((short)in_t7 + ((uVar2 >> 6) - (short)unaff_s1)) * 0x40 |
                  (ushort)((int)(unaff_s0 + (((uint)uVar2 & 0x3f) * 0x10 - (unaff_s3 & unaff_s4)))
                          >> 4) & 0x3f;
        *(char *)(puVar7 + 1) = *(char *)(puVar7 + 1) + cVar4;
        *(char *)(puVar7 + 3) = *(char *)(puVar7 + 3) + cVar4;
        puVar7 = puVar7 + 8;
      } while (pcVar6 < *(char **)(iVar8 + 0x34));
    }
  }
  return (_BlockVramEntry *)(uint)bVar3;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_ClearVram()
 // line 970, offset 0x80073704
	/* begin block 1 */
		// Start line: 971
		// Start offset: 0x80073704
		// Variables:
	// 		struct _BlockVramEntry *vblock; // $a0
	// 		struct _BlockVramEntry *next; // $s0
	/* end block 1 */
	// End offset: 0x80073730
	// End Line: 981

	/* begin block 2 */
		// Start line: 2226
	/* end block 2 */
	// End Line: 2227

	/* begin block 3 */
		// Start line: 2229
	/* end block 3 */
	// End Line: 2230

/* WARNING: Unknown calling convention yet parameter storage is locked */

void VRAM_ClearVram(void)

{
  int in_v1;
  undefined4 in_a0;
  undefined4 *in_a1;
  int in_a2;
  undefined4 *in_a3;
  undefined4 *puVar1;
  undefined4 *in_t0;
  
  while (((puVar1 = in_a3, in_a2 < in_v1 ||
          ((in_a3 = puVar1, in_a2 == in_v1 &&
           (in_a3 = puVar1, *(short *)((int)in_a1 + 0x12) < *(short *)((int)puVar1 + 0x12))))) &&
         (in_a3 = (undefined4 *)*puVar1, in_t0 = puVar1, in_a3 != (undefined4 *)0x0))) {
    in_a2 = (int)*(short *)(in_a1 + 4);
    in_v1 = (int)*(short *)(in_a3 + 4);
    in_t0 = puVar1;
  }
  if (in_t0 == (undefined4 *)0x0) {
    *in_a1 = in_a0;
  }
  else {
    *(undefined4 **)in_a1 = in_a3;
    *(undefined4 **)in_t0 = in_a1;
  }
  return;
}



// decompiled code
// original method signature: 
// struct _BlockVramEntry * /*$ra*/ VRAM_RearrangeVramsLayer(long whichLayer /*stack 0*/, short *AddX /*stack 4*/, short *AddY /*stack 8*/, short AddW /*$fp*/, int AddH /*stack 16*/, int AddType /*stack 20*/, int AddStartY /*stack 24*/)
 // line 991, offset 0x80073740
	/* begin block 1 */
		// Start line: 992
		// Start offset: 0x80073740
		// Variables:
	// 		struct _BlockVramEntry *vblock; // $a0
	// 		struct _BlockVramEntry *retvblock; // $s5
	// 		struct _BlockVramEntry *sortedBlocks; // $s2
	// 		struct _BlockVramEntry *curBlock; // $s0
	// 		struct _BlockVramEntry (*savedVramBlocksPTR[48]); // stack offset -1624
	// 		struct _BlockVramEntry savedVramBlocks[48]; // stack offset -1432
	// 		struct RECT vramLoc; // stack offset -88
	// 		long numBlocks; // $s3
	// 		long d; // $s1
	// 		int error_retry; // $s4
	// 		int good_pack; // $s7
	// 		int pack_type; // $s6
	// 		short x; // stack offset -80
	// 		short y; // stack offset -78
	// 		short dispYPos; // stack offset -56

		/* begin block 1.1 */
			// Start line: 1052
			// Start offset: 0x80073868
			// Variables:
		// 		int startY; // stack offset -48

			/* begin block 1.1.1 */
				// Start line: 1117
				// Start offset: 0x80073A70
				// Variables:
			// 		int type; // $t0
			/* end block 1.1.1 */
			// End offset: 0x80073C08
			// End Line: 1217
		/* end block 1.1 */
		// End offset: 0x80073D8C
		// End Line: 1278
	/* end block 1 */
	// End offset: 0x80073D8C
	// End Line: 1281

	/* begin block 2 */
		// Start line: 2271
	/* end block 2 */
	// End Line: 2272

	/* begin block 3 */
		// Start line: 2292
	/* end block 3 */
	// End Line: 2293

_BlockVramEntry *
VRAM_RearrangeVramsLayer
          (long whichLayer,short *AddX,short *AddY,short AddW,int AddH,int AddType,int AddStartY)

{
  _BlockVramEntry *in_v0;
  int *piVar1;
  
  piVar1 = vramBlockList[74]._4_4_;
  if (vramBlockList[74]._4_4_ != (int *)0x0) {
    do {
      piVar1 = (int *)*piVar1;
      in_v0 = (_BlockVramEntry *)FUN_80073468();
    } while (piVar1 != (int *)0x0);
  }
  return in_v0;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_TransferBufferToVram(void *dataPtr /*$s3*/, long dataSize /*$s2*/, short status /*$s7*/, void *data1 /*$s0*/, void *data2 /*stack 16*/)
 // line 1315, offset 0x80073dc8
	/* begin block 1 */
		// Start line: 1316
		// Start offset: 0x80073DC8
		// Variables:
	// 		struct VramBuffer *vramControl; // $s1
	// 		struct RECT rect; // stack offset -48
	// 		long *nextOTag; // $s5
	// 		long *drawTimerReturn; // $fp

		/* begin block 1.1 */
			// Start line: 1345
			// Start offset: 0x80073E5C
		/* end block 1.1 */
		// End offset: 0x80073F10
		// End Line: 1374

		/* begin block 1.2 */
			// Start line: 1379
			// Start offset: 0x80073F18
		/* end block 1.2 */
		// End offset: 0x80073FBC
		// End Line: 1399

		/* begin block 1.3 */
			// Start line: 1435
			// Start offset: 0x80073FD8
		/* end block 1.3 */
		// End offset: 0x80073FEC
		// End Line: 1438
	/* end block 1 */
	// End offset: 0x80074010
	// End Line: 1450

	/* begin block 2 */
		// Start line: 2630
	/* end block 2 */
	// End Line: 2631

void VRAM_TransferBufferToVram(void *dataPtr,long dataSize,short status,void *data1,void *data2)

{
                    /* WARNING: Subroutine does not return */
  FUN_800ba930(0);
}



// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_LoadReturn(void *dataPtr /*$a0*/, void *data1 /*$a1*/, void *data2 /*$a2*/)
 // line 1455, offset 0x80074040
	/* begin block 1 */
		// Start line: 1456
		// Start offset: 0x80074040
	/* end block 1 */
	// End offset: 0x80074040
	// End Line: 1456

	/* begin block 2 */
		// Start line: 3339
	/* end block 2 */
	// End Line: 3340

void VRAM_LoadReturn(void *dataPtr,void *data1,void *data2)

{
  FUN_800bad64();
  return;
}



// decompiled code
// original method signature: 
// long /*$ra*/ VRAM_GetObjectVramSpace(struct VramSize *vramSize /*$v1*/, struct _ObjectTracker *objectTracker /*$s4*/)
 // line 1461, offset 0x80074060
	/* begin block 1 */
		// Start line: 1462
		// Start offset: 0x80074060
		// Variables:
	// 		struct RECT rect; // stack offset -32
	// 		long result; // $s3
	// 		struct _BlockVramEntry *lastVramBlockUsed; // $v0
	/* end block 1 */
	// End offset: 0x80074134
	// End Line: 1505

	/* begin block 2 */
		// Start line: 3351
	/* end block 2 */
	// End Line: 3352

long VRAM_GetObjectVramSpace(VramSize *vramSize,_ObjectTracker *objectTracker)

{
  long in_v0;
  
  return in_v0;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_InitMorphPalettes()
 // line 1511, offset 0x80074158
	/* begin block 1 */
		// Start line: 3502
	/* end block 1 */
	// End Line: 3503

	/* begin block 2 */
		// Start line: 3509
	/* end block 2 */
	// End Line: 3510

/* WARNING: Unknown calling convention yet parameter storage is locked */

void VRAM_InitMorphPalettes(void)

{
  int iVar1;
  int unaff_s4;
  
  iVar1 = FUN_8007306c();
  *(int *)(unaff_s4 + 0x18) = iVar1;
  if (iVar1 != 0) {
    *(int *)(iVar1 + 0x18) = unaff_s4;
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ VRAM_UpdateMorphPalettes()
 // line 1545, offset 0x80074160
	/* begin block 1 */
		// Start line: 3570
	/* end block 1 */
	// End Line: 3571

	/* begin block 2 */
		// Start line: 3671
	/* end block 2 */
	// End Line: 3672

/* WARNING: Unknown calling convention yet parameter storage is locked */

void VRAM_UpdateMorphPalettes(void)

{
  int in_v0;
  int unaff_s4;
  
  *(int *)(unaff_s4 + 0x18) = in_v0;
  if (in_v0 != 0) {
    *(int *)(in_v0 + 0x18) = unaff_s4;
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ MORPH_ChangeAreaPalettes(long time /*$a0*/)
 // line 1703, offset 0x80074168
	/* begin block 1 */
		// Start line: 3886
	/* end block 1 */
	// End Line: 3887

	/* begin block 2 */
		// Start line: 3912
	/* end block 2 */
	// End Line: 3913

void MORPH_ChangeAreaPalettes(long time)

{
  int in_v0;
  int unaff_s4;
  
  *(int *)(unaff_s4 + 0x18) = in_v0;
  *(int *)(in_v0 + 0x18) = unaff_s4;
  return;
}





