#include "THISDUST.H"
#include "MEMCARD.H"


// autogenerated function stub: 
// int /*$ra*/ MEMCARD_IsWrongVersion(struct memcard_t *memcard /*$a0*/)
int MEMCARD_IsWrongVersion(struct memcard_t *memcard)
{ // line 58, offset 0x800b9924
	/* begin block 1 */
		// Start line: 60
		// Start offset: 0x800B9924
		// Variables:
			int result; // $v0
	/* end block 1 */
	// End offset: 0x800B9930
	// End Line: 68

	/* begin block 2 */
		// Start line: 116
	/* end block 2 */
	// End Line: 117

	/* begin block 3 */
		// Start line: 117
	/* end block 3 */
	// End Line: 118

	/* begin block 4 */
		// Start line: 119
	/* end block 4 */
	// End Line: 120

	return 0;
}


// decompiled code
// original method signature: 
// void /*$ra*/ load(struct memcard_t *memcard /*$s1*/)
 // line 71, offset 0x800b9938
	/* begin block 1 */
		// Start line: 72
		// Start offset: 0x800B9938
		// Variables:
	// 		struct Object *object; // $s0
	/* end block 1 */
	// End offset: 0x800B99F0
	// End Line: 115

	/* begin block 2 */
		// Start line: 142
	/* end block 2 */
	// End Line: 143

void load(memcard_t *memcard)

{
  short sVar1;
  short sVar2;
  int in_v0;
  int in_v1;
  int in_a1;
  short *unaff_s0;
  short *psVar3;
  uint unaff_s1;
  int unaff_s2;
  uint unaff_s3;
  
  if (in_v0 == ((in_a1 >> 5) - in_v1) * 500) {
    if ((int)unaff_s0[-2] == unaff_s2) {
      unaff_s0[-1] = 1;
    }
    else {
      unaff_s0[-1] = (short)unaff_s2;
    }
  }
LAB_800b99bc:
  psVar3 = unaff_s0;
  unaff_s1 = unaff_s1 + 0x10;
  unaff_s0 = psVar3 + 8;
  if (unaff_s3 <= unaff_s1) {
    return;
  }
  sVar1 = *unaff_s0 + -1;
  if (*unaff_s0 == 0) goto code_r0x800b990c;
  goto LAB_800b99b8;
code_r0x800b990c:
  if (psVar3[7] == 0) {
                    /* WARNING: Subroutine does not return */
    FUN_800bcddc();
  }
  sVar2 = psVar3[6] + psVar3[7];
  psVar3[6] = sVar2;
  sVar1 = 200;
  if (((int)sVar2 == (uint)*(byte *)(psVar3 + 5) * 7 + -1) || ((int)sVar2 == unaff_s2)) {
    psVar3[7] = 0;
LAB_800b99b8:
    *unaff_s0 = sVar1;
  }
  goto LAB_800b99bc;
}



// decompiled code
// original method signature: 
// void /*$ra*/ unload(struct memcard_t *memcard /*$s0*/)
 // line 117, offset 0x800b9a04
	/* begin block 1 */
		// Start line: 253
	/* end block 1 */
	// End Line: 254

void unload(memcard_t *memcard)

{
  short *psVar1;
  int iVar2;
  menuface_t *pmVar3;
  int iVar4;
  
  iVar4 = 0;
  pmVar3 = &MenuFaces;
  psVar1 = &MenuFaces.y;
  iVar2 = 0;
  do {
    if ((int)(uint)*(byte *)(psVar1 + 2) <= (int)psVar1[3]) {
      FUN_8002a9a4(PTR_ARRAY_800d5a20[1] +
                   (iVar2 + (int)psVar1[3] / (int)(uint)*(byte *)(psVar1 + 2)) * 8,(int)pmVar3->x,
                   (int)*psVar1,clearRect[1]._8_4_ + 4);
    }
    iVar2 = iVar2 + 7;
    iVar4 = iVar4 + 1;
    psVar1 = psVar1 + 8;
    pmVar3 = pmVar3 + 1;
  } while (iVar4 < 8);
  return;
}



// decompiled code
// original method signature: 
// int /*$ra*/ memcard_data_size()
 // line 133, offset 0x800b9a58
	/* begin block 1 */
		// Start line: 285
	/* end block 1 */
	// End Line: 286

	/* begin block 2 */
		// Start line: 286
	/* end block 2 */
	// End Line: 287

/* WARNING: Unknown calling convention yet parameter storage is locked */

int memcard_data_size(void)

{
  short *psVar1;
  short *psVar2;
  short *unaff_s0;
  short *psVar3;
  int unaff_s1;
  short *unaff_s2;
  int unaff_s3;
  
  while( true ) {
    unaff_s1 = unaff_s1 + 7;
    unaff_s3 = unaff_s3 + 1;
    psVar3 = unaff_s0 + 8;
    unaff_s2 = unaff_s2 + 8;
    if (unaff_s3 >= 8) break;
    psVar1 = unaff_s0 + 0xb;
    psVar2 = unaff_s0 + 10;
    unaff_s0 = psVar3;
    if ((int)(uint)*(byte *)psVar2 <= (int)*psVar1) {
      FUN_8002a9a4(PTR_ARRAY_800d5a20[1] +
                   (unaff_s1 + (int)*psVar1 / (int)(uint)*(byte *)psVar2) * 8,(int)*unaff_s2,
                   (int)*psVar3,clearRect[1]._8_4_ + 4);
      unaff_s0 = psVar3;
    }
  }
  return (uint)(unaff_s3 < 8);
}



// decompiled code
// original method signature: 
// int /*$ra*/ memcard_initialize(struct memcard_t *memcard /*$s0*/, void *gt /*$a1*/, int nblocks /*$s2*/, void *buffer /*$s3*/, int nbytes /*stack 16*/)
 // line 148, offset 0x800b9a60
	/* begin block 1 */
		// Start line: 149
		// Start offset: 0x800B9A60
		// Variables:
	// 		int header_size; // $s1
	/* end block 1 */
	// End offset: 0x800B9B00
	// End Line: 177

	/* begin block 2 */
		// Start line: 315
	/* end block 2 */
	// End Line: 316

int memcard_initialize(memcard_t *memcard,void *gt,int nblocks,void *buffer,int nbytes)

{
  short *unaff_s0;
  int unaff_s1;
  short *unaff_s2;
  int unaff_s3;
  
  while( true ) {
    unaff_s3 = unaff_s3 + 1;
    unaff_s2 = unaff_s2 + 8;
    if (unaff_s3 >= 8) break;
    if ((int)(uint)*(byte *)(unaff_s0 + 10) <= (int)unaff_s0[0xb]) {
      FUN_8002a9a4(PTR_ARRAY_800d5a20[1] +
                   (unaff_s1 + (int)unaff_s0[0xb] / (int)(uint)*(byte *)(unaff_s0 + 10)) * 8,
                   (int)*unaff_s2,(int)unaff_s0[8],clearRect[1]._8_4_ + 4);
    }
    unaff_s1 = unaff_s1 + 7;
    unaff_s0 = unaff_s0 + 8;
  }
  return (uint)(unaff_s3 < 8);
}



// decompiled code
// original method signature: 
// void /*$ra*/ memcard_end(struct memcard_t *memcard /*$s0*/)
 // line 182, offset 0x800b9b20
	/* begin block 1 */
		// Start line: 400
	/* end block 1 */
	// End Line: 401

void memcard_end(memcard_t *memcard)

{
  undefined4 unaff_s0;
  undefined4 *unaff_s1;
  
  *unaff_s1 = unaff_s0;
  if (*(int *)(unaff_s1[1] + 0x20) != -0x7ff30460) {
    if ((gameTrackerX.animObjLine & 0x8000000) == 0) {
                    /* WARNING: Subroutine does not return */
      FUN_8004fe84();
    }
    unaff_s1[1] = 0;
  }
  return;
}



// decompiled code
// original method signature: 
// int /*$ra*/ maybe_start(struct memcard_t *memcard /*$s0*/)
 // line 190, offset 0x800b9b64
	/* begin block 1 */
		// Start line: 416
	/* end block 1 */
	// End Line: 417

int maybe_start(memcard_t *memcard)

{
  int in_v0;
  
  return in_v0;
}



// decompiled code
// original method signature: 
// int /*$ra*/ memcard_main_menu(void *gt /*$a0*/, int index /*$s1*/)
 // line 209, offset 0x800b9bd0
	/* begin block 1 */
		// Start line: 210
		// Start offset: 0x800B9BD0
		// Variables:
	// 		struct memcard_t *memcard; // $s0
	/* end block 1 */
	// End offset: 0x800B9C10
	// End Line: 215

	/* begin block 2 */
		// Start line: 455
	/* end block 2 */
	// End Line: 456

int memcard_main_menu(void *gt,int index)

{
                    /* WARNING: Subroutine does not return */
  FUN_800bcdac(gt,0,0x10);
}



// decompiled code
// original method signature: 
// int /*$ra*/ memcard_pause_menu(void *gt /*$a0*/, int index /*$s1*/)
 // line 217, offset 0x800b9c24
	/* begin block 1 */
		// Start line: 218
		// Start offset: 0x800B9C24
		// Variables:
	// 		struct memcard_t *memcard; // $s0
	/* end block 1 */
	// End offset: 0x800B9C64
	// End Line: 223

	/* begin block 2 */
		// Start line: 472
	/* end block 2 */
	// End Line: 473

int memcard_pause_menu(void *gt,int index)

{
  int in_v0;
  int iVar1;
  int unaff_s0;
  
  (**(code **)(in_v0 + 4))();
  iVar1 = (**(code **)(*(int *)(unaff_s0 + 4) + 0x14))(*(undefined4 *)(unaff_s0 + 8));
  FUN_800b9b70();
  return iVar1;
}



// decompiled code
// original method signature: 
// void * /*$ra*/ gt2mcmenu(void *gt /*$a0*/)
 // line 229, offset 0x800b9c78
	/* begin block 1 */
		// Start line: 231
		// Start offset: 0x800B9C78
		// Variables:
	// 		struct memcard_t *memcard; // $v0
	/* end block 1 */
	// End offset: 0x800B9C78
	// End Line: 231

	/* begin block 2 */
		// Start line: 497
	/* end block 2 */
	// End Line: 498

	/* begin block 3 */
		// Start line: 498
	/* end block 3 */
	// End Line: 499

void * gt2mcmenu(void *gt)

{
  void *in_v0;
  
  return in_v0;
}



// decompiled code
// original method signature: 
// void /*$ra*/ memcard_pop(void *opaque /*$a0*/)
 // line 235, offset 0x800b9c8c
	/* begin block 1 */
		// Start line: 509
	/* end block 1 */
	// End Line: 510

void memcard_pop(void *opaque)

{
  (**(code **)(*(int *)((int)opaque + 4) + 0x10))(*(undefined4 *)((int)opaque + 8));
  FUN_800b9b70(opaque);
  *(undefined2 *)((int)opaque + 0xc) = 0;
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ memcard_start(void *opaque /*$a0*/)
 // line 243, offset 0x800b9cc8
	/* begin block 1 */
		// Start line: 528
	/* end block 1 */
	// End Line: 529

void memcard_start(void *opaque)

{
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ memcard_load(void *opaque /*$a0*/)
 // line 252, offset 0x800b9d0c
	/* begin block 1 */
		// Start line: 549
	/* end block 1 */
	// End Line: 550

void memcard_load(void *opaque)

{
  int unaff_s0;
  
  *(undefined2 *)(unaff_s0 + 0xc) = 1;
  (**(code **)(*(int *)(unaff_s0 + 4) + 0xc))();
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ memcard_save(void *opaque /*$a0*/)
 // line 261, offset 0x800b9d58
	/* begin block 1 */
		// Start line: 569
	/* end block 1 */
	// End Line: 570

void memcard_save(void *opaque)

{
  int in_v0;
  int unaff_s0;
  
  if (in_v0 != 0) {
    (**(code **)(*(int *)(unaff_s0 + 4) + 0x18))(*(undefined4 *)(unaff_s0 + 8));
  }
  return;
}



// decompiled code
// original method signature: 
// void /*$ra*/ memcard_item(void *opaque /*$a0*/, TDRFuncPtr_memcard_item1fn fn /*$a1*/, long parameter /*$a2*/, long flags /*$a3*/, char *text /*stack 16*/)
 // line 266, offset 0x800b9d78
	/* begin block 1 */
		// Start line: 579
	/* end block 1 */
	// End Line: 580

void memcard_item(void *opaque,TDRFuncPtr_memcard_item1fn fn,long parameter,long flags,char *text)

{
  return;
}





